

	.FUNCT	BE-SPECIFIC
	PRINTI	"(Be specific: what do you want to "
	RTRUE	


	.FUNCT	TO-DO-THING-USE,STR1,STR2
	PRINTI	"(To "
	PRINT	STR1
	PRINTI	" something, use the command: "
	PRINT	STR2
	PRINTR	" THING.)"


	.FUNCT	CANT-USE,PTR,BUF,?TMP1
	SET	'QUOTE-FLAG,FALSE-VALUE
	SET	'P-OFLAG,FALSE-VALUE
	PRINTI	"(This story can't understand the word """
	MUL	PTR,2 >BUF
	ADD	P-LEXV,BUF
	GETB	STACK,2 >?TMP1
	ADD	P-LEXV,BUF
	GETB	STACK,3
	CALL	WORD-PRINT,?TMP1,STACK
	PRINTR	""" when you use it that way.)"


	.FUNCT	DONT-UNDERSTAND
	PRINTR	"(That sentence didn't make sense. Please reword it or try something else.)"


	.FUNCT	NOT-IN-SENTENCE,STR
	PRINTI	"(There aren't "
	PRINT	STR
	PRINTR	" in that sentence!)"


	.FUNCT	WALLS-F
	FSET?	HERE,INDOORSBIT /?CCL3
	CALL	CANT-SEE-ANY,WALLS
	RETURN	2
?CCL3:	CALL	GETTING-INTO?
	ZERO?	STACK \?PRG10
	EQUAL?	PRSA,V?LOOK-BEHIND \?CCL7
?PRG10:	CALL	PICK-ONE,YUKS
	PRINT	STACK
	CRLF	
	RTRUE	
?CCL7:	EQUAL?	PRSA,V?LOOK-UNDER \?CCL13
	PRINTR	"There's a floor there."
?CCL13:	CALL	HURT?,WALLS
	ZERO?	STACK \?CTR16
	CALL	MOVING?,WALLS
	ZERO?	STACK /?CCL17
?CTR16:	CALL	SAY-THE,WALLS
	PRINTR	" is not affected."
?CCL17:	CALL	TALKING-TO?,WALLS
	ZERO?	STACK \?PRG26
	EQUAL?	PRSA,V?YELL \?CCL23
?PRG26:	PRINTI	"Talking to walls"
	CALL	SIGN-OF-COLLAPSE
	RETURN	2
?CCL23:	CALL	YOU-DONT-NEED,WALLS
	RETURN	2


	.FUNCT	CEILING-F
	FSET?	HERE,INDOORSBIT /?CCL3
	CALL	CANT-SEE-ANY,CEILING
	RETURN	2
?CCL3:	EQUAL?	PRSA,V?LOOK-UNDER \FALSE
	CALL	V-LOOK
	RTRUE	


	.FUNCT	ME-F,CONTEXT=0,OLIT
	EQUAL?	PRSA,V?ALARM \?CCL3
	PRINTR	"You're already wide awake."
?CCL3:	CALL	TALKING-TO?,ME
	ZERO?	STACK \?CTR6
	EQUAL?	PRSA,V?YELL \?CCL7
?CTR6:	CALL	TALK-TO-SELF
	RETURN	2
?CCL7:	EQUAL?	PRSA,V?LISTEN \?CCL13
	PRINT	CANT
	PRINTR	" help doing that."
?CCL13:	EQUAL?	PRSA,V?GIVE \?CCL17
	EQUAL?	PRSI,ME \?CCL17
	CALL	HELD?,PRSO
	ZERO?	STACK /?CCL22
	PRINTR	"You already have it."
?CCL22:	CALL	PERFORM,V?TAKE,PRSO
	RTRUE	
?CCL17:	EQUAL?	PRSA,V?KILL \?CCL26
	PRINTR	"Desperate? Call the Samaritans."
?CCL26:	EQUAL?	PRSA,V?FIND \?CCL30
	PRINTR	"You're right here!"
?CCL30:	CALL	HURT?,ME
	ZERO?	STACK /FALSE
	PRINTR	"Punishing yourself that way won't help matters."


	.FUNCT	TALK-TO-SELF
	PRINTI	"Talking to yourself"
	CALL	SIGN-OF-COLLAPSE
	CALL	PCLEAR
	RSTACK	


	.FUNCT	SIGN-OF-COLLAPSE
	PRINTR	" is said to be a sign of impending mental collapse."


	.FUNCT	GLOBAL-ROOM-F
	EQUAL?	PRSA,V?LOOK-INSIDE,V?EXAMINE,V?LOOK \?CCL3
	CALL	V-LOOK
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?DROP,V?THROUGH,V?ENTER /?CTR4
	EQUAL?	PRSA,V?EXIT \?CCL5
?CTR4:	CALL	V-WALK-AROUND
	RETURN	2
?CCL5:	EQUAL?	PRSA,V?WALK-AROUND \FALSE
	PRINTR	"Walking around the area reveals nothing new.

(If you want to go somewhere, just type a direction.)"


	.FUNCT	OBJECT-IS-LOCKED
	PRINT	CANT
	PRINTR	" do that. It's locked."


	.FUNCT	CANT-SEE-ANY,THING=0,STRING?=0
	CALL	YOU-CANT-SEE
	ZERO?	STRING? /?CCL3
	PRINT	THING
	JUMP	?PRG16
?CCL3:	ZERO?	THING /?PRG14
	FSET?	THING,NARTICLEBIT /?PRG12
	PRINTI	"any "
?PRG12:	PRINTD	THING
	JUMP	?PRG16
?PRG14:	PRINTI	"that"
?PRG16:	PRINTR	" here!"


	.FUNCT	YOU-CANT-SEE
	SET	'CLOCK-WAIT,TRUE-VALUE
	CALL	PCLEAR
	PRINT	CANT
	PRINTI	" see "
	RTRUE	


	.FUNCT	HOW?
	PRINTR	"How do you intend to do that?"


	.FUNCT	PRESUMABLY-YOU-WANT-TO,STR,THING=0
	PRINT	I-ASSUME
	PRINTC	32
	PRINT	STR
	PRINTC	32
	ZERO?	THING /?PRG8
	CALL	ARTICLE,THING,TRUE-VALUE
	PRINTD	THING
	JUMP	?PRG10
?PRG8:	PRINTI	"it"
?PRG10:	PRINTR	".)"


	.FUNCT	NOT-LIKELY,THING,STR
	PRINTI	"It"
	CALL	PICK-ONE,LIKELIES
	PRINT	STACK
	PRINTI	" that "
	CALL	ARTICLE,THING,TRUE-VALUE
	PRINTD	THING
	PRINTC	32
	PRINT	STR
	PRINTR	"."


	.FUNCT	YOUD-HAVE-TO,STR,THING
	PRINTI	"You'd have to "
	PRINT	STR
	PRINTC	32
	CALL	ARTICLE,THING,TRUE-VALUE
	PRINTD	THING
	PRINTR	" to do that."


	.FUNCT	DO-TO
	PRINTI	" do that to "
	RTRUE	

	.ENDI
