

	.FUNCT	GO
START::

?FCN:	SET	'LIT,TRUE-VALUE
	SET	'WINNER,PROTAGONIST
	SET	'HERE,THE-ROOM
	CALL	RESET-THEM
	CALL	QUEUE,I-PROMPT,1
	PUT	STACK,0,1
	CALL	V-VERSION
	CRLF	
	CALL	V-LOOK
	CALL	DO-MAIN-LOOP
	JUMP	?FCN


	.FUNCT	RESET-THEM
	CALL	PCLEAR
	SET	'P-HIM-OBJECT,NOT-HERE-OBJECT
	SET	'P-HER-OBJECT,NOT-HERE-OBJECT
	SET	'P-THEM-OBJECT,NOT-HERE-OBJECT
	RETURN	P-THEM-OBJECT


	.FUNCT	PCLEAR
	SET	'P-CONT,FALSE-VALUE
	SET	'QUOTE-FLAG,FALSE-VALUE
	RETURN	QUOTE-FLAG


	.FUNCT	DO-MAIN-LOOP,X
?PRG1:	CALL	MAIN-LOOP >X
	JUMP	?PRG1


	.FUNCT	MAIN-LOOP,ICNT,OCNT,NUM,CNT,OBJ,TBL,V,PTBL,OBJ1,TMP,X,?TMP1
?PRG1:	SET	'CNT,0
	SET	'OBJ,FALSE-VALUE
	SET	'PTBL,TRUE-VALUE
	EQUAL?	QCONTEXT-ROOM,HERE /?CND3
	SET	'QCONTEXT,FALSE-VALUE
?CND3:	CALL	PARSER >P-WON
	ZERO?	P-WON /?CCL7
	GET	P-PRSI,P-MATCHLEN >ICNT
	GET	P-PRSO,P-MATCHLEN >OCNT
	ZERO?	P-IT-OBJECT /?CND8
	CALL	ACCESSIBLE?,P-IT-OBJECT
	ZERO?	STACK /?CND8
	SET	'TMP,FALSE-VALUE
?PRG12:	IGRTR?	'CNT,ICNT /?REP13
	GET	P-PRSI,CNT
	EQUAL?	STACK,IT \?PRG12
	PUT	P-PRSI,CNT,P-IT-OBJECT
	SET	'TMP,TRUE-VALUE
?REP13:	ZERO?	TMP \?CND19
	SET	'CNT,0
?PRG21:	IGRTR?	'CNT,OCNT /?CND19
	GET	P-PRSO,CNT
	EQUAL?	STACK,IT \?PRG21
	PUT	P-PRSO,CNT,P-IT-OBJECT
?CND19:	SET	'CNT,0
?CND8:	ZERO?	OCNT \?CCL30
	SET	'NUM,OCNT
	JUMP	?CND28
?CCL30:	GRTR?	OCNT,1 \?CCL32
	SET	'TBL,P-PRSO
	ZERO?	ICNT \?CCL35
	SET	'OBJ,FALSE-VALUE
	JUMP	?CND33
?CCL35:	GET	P-PRSI,1 >OBJ
?CND33:	SET	'NUM,OCNT
	JUMP	?CND28
?CCL32:	GRTR?	ICNT,1 \?CCL37
	SET	'PTBL,FALSE-VALUE
	SET	'TBL,P-PRSI
	GET	P-PRSO,1 >OBJ
	SET	'NUM,ICNT
	JUMP	?CND28
?CCL37:	SET	'NUM,1
?CND28:	ZERO?	OBJ \?CND38
	EQUAL?	ICNT,1 \?CND38
	GET	P-PRSI,1 >OBJ
?CND38:	EQUAL?	PRSA,V?WALK \?CCL44
	CALL	PERFORM,PRSA,PRSO >V
	JUMP	?CND42
?CCL44:	ZERO?	NUM \?CCL46
	GETB	P-SYNTAX,P-SBITS
	BAND	STACK,P-SONUMS
	ZERO?	STACK \?CCL49
	CALL	PERFORM,PRSA >V
	SET	'PRSO,FALSE-VALUE
	JUMP	?CND42
?CCL49:	ZERO?	LIT \?CCL51
	CALL	PCLEAR
	CALL	TOO-DARK
	JUMP	?CND42
?CCL51:	CALL	PCLEAR
	PRINTI	"(There isn't anything to "
	GET	P-ITBL,P-VERBN >TMP
	EQUAL?	PRSA,V?TELL \?CCL56
	PRINTI	"talk to"
	JUMP	?PRG63
?CCL56:	ZERO?	P-MERGED \?CTR59
	ZERO?	P-OFLAG /?CCL60
?CTR59:	GET	TMP,0
	PRINTB	STACK
	JUMP	?PRG63
?CCL60:	GETB	TMP,2 >?TMP1
	GETB	TMP,3
	CALL	WORD-PRINT,?TMP1,STACK >V
?PRG63:	PRINTI	"!)"
	CRLF	
	SET	'V,FALSE-VALUE
	JUMP	?CND42
?CCL46:	SET	'X,0
	SET	'TMP,0
?PRG65:	IGRTR?	'CNT,NUM \?CCL69
	GRTR?	X,0 \?CCL72
	PRINTI	"(The "
	EQUAL?	X,NUM /?PRG79
	PRINTI	"other "
?PRG79:	PRINTI	"object"
	EQUAL?	X,1 /?PRG85
	PRINTC	115
?PRG85:	PRINTI	" that you mentioned "
	EQUAL?	X,1 /?PRG92
	PRINTI	"are"
	JUMP	?PRG94
?PRG92:	PRINTI	"is"
?PRG94:	PRINTI	"n't here!)"
	CRLF	
	JUMP	?CND42
?CCL72:	ZERO?	TMP \?CND42
	CALL	REFERRING
	JUMP	?CND42
?CCL69:	ZERO?	PTBL /?CCL99
	GET	P-PRSO,CNT >OBJ1
	JUMP	?CND97
?CCL99:	GET	P-PRSI,CNT >OBJ1
?CND97:	GRTR?	NUM,1 /?CCL101
	GET	P-ITBL,P-NC1
	GET	STACK,0
	EQUAL?	STACK,W?ALL,W?EVERYTHING \?CND100
?CCL101:	EQUAL?	OBJ1,NOT-HERE-OBJECT \?CCL106
	INC	'X
	JUMP	?PRG65
?CCL106:	EQUAL?	P-GETFLAGS,P-ALL \?CCL108
	CALL	DONT-ALL?,OBJ1,OBJ
	ZERO?	STACK \?PRG65
?CCL108:	CALL	ACCESSIBLE?,OBJ1
	ZERO?	STACK /?PRG65
	EQUAL?	OBJ1,PROTAGONIST /?PRG65
	EQUAL?	OBJ1,IT \?CCL117
	FSET?	P-IT-OBJECT,NARTICLEBIT /?CND118
	PRINTI	"The "
?CND118:	PRINTD	P-IT-OBJECT
	JUMP	?PRG126
?CCL117:	FSET?	OBJ1,NARTICLEBIT /?CND122
	PRINTI	"The "
?CND122:	PRINTD	OBJ1
?PRG126:	PRINTI	": "
?CND100:	SET	'TMP,TRUE-VALUE
	ZERO?	PTBL /?CCL130
	PUSH	OBJ1
	JUMP	?CND128
?CCL130:	PUSH	OBJ
?CND128:	CALL	QCONTEXT-CHECK,STACK >V
	ZERO?	PTBL /?CCL133
	SET	'PRSO,OBJ1
	JUMP	?CND131
?CCL133:	SET	'PRSO,OBJ
?CND131:	ZERO?	PTBL /?CCL136
	SET	'PRSI,OBJ
	JUMP	?CND134
?CCL136:	SET	'PRSI,OBJ1
?CND134:	CALL	PERFORM,PRSA,PRSO,PRSI >V
	EQUAL?	V,M-FATAL \?PRG65
?CND42:	EQUAL?	V,M-FATAL \?CND5
	SET	'P-CONT,FALSE-VALUE
	JUMP	?CND5
?CCL7:	SET	'P-CONT,FALSE-VALUE
?CND5:	ZERO?	P-WON /?CND141
	CALL	GAME-VERB?
	ZERO?	STACK \?CND141
	CALL	CLOCKER >V
?CND141:	SET	'PRSA,FALSE-VALUE
	SET	'PRSO,FALSE-VALUE
	SET	'PRSI,FALSE-VALUE
	JUMP	?PRG1


	.FUNCT	DONT-ALL?,O,I,L
	LOC	O >L
	EQUAL?	O,I /TRUE
	EQUAL?	PRSA,V?TAKE \?CCL5
	EQUAL?	L,PROTAGONIST,WINNER /TRUE
	FSET?	O,TAKEBIT /?CCL10
	FSET?	O,TRYTAKEBIT \TRUE
?CCL10:	ZERO?	I /?CCL14
	EQUAL?	L,I \TRUE
	CALL	SEE-INSIDE?,I
	ZERO?	STACK /TRUE
	RFALSE	
?CCL14:	EQUAL?	L,HERE /FALSE
	FSET?	L,SURFACEBIT /FALSE
	FSET?	L,ACTORBIT /FALSE
	RTRUE	
?CCL5:	EQUAL?	PRSA,V?DROP,V?PUT,V?PUT-ON /?CTR26
	EQUAL?	PRSA,V?THROW \FALSE
?CTR26:	EQUAL?	L,PROTAGONIST,WINNER /FALSE
	RTRUE	


	.FUNCT	GAME-VERB?,V=0
	ZERO?	V \?CND1
	SET	'V,PRSA
?CND1:	EQUAL?	V,V?BRIEF,V?SCORE,V?VERBOSE /TRUE
	EQUAL?	V,V?QUIT,V?RESTART,V?RESTORE /TRUE
	EQUAL?	V,V?SAVE,V?SCRIPT,V?SUPER-BRIEF /TRUE
	EQUAL?	V,V?TELL,V?UNSCRIPT,V?VERSION /TRUE
	EQUAL?	V,V?TIME /TRUE
	RFALSE	


	.FUNCT	QCONTEXT-CHECK,PRSO,OTHER,WHO=0,N=0
	EQUAL?	PRSA,V?HELP /?CCL3
	EQUAL?	PRSA,V?TELL \FALSE
	EQUAL?	PRSO,PROTAGONIST \FALSE
?CCL3:	FIRST?	HERE >OTHER /?PRG8
?PRG8:	ZERO?	OTHER /?REP9
	FSET?	OTHER,ACTORBIT \?CND10
	EQUAL?	OTHER,PROTAGONIST /?CND10
	INC	'N
	SET	'WHO,OTHER
?CND10:	NEXT?	OTHER >OTHER /?PRG8
	JUMP	?PRG8
?REP9:	EQUAL?	1,N \?CND16
	ZERO?	QCONTEXT \?CND16
	CALL	SAID-TO,WHO
?CND16:	CALL	QCONTEXT-GOOD?
	ZERO?	STACK /FALSE
	EQUAL?	WINNER,PROTAGONIST \FALSE
	SET	'WINNER,QCONTEXT
	CALL	SPOKEN-TO,QCONTEXT
	RSTACK	


	.FUNCT	SAID-TO,WHO
	SET	'QCONTEXT,WHO
	LOC	WHO >QCONTEXT-ROOM
	RETURN	QCONTEXT-ROOM


	.FUNCT	SPOKEN-TO,WHO
	CALL	PCLEAR
	PRINTI	"(spoken to "
	CALL	ARTICLE,WHO,TRUE-VALUE
	PRINTD	WHO
	PRINTR	")"


	.FUNCT	QCONTEXT-GOOD?
	ZERO?	QCONTEXT /FALSE
	FSET?	QCONTEXT,ACTORBIT \FALSE
	EQUAL?	HERE,QCONTEXT-ROOM \FALSE
	CALL	META-LOC,QCONTEXT
	EQUAL?	HERE,STACK /TRUE
	RFALSE	


	.FUNCT	ACCESSIBLE?,OBJ
	FSET?	OBJ,INVISIBLE /FALSE
	CALL	META-LOC,OBJ
	EQUAL?	STACK,WINNER,HERE,GLOBAL-OBJECTS /TRUE
	CALL	VISIBLE?,OBJ
	ZERO?	STACK /FALSE
	RTRUE	


	.FUNCT	VISIBLE?,OBJ,L
	LOC	OBJ >L
	ZERO?	L /FALSE
	FSET?	OBJ,INVISIBLE /FALSE
	EQUAL?	L,GLOBAL-OBJECTS /FALSE
	EQUAL?	L,PROTAGONIST,HERE,WINNER /TRUE
	EQUAL?	L,LOCAL-GLOBALS \?CCL11
	CALL	GLOBAL-IN?,OBJ,HERE
	ZERO?	STACK \TRUE
?CCL11:	CALL	SEE-INSIDE?,L
	ZERO?	STACK /FALSE
	CALL	VISIBLE?,L
	ZERO?	STACK /FALSE
	RTRUE	


	.FUNCT	SEE-INSIDE?,CONTAINER
	ZERO?	P-MOBY-FLAG \TRUE
	FSET?	CONTAINER,SURFACEBIT /TRUE
	FSET?	CONTAINER,CONTBIT \?CCL7
	FSET?	CONTAINER,OPENBIT /TRUE
	FSET?	CONTAINER,TRANSBIT /TRUE
	RFALSE	
?CCL7:	FSET?	CONTAINER,ACTORBIT \FALSE
	EQUAL?	CONTAINER,PROTAGONIST /FALSE
	RTRUE	


	.FUNCT	META-LOC,OBJ
?PRG1:	ZERO?	OBJ /FALSE
	IN?	OBJ,GLOBAL-OBJECTS \?CCL7
	RETURN	GLOBAL-OBJECTS
?CCL7:	IN?	OBJ,ROOMS \?CCL9
	RETURN	OBJ
?CCL9:	FSET?	OBJ,INVISIBLE /FALSE
	LOC	OBJ >OBJ
	JUMP	?PRG1


	.FUNCT	QUEUE,RTN,TICK,CINT
	CALL	INT,RTN >CINT
	PUT	CINT,C-TICK,TICK
	RETURN	CINT


	.FUNCT	INT,RTN,DEMON=0,E,C,INT
	ADD	C-TABLE,C-TABLELEN >E
	ADD	C-TABLE,C-INTS >C
?PRG1:	EQUAL?	C,E \?CCL5
	SUB	C-INTS,C-INTLEN >C-INTS
	ZERO?	DEMON /?PEN6
	SUB	C-DEMONS,C-INTLEN >C-DEMONS
?PEN6:	ADD	C-TABLE,C-INTS >INT
	PUT	INT,C-RTN,RTN
	RETURN	INT
?CCL5:	GET	C,C-RTN
	EQUAL?	STACK,RTN \?CND3
	RETURN	C
?CND3:	ADD	C,C-INTLEN >C
	JUMP	?PRG1


	.FUNCT	CLOCKER,C,E,I,TICK,FLG=0
	ZERO?	CLOCK-WAIT /?CND1
	SET	'CLOCK-WAIT,FALSE-VALUE
	RFALSE	
?CND1:	ZERO?	P-WON /?CCL5
	PUSH	C-INTS
	JUMP	?CND3
?CCL5:	PUSH	C-DEMONS
?CND3:	ADD	C-TABLE,STACK >C
	ADD	C-TABLE,C-TABLELEN >E
?PRG6:	EQUAL?	C,E \?CCL10
	IGRTR?	'MOVES,59 /?CCL12
	RETURN	FLG
?CCL12:	SET	'MOVES,0
	IGRTR?	'SCORE,23 /?CCL14
	RETURN	FLG
?CCL14:	SET	'SCORE,0
	RETURN	FLG
?CCL10:	GET	C,C-ENABLED?
	ZERO?	STACK /?CND8
	GET	C,C-TICK >TICK
	ZERO?	TICK /?CND8
	SUB	TICK,1
	PUT	C,C-TICK,STACK
	GRTR?	TICK,1 /?CND8
	GET	C,C-RTN
	CALL	STACK
	ZERO?	STACK /?CND8
	SET	'FLG,TRUE-VALUE
?CND8:	ADD	C,C-INTLEN >C
	JUMP	?PRG6

	.ENDI
