

	.FUNCT	PARSER,PTR=P-LEXSTART,WRD,VAL=0,VERB=0,OF-FLAG=0,LEN,DIR=0,NW=0,LW=0,CNT=-1,OWINNER,OMERGED,TMP1,?TMP1,?TMP2
?PRG1:	IGRTR?	'CNT,P-ITBLLEN /?REP2
	ZERO?	P-OFLAG \?CND6
	GET	P-ITBL,CNT
	PUT	P-OTBL,CNT,STACK
?CND6:	PUT	P-ITBL,CNT,0
	JUMP	?PRG1
?REP2:	SET	'P-NUMBER,-1
	SET	'P-NAM,FALSE-VALUE
	SET	'P-ADJ,FALSE-VALUE
	SET	'P-ADVERB,FALSE-VALUE
	SET	'OMERGED,P-MERGED
	SET	'P-MERGED,FALSE-VALUE
	SET	'P-END-ON-PREP,FALSE-VALUE
	PUT	P-PRSO,P-MATCHLEN,0
	PUT	P-PRSI,P-MATCHLEN,0
	PUT	P-BUTS,P-MATCHLEN,0
	SET	'OWINNER,WINNER
	ZERO?	QUOTE-FLAG \?CND8
	EQUAL?	WINNER,PROTAGONIST /?CND8
	SET	'WINNER,PROTAGONIST
	SET	'LAST-PLAYER-LOC,HERE
	LOC	WINNER >HERE
	CALL	LIT?,HERE >LIT
?CND8:	ZERO?	RESERVE-PTR /?CCL14
	SET	'PTR,RESERVE-PTR
	CALL	STUFF,P-LEXV,RESERVE-LEXV
	CALL	INBUF-STUFF,P-INBUF,RESERVE-INBUF
	EQUAL?	VERBOSE,1,2 \?CND15
	EQUAL?	PROTAGONIST,WINNER \?CND15
	CRLF	
?CND15:	SET	'RESERVE-PTR,FALSE-VALUE
	SET	'P-CONT,FALSE-VALUE
	JUMP	?CND12
?CCL14:	ZERO?	P-CONT /?CCL20
	SET	'PTR,P-CONT
	SET	'P-CONT,FALSE-VALUE
	ZERO?	SAYING? /?CCL23
	SET	'SAYING?,FALSE-VALUE
	JUMP	?CND12
?CCL23:	ZERO?	SUPER-BRIEF \?CND12
	EQUAL?	PROTAGONIST,WINNER \?CND12
	CRLF	
	JUMP	?CND12
?CCL20:	SET	'SAYING?,FALSE-VALUE
	SET	'WINNER,PROTAGONIST
	SET	'QUOTE-FLAG,FALSE-VALUE
	SET	'LAST-PLAYER-LOC,HERE
	LOC	WINNER >HERE
	CALL	LIT?,HERE >LIT
	ZERO?	SUPER-BRIEF \?CND27
	CRLF	
?CND27:	ZERO?	P-PROMPT /?CND29
	ZERO?	P-OFLAG \?CND29
	EQUAL?	P-PROMPT,P-PROMPT-START \?CCL35
	PRINT	OKAY
	PRINTI	"what do you want to do now?"
	JUMP	?CND33
?CCL35:	DLESS?	'P-PROMPT,1 \?PRG42
	PRINTI	"(You won't see ""What next?"" any more.)
"
	JUMP	?CND33
?PRG42:	PRINTI	"What next?"
?CND33:	CRLF	
?CND29:	PUTB	P-LEXV,0,59
	PRINTC	62
	READ	P-INBUF,P-LEXV
?CND12:	GETB	P-LEXV,P-LEXWORDS >P-LEN
	GET	P-LEXV,PTR
	EQUAL?	W?QUOTE,STACK \?CND46
	CALL	QCONTEXT-GOOD?
	ZERO?	STACK /?CND46
	ADD	PTR,P-LEXELEN >PTR
	DEC	'P-LEN
?CND46:	GET	P-LEXV,PTR
	EQUAL?	W?THEN,STACK \?CND50
	ADD	PTR,P-LEXELEN >PTR
	DEC	'P-LEN
?CND50:	LESS?	1,P-LEN \?CND52
	GET	P-LEXV,PTR
	EQUAL?	W?GO,STACK \?CND52
	ADD	PTR,P-LEXELEN
	GET	P-LEXV,STACK >NW
	ZERO?	NW /?CND52
	CALL	WT?,NW,64
	ZERO?	STACK /?CND52
	ADD	PTR,P-LEXELEN >PTR
	DEC	'P-LEN
?CND52:	ZERO?	P-LEN \?CCL60
	PRINTI	"Beg pardon?"
	CRLF	
	RFALSE	
?CCL60:	GET	P-LEXV,PTR
	EQUAL?	STACK,W?OOPS \?CCL64
	ADD	PTR,P-LEXELEN
	GET	P-LEXV,STACK
	EQUAL?	STACK,W?PERIOD,W?COMMA \?CND65
	ADD	PTR,P-LEXELEN >PTR
	DEC	'P-LEN
?CND65:	GRTR?	P-LEN,1 /?CCL69
	PRINTI	"I can't help your clumsiness."
	CRLF	
	RFALSE	
?CCL69:	GET	OOPS-TABLE,O-PTR >VAL
	ZERO?	VAL /?CCL73
	GRTR?	P-LEN,2 \?CND74
	PRINTI	"[Warning: only the first word after OOPS is used.]"
	CRLF	
?CND74:	ADD	PTR,P-LEXELEN
	GET	P-LEXV,STACK
	PUT	AGAIN-LEXV,VAL,STACK
	SET	'WINNER,OWINNER
	MUL	PTR,P-LEXELEN
	ADD	STACK,6
	GETB	P-LEXV,STACK >?TMP2
	MUL	PTR,P-LEXELEN
	ADD	STACK,7
	GETB	P-LEXV,STACK >?TMP1
	MUL	VAL,P-LEXELEN
	ADD	STACK,3
	CALL	INBUF-ADD,?TMP2,?TMP1,STACK
	CALL	STUFF,P-LEXV,AGAIN-LEXV
	GETB	P-LEXV,P-LEXWORDS >P-LEN
	GET	OOPS-TABLE,O-START >PTR
	CALL	INBUF-STUFF,P-INBUF,OOPS-INBUF
	JUMP	?CND58
?CCL73:	PUT	OOPS-TABLE,O-END,FALSE-VALUE
	PRINTI	"There was no word to replace!"
	CRLF	
	RFALSE	
?CCL64:	PUT	OOPS-TABLE,O-END,FALSE-VALUE
?CND58:	GET	P-LEXV,PTR
	EQUAL?	STACK,W?AGAIN,W?G \?CCL82
	ZERO?	P-OFLAG /?CCL85
	PRINTI	"It's difficult to repeat fragments."
	CRLF	
	RFALSE	
?CCL85:	GRTR?	P-LEN,1 \?CCL89
	ADD	PTR,P-LEXELEN
	GET	P-LEXV,STACK
	EQUAL?	STACK,W?PERIOD,W?COMMA,W?THEN /?CTR91
	ADD	PTR,P-LEXELEN
	GET	P-LEXV,STACK
	EQUAL?	STACK,W?AND \?PRG95
?CTR91:	ADD	PTR,4 >PTR
	GETB	P-LEXV,P-LEXWORDS
	SUB	STACK,2
	PUTB	P-LEXV,P-LEXWORDS,STACK
	JUMP	?CND83
?PRG95:	PRINTI	"I couldn't understand that sentence."
	CRLF	
	RFALSE	
?CCL89:	ADD	PTR,P-LEXELEN >PTR
	GETB	P-LEXV,P-LEXWORDS
	SUB	STACK,1
	PUTB	P-LEXV,P-LEXWORDS,STACK
?CND83:	GETB	P-LEXV,P-LEXWORDS
	GRTR?	STACK,0 \?CCL99
	CALL	STUFF,RESERVE-LEXV,P-LEXV
	CALL	INBUF-STUFF,RESERVE-INBUF,P-INBUF
	SET	'RESERVE-PTR,PTR
	JUMP	?CND97
?CCL99:	SET	'RESERVE-PTR,FALSE-VALUE
?CND97:	SET	'WINNER,OWINNER
	SET	'P-MERGED,OMERGED
	CALL	INBUF-STUFF,P-INBUF,OOPS-INBUF
	CALL	STUFF,P-LEXV,AGAIN-LEXV
	SET	'CNT,-1
	SET	'DIR,AGAIN-DIR
?PRG100:	IGRTR?	'CNT,P-ITBLLEN /?CND80
	GET	P-OTBL,CNT
	PUT	P-ITBL,CNT,STACK
	JUMP	?PRG100
?CCL82:	CALL	STUFF,AGAIN-LEXV,P-LEXV
	CALL	INBUF-STUFF,OOPS-INBUF,P-INBUF
	PUT	OOPS-TABLE,O-START,PTR
	MUL	4,P-LEN
	PUT	OOPS-TABLE,O-LENGTH,STACK
	GETB	P-LEXV,P-LEXWORDS
	MUL	P-LEXELEN,STACK
	ADD	PTR,STACK
	MUL	2,STACK >LEN
	SUB	LEN,1
	GETB	P-LEXV,STACK >?TMP1
	SUB	LEN,2
	GETB	P-LEXV,STACK
	ADD	?TMP1,STACK
	PUT	OOPS-TABLE,O-END,STACK
	SET	'RESERVE-PTR,FALSE-VALUE
	SET	'LEN,P-LEN
	SET	'P-DIR,FALSE-VALUE
	SET	'P-NCN,0
	SET	'P-GETFLAGS,0
	PUT	P-ITBL,P-VERBN,0
?PRG105:	DLESS?	'P-LEN,0 \?CCL109
	SET	'QUOTE-FLAG,FALSE-VALUE
	JUMP	?CND80
?CCL109:	GET	P-LEXV,PTR >WRD
	CALL	BUZZER-WORD?,WRD
	ZERO?	STACK \FALSE
	ZERO?	WRD \?CTR112
	CALL	NUMBER?,PTR >WRD
	ZERO?	WRD /?CCL113
?CTR112:	EQUAL?	WRD,W?TO \?CCL118
	EQUAL?	VERB,ACT?TELL,ACT?ASK \?CCL118
	PUT	P-ITBL,P-VERB,ACT?TELL
	SET	'WRD,W?QUOTE
	JUMP	?CND116
?CCL118:	EQUAL?	WRD,W?THEN \?CND116
	GRTR?	P-LEN,0 \?CND116
	ZERO?	VERB \?CND116
	ZERO?	QUOTE-FLAG \?CND116
	PUT	P-ITBL,P-VERB,ACT?TELL
	PUT	P-ITBL,P-VERBN,0
	SET	'WRD,W?QUOTE
?CND116:	EQUAL?	WRD,W?PERIOD \?CCL128
	EQUAL?	LW,W?MR,W?MISS,W?MRS \?CCL128
	SET	'LW,0
	JUMP	?CND107
?CCL128:	EQUAL?	WRD,W?THEN,W?PERIOD,W?QUOTE \?CCL132
	EQUAL?	WRD,W?QUOTE \?CND133
	ZERO?	QUOTE-FLAG /?CCL137
	SET	'QUOTE-FLAG,FALSE-VALUE
	JUMP	?CND133
?CCL137:	SET	'QUOTE-FLAG,TRUE-VALUE
?CND133:	ZERO?	P-LEN /?PEN138
	ADD	PTR,P-LEXELEN >P-CONT
?PEN138:	PUTB	P-LEXV,P-LEXWORDS,P-LEN
	JUMP	?CND80
?CCL132:	CALL	WT?,WRD,16,3 >VAL
	ZERO?	VAL /?CCL141
	EQUAL?	VERB,FALSE-VALUE,ACT?WALK \?CCL141
	EQUAL?	LEN,1 /?CTR140
	EQUAL?	LEN,2 \?PRD147
	EQUAL?	VERB,ACT?WALK /?CTR140
?PRD147:	ADD	PTR,P-LEXELEN
	GET	P-LEXV,STACK >NW
	EQUAL?	NW,W?THEN,W?PERIOD,W?QUOTE \?PRD150
	GRTR?	LEN,1 /?CTR140
?PRD150:	ZERO?	QUOTE-FLAG /?PRD153
	EQUAL?	LEN,2 \?PRD153
	EQUAL?	NW,W?QUOTE /?CTR140
?PRD153:	GRTR?	LEN,2 \?CCL141
	EQUAL?	NW,W?COMMA,W?AND \?CCL141
?CTR140:	SET	'DIR,VAL
	EQUAL?	NW,W?COMMA,W?AND \?CND159
	ADD	PTR,P-LEXELEN
	CALL	CHANGE-LEXV,STACK,W?THEN
?CND159:	GRTR?	LEN,2 /?CND107
	SET	'QUOTE-FLAG,FALSE-VALUE
	JUMP	?CND80
?CCL141:	CALL	WT?,WRD,64,1 >VAL
	ZERO?	VAL /?CCL164
	ZERO?	VERB \?CCL164
	SET	'VERB,VAL
	PUT	P-ITBL,P-VERB,VAL
	PUT	P-ITBL,P-VERBN,P-VTBL
	PUT	P-VTBL,0,WRD
	MUL	PTR,2
	ADD	STACK,2 >TMP1
	GETB	P-LEXV,TMP1
	PUTB	P-VTBL,2,STACK
	ADD	TMP1,1
	GETB	P-LEXV,STACK
	PUTB	P-VTBL,3,STACK
	JUMP	?CND107
?CCL164:	CALL	WT?,WRD,8,0 >VAL
	ZERO?	VAL \?CTR167
	EQUAL?	WRD,W?A /?PRD172
	EQUAL?	WRD,W?BOTH,W?ALL,W?EVERYTHING /?PRD172
	CALL	WT?,WRD,32
	ZERO?	STACK \?PRD172
	CALL	WT?,WRD,128
	ZERO?	STACK /?CCL168
?PRD172:	SET	'VAL,0
	JUMP	?CTR167
?CCL168:	EQUAL?	WRD,W?OF \?CCL203
	ZERO?	OF-FLAG /?CTR205
	ADD	PTR,P-LEXELEN
	GET	P-LEXV,STACK
	EQUAL?	STACK,W?PERIOD,W?THEN \?CCL206
?CTR205:	CALL	CANT-USE,PTR
	RFALSE	
?CTR167:	GRTR?	P-LEN,1 \?CCL179
	ADD	PTR,P-LEXELEN
	GET	P-LEXV,STACK
	EQUAL?	STACK,W?OF \?CCL179
	EQUAL?	VERB,ACT?TAKE /?CCL179
	ZERO?	VAL \?CCL179
	EQUAL?	WRD,W?A /?CCL179
	EQUAL?	WRD,W?ALL,W?BOTH,W?EVERYTHING /?CCL179
	SET	'OF-FLAG,TRUE-VALUE
	JUMP	?CND107
?CCL179:	ZERO?	VAL /?CCL187
	ZERO?	P-LEN /?CTR186
	ADD	PTR,2
	GET	P-LEXV,STACK
	EQUAL?	STACK,W?THEN,W?PERIOD \?CCL187
?CTR186:	SET	'P-END-ON-PREP,TRUE-VALUE
	LESS?	P-NCN,2 \?CND107
	PUT	P-ITBL,P-PREP1,VAL
	PUT	P-ITBL,P-PREP1N,WRD
	JUMP	?CND107
?CCL187:	EQUAL?	P-NCN,2 \?CCL195
	PRINTI	"(There are too many nouns in that sentence!)"
	CRLF	
	RFALSE	
?CCL195:	INC	'P-NCN
	CALL	CLAUSE,PTR,VAL,WRD >PTR
	ZERO?	PTR /FALSE
	LESS?	PTR,0 \?CND107
	SET	'QUOTE-FLAG,FALSE-VALUE
?CND80:	PUT	OOPS-TABLE,O-PTR,FALSE-VALUE
	ZERO?	DIR /?CND214
	SET	'PRSA,V?WALK
	SET	'P-WALK-DIR,DIR
	SET	'AGAIN-DIR,DIR
	SET	'PRSO,DIR
	SET	'P-OFLAG,FALSE-VALUE
	RTRUE	
?CCL206:	SET	'OF-FLAG,FALSE-VALUE
?CND107:	SET	'LW,WRD
	ADD	PTR,P-LEXELEN >PTR
	JUMP	?PRG105
?CCL203:	CALL	WT?,WRD,4
	ZERO?	STACK \?CND107
	EQUAL?	VERB,ACT?TELL \?CCL211
	CALL	WT?,WRD,64
	ZERO?	STACK /?CCL211
	CALL	WAY-TO-TALK
	RFALSE	
?CCL211:	CALL	CANT-USE,PTR
	RFALSE	
?CCL113:	CALL	UNKNOWN-WORD,PTR
	RFALSE	
?CND214:	SET	'P-WALK-DIR,FALSE-VALUE
	SET	'AGAIN-DIR,FALSE-VALUE
	ZERO?	P-OFLAG /?CND216
	CALL	ORPHAN-MERGE
	ZERO?	STACK /?CND216
	SET	'WINNER,OWINNER
?CND216:	GET	P-ITBL,P-VERB
	ZERO?	STACK \?CND220
	PUT	P-ITBL,P-VERB,ACT?TELL
?CND220:	CALL	SYNTAX-CHECK
	ZERO?	STACK /FALSE
	CALL	SNARF-OBJECTS
	ZERO?	STACK /FALSE
	CALL	MANY-CHECK
	ZERO?	STACK /FALSE
	CALL	TAKE-CHECK
	ZERO?	STACK \TRUE
	RFALSE	


	.FUNCT	CHANGE-LEXV,PTR,WRD
	PUT	P-LEXV,PTR,WRD
	PUT	AGAIN-LEXV,PTR,WRD
	RTRUE	


	.FUNCT	WAY-TO-TALK
	PRINTR	"(Refer to your GENERIC manual for the correct way to talk to characters.)"


	.FUNCT	WT?,PTR,BIT,B1=5,OFFS=P-P1OFF,TYP
	GETB	PTR,P-PSOFF >TYP
	BTST	TYP,BIT \FALSE
	GRTR?	B1,4 /TRUE
	BAND	TYP,P-P1BITS >TYP
	EQUAL?	TYP,B1 /?CND7
	INC	'OFFS
?CND7:	GETB	PTR,OFFS
	RSTACK	


	.FUNCT	CLAUSE,PTR,VAL,WRD,OFF,NUM,ANDFLG=0,FIRST??=1,NW,LW=0,?TMP1
	SUB	P-NCN,1
	MUL	STACK,2 >OFF
	ZERO?	VAL /?CCL3
	ADD	P-PREP1,OFF >NUM
	PUT	P-ITBL,NUM,VAL
	ADD	NUM,1
	PUT	P-ITBL,STACK,WRD
	ADD	PTR,P-LEXELEN >PTR
	JUMP	?CND1
?CCL3:	INC	'P-LEN
?CND1:	ZERO?	P-LEN \?CND4
	DEC	'P-NCN
	RETURN	-1
?CND4:	ADD	P-NC1,OFF >NUM
	MUL	PTR,2
	ADD	P-LEXV,STACK
	PUT	P-ITBL,NUM,STACK
	GET	P-LEXV,PTR
	EQUAL?	STACK,W?THE,W?A,W?AN \?PRG8
	GET	P-ITBL,NUM
	ADD	STACK,4
	PUT	P-ITBL,NUM,STACK
?PRG8:	DLESS?	'P-LEN,0 \?CND10
	ADD	NUM,1 >?TMP1
	MUL	PTR,2
	ADD	P-LEXV,STACK
	PUT	P-ITBL,?TMP1,STACK
	RETURN	-1
?CND10:	GET	P-LEXV,PTR >WRD
	CALL	BUZZER-WORD?,WRD
	ZERO?	STACK \FALSE
	ZERO?	WRD \?CTR15
	CALL	NUMBER?,PTR >WRD
	ZERO?	WRD /?CCL16
?CTR15:	ZERO?	P-LEN \?CCL21
	SET	'NW,0
	JUMP	?CND19
?CCL21:	ADD	PTR,P-LEXELEN
	GET	P-LEXV,STACK >NW
?CND19:	EQUAL?	WRD,W?PERIOD \?CCL24
	EQUAL?	LW,W?MR,W?MRS,W?MISS \?CCL24
	SET	'LW,0
	JUMP	?CND12
?CCL24:	EQUAL?	WRD,W?AND,W?COMMA \?CCL28
	SET	'ANDFLG,TRUE-VALUE
	JUMP	?CND12
?CCL28:	EQUAL?	WRD,W?ALL,W?BOTH,W?EVERYTHING \?CCL30
	EQUAL?	NW,W?OF \?CND12
	DEC	'P-LEN
	ADD	PTR,P-LEXELEN >PTR
	JUMP	?CND12
?CCL30:	EQUAL?	WRD,W?THEN,W?PERIOD /?CTR33
	CALL	WT?,WRD,8
	ZERO?	STACK /?CCL34
	GET	P-ITBL,P-VERB
	ZERO?	STACK /?CCL34
	ZERO?	FIRST?? \?CCL34
?CTR33:	INC	'P-LEN
	ADD	NUM,1 >?TMP1
	MUL	PTR,2
	ADD	P-LEXV,STACK
	PUT	P-ITBL,?TMP1,STACK
	SUB	PTR,P-LEXELEN
	RSTACK	
?CCL34:	ZERO?	ANDFLG /?CCL41
	GET	P-ITBL,P-VERBN
	ZERO?	STACK /?CTR40
	CALL	VERB-DIR-ONLY?,WRD
	ZERO?	STACK /?CCL41
?CTR40:	SUB	PTR,4 >PTR
	ADD	PTR,2
	CALL	CHANGE-LEXV,STACK,W?THEN
	ADD	P-LEN,2 >P-LEN
	JUMP	?CND12
?CCL41:	CALL	WT?,WRD,128
	ZERO?	STACK /?CCL47
	GRTR?	P-LEN,0 \?CCL50
	EQUAL?	NW,W?OF \?CCL50
	EQUAL?	WRD,W?ALL,W?EVERYTHING \?CND12
?CCL50:	CALL	WT?,WRD,32
	ZERO?	STACK /?CCL54
	ZERO?	NW /?CCL54
	CALL	WT?,NW,128
	ZERO?	STACK \?CND12
?CCL54:	ZERO?	ANDFLG \?CCL59
	EQUAL?	NW,W?BUT,W?EXCEPT /?CCL59
	EQUAL?	NW,W?AND,W?COMMA /?CCL59
	ADD	NUM,1 >?TMP1
	ADD	PTR,2
	MUL	STACK,2
	ADD	P-LEXV,STACK
	PUT	P-ITBL,?TMP1,STACK
	RETURN	PTR
?CCL59:	SET	'ANDFLG,FALSE-VALUE
	JUMP	?CND12
?CCL47:	CALL	WT?,WRD,32
	ZERO?	STACK \?CND12
	CALL	WT?,WRD,4
	ZERO?	STACK \?CND12
	ZERO?	ANDFLG /?CCL67
	GET	P-ITBL,P-VERB
	ZERO?	STACK \?CCL67
	SUB	PTR,4 >PTR
	ADD	PTR,2
	CALL	CHANGE-LEXV,STACK,W?THEN
	ADD	P-LEN,2 >P-LEN
?CND12:	SET	'LW,WRD
	SET	'FIRST??,FALSE-VALUE
	ADD	PTR,P-LEXELEN >PTR
	JUMP	?PRG8
?CCL67:	CALL	WT?,WRD,8
	ZERO?	STACK \?CND12
	CALL	CANT-USE,PTR
	RFALSE	
?CCL16:	CALL	UNKNOWN-WORD,PTR
	RFALSE	


	.FUNCT	THIS-IS-IT,OBJ
	EQUAL?	OBJ,FALSE-VALUE,PROTAGONIST,NOT-HERE-OBJECT /TRUE
	EQUAL?	OBJ,INTDIR /TRUE
	EQUAL?	PRSA,V?WALK,V?WALK-TO \?CCL7
	EQUAL?	OBJ,PRSO /TRUE
?CCL7:	SET	'P-IT-OBJECT,OBJ
	RTRUE	


	.FUNCT	FAKE-ORPHAN,TMP,?TMP1
	CALL	ORPHAN,P-SYNTAX,FALSE-VALUE
	CALL	BE-SPECIFIC
	GET	P-OTBL,P-VERBN >TMP
	ZERO?	TMP \?CCL3
	PRINTI	"tell"
	JUMP	?CND1
?CCL3:	GETB	P-VTBL,2
	ZERO?	STACK \?CCL7
	GET	TMP,0
	PRINTB	STACK
	JUMP	?CND1
?CCL7:	GETB	TMP,2 >?TMP1
	GETB	TMP,3
	CALL	WORD-PRINT,?TMP1,STACK
	PUTB	P-VTBL,2,0
?CND1:	SET	'P-OFLAG,TRUE-VALUE
	SET	'P-WON,FALSE-VALUE
	PRINTR	"?)"


	.FUNCT	SEE-VERB?
	EQUAL?	PRSA,V?LOOK,V?EXAMINE,V?LOOK-INSIDE /TRUE
	EQUAL?	PRSA,V?SEARCH,V?FIND,V?LOOK-ON /TRUE
	EQUAL?	PRSA,V?LOOK-UNDER,V?LOOK-BEHIND,V?READ /TRUE
	EQUAL?	PRSA,V?LOOK-THRU,V?LOOK-DOWN,V?COUNT /TRUE
	RFALSE	


	.FUNCT	PERFORM,A,O=0,I=0,V,OA,OO,OI
	SET	'OA,PRSA
	SET	'OO,PRSO
	SET	'OI,PRSI
	SET	'PRSA,A
	ZERO?	LIT \?CCL3
	CALL	SEE-VERB?
	ZERO?	STACK /?CCL3
	CALL	TOO-DARK
	RETURN	2
?CCL3:	EQUAL?	A,V?WALK /?CND1
	EQUAL?	IT,I,O \?CND9
	CALL	ACCESSIBLE?,P-IT-OBJECT
	ZERO?	STACK \?CND9
	ZERO?	I \?CCL15
	CALL	FAKE-ORPHAN
	RETURN	2
?CCL15:	CALL	CANT-SEE-ANY,P-IT-OBJECT
	RETURN	2
?CND9:	EQUAL?	THEM,I,O \?CND18
	CALL	VISIBLE?,P-THEM-OBJECT
	ZERO?	STACK /?CCL22
	EQUAL?	THEM,O \?CND23
	SET	'O,P-THEM-OBJECT
?CND23:	EQUAL?	THEM,I \?CND18
	SET	'I,P-THEM-OBJECT
?CND18:	EQUAL?	HER,I,O \?CND32
	CALL	VISIBLE?,P-HER-OBJECT
	ZERO?	STACK /?CCL36
	EQUAL?	HER,O \?CND37
	SET	'O,P-HER-OBJECT
?CND37:	EQUAL?	HER,I \?CND32
	SET	'I,P-HER-OBJECT
?CND32:	EQUAL?	HIM,I,O \?CND46
	CALL	VISIBLE?,P-HIM-OBJECT
	ZERO?	STACK /?CCL50
	EQUAL?	HIM,O \?CND51
	SET	'O,P-HIM-OBJECT
?CND51:	EQUAL?	HIM,I \?CND46
	SET	'I,P-HIM-OBJECT
?CND46:	EQUAL?	O,IT \?CND60
	SET	'O,P-IT-OBJECT
?CND60:	EQUAL?	I,IT \?CND1
	SET	'I,P-IT-OBJECT
?CND1:	SET	'PRSI,I
	SET	'PRSO,O
	SET	'V,FALSE-VALUE
	EQUAL?	A,V?WALK /?CND64
	EQUAL?	NOT-HERE-OBJECT,PRSO,PRSI \?CND64
	CALL	D-APPLY,STR?1,NOT-HERE-OBJECT-F >V
	ZERO?	V /?CND64
	SET	'P-WON,FALSE-VALUE
?CND64:	CALL	THIS-IS-IT,PRSI
	CALL	THIS-IS-IT,PRSO
	SET	'O,PRSO
	SET	'I,PRSI
	ZERO?	V \?CND70
	GETP	WINNER,P?ACTION
	CALL	D-APPLY,STR?2,STACK,M-WINNER >V
?CND70:	ZERO?	V \?CND72
	LOC	WINNER
	GETP	STACK,P?ACTION
	CALL	D-APPLY,STR?3,STACK,M-BEG >V
?CND72:	ZERO?	V \?CND74
	GET	PREACTIONS,A
	CALL	D-APPLY,STR?4,STACK >V
?CND74:	SET	'NOW-PRSI,TRUE-VALUE
	ZERO?	V \?CND76
	ZERO?	I /?CND76
	EQUAL?	A,V?WALK /?CND76
	LOC	I
	ZERO?	STACK /?CND76
	LOC	I
	GETP	STACK,P?CONTFCN >V
	ZERO?	V /?CND76
	CALL	V,M-CONT >V
?CND76:	ZERO?	V \?CND84
	ZERO?	I /?CND84
	GETP	I,P?ACTION
	CALL	D-APPLY,STR?5,STACK >V
?CND84:	SET	'NOW-PRSI,FALSE-VALUE
	ZERO?	V \?CND88
	ZERO?	O /?CND88
	EQUAL?	A,V?WALK /?CND88
	LOC	O
	ZERO?	STACK /?CND88
	LOC	O
	GETP	STACK,P?CONTFCN >V
	ZERO?	V /?CND88
	CALL	V,M-CONT >V
?CND88:	ZERO?	V \?CND96
	ZERO?	O /?CND96
	EQUAL?	A,V?WALK /?CND96
	GETP	O,P?ACTION
	CALL	D-APPLY,STR?6,STACK >V
	ZERO?	V /?CND96
	CALL	THIS-IS-IT,O
?CND96:	ZERO?	V \?CND103
	GET	ACTIONS,A
	CALL	D-APPLY,FALSE-VALUE,STACK >V
?CND103:	EQUAL?	V,M-FATAL /?CND105
	CALL	GAME-VERB?
	ZERO?	STACK \?CND105
	LOC	WINNER
	GETP	STACK,P?ACTION
	CALL	D-APPLY,STR?7,STACK,M-END >V
?CND105:	SET	'PRSA,OA
	SET	'PRSO,OO
	SET	'PRSI,OI
	RETURN	V
?CCL22:	ZERO?	I \?CCL29
	CALL	FAKE-ORPHAN
	RETURN	2
?CCL29:	CALL	CANT-SEE-ANY,P-THEM-OBJECT
	RETURN	2
?CCL36:	ZERO?	I \?CCL43
	CALL	FAKE-ORPHAN
	RETURN	2
?CCL43:	CALL	CANT-SEE-ANY,P-HER-OBJECT
	RETURN	2
?CCL50:	ZERO?	I \?CCL57
	CALL	FAKE-ORPHAN
	RETURN	2
?CCL57:	CALL	CANT-SEE-ANY,P-HIM-OBJECT
	RETURN	2


	.FUNCT	D-APPLY,STR,FCN,FOO=0,RES
	ZERO?	FCN /FALSE
	EQUAL?	STR,STR?8 \?CND4
	SET	FOO,M-CONT
?CND4:	ZERO?	FOO /?CCL8
	CALL	FCN,FOO >RES
	RETURN	RES
?CCL8:	CALL	FCN >RES
	RETURN	RES


	.FUNCT	BUZZER-WORD?,WORD
	CALL	QUESTION-WORD?,WORD
	ZERO?	STACK \TRUE
	CALL	NUMBER-WORD?,WORD
	ZERO?	STACK \TRUE
	CALL	NAUGHTY-WORD?,WORD
	ZERO?	STACK /FALSE
	RTRUE	


	.FUNCT	QUESTION-WORD?,WORD
	EQUAL?	WORD,W?WHERE \?CCL3
	CALL	TO-DO-THING-USE,STR?9,STR?10
	RTRUE	
?CCL3:	EQUAL?	WORD,W?WHAT,W?WHAT'S,W?WHO /?CTR4
	EQUAL?	WORD,W?WHO'S,W?WHY,W?HOW /?CTR4
	EQUAL?	WORD,W?WHEN,W?WHEN'S,W?AM /?CTR4
	EQUAL?	WORD,W?WOULD,W?COULD,W?SHOULD \?CCL5
?CTR4:	CALL	TO-DO-THING-USE,STR?11,STR?12
	RTRUE	
?CCL5:	EQUAL?	WORD,W?THAT'S,W?IT'S,W?I'M /?PRG20
	EQUAL?	WORD,W?IS,W?DID,W?ARE /?PRG20
	EQUAL?	WORD,W?DO,W?HAVE,W?ANY /?PRG20
	EQUAL?	WORD,W?WILL,W?WAS,W?WERE /?PRG20
	EQUAL?	WORD,W?I'LL,W?WHICH,W?WE'RE /?PRG20
	EQUAL?	WORD,W?I'VE,W?WON'T,W?HAS /?PRG20
	EQUAL?	WORD,W?YOU'RE,W?HE'S,W?SHE'S /?PRG20
	EQUAL?	WORD,W?THEY'RE,W?SHALL \FALSE
?PRG20:	PRINTI	"(Please use commands"
	IGRTR?	'QUESTION-WORD-COUNT,4 \?PRG27
	SET	'QUESTION-WORD-COUNT,0
	PRINTI	"! Your commands tell the computer what you want to do in the story. Here are examples of commands:

   TURN ON THE LAMP
   LOOK INSIDE THE HOLE

Now you can try again"
	JUMP	?PRG29
?PRG27:	PRINTI	", not statements or questions"
?PRG29:	PRINTR	".)"


	.FUNCT	NUMBER-WORD?,WRD
	EQUAL?	WRD,W?ONE /?PRG15
	EQUAL?	WRD,W?TWO,W?THREE,W?FOUR /?PRG15
	EQUAL?	WRD,W?FIVE,W?SIX,W?SEVEN /?PRG15
	EQUAL?	WRD,W?EIGHT,W?NINE,W?TEN /?PRG15
	EQUAL?	WRD,W?ELEVEN,W?TWELVE,W?THIRTE /?PRG15
	EQUAL?	WRD,W?FOURTE,W?FIFTEE,W?SIXTEE /?PRG15
	EQUAL?	WRD,W?SEVENT,W?EIGHTE,W?NINETE /?PRG15
	EQUAL?	WRD,W?TWENTY,W?THIRTY,W?FORTY /?PRG15
	EQUAL?	WRD,W?FIFTY,W?SIXTY,W?EIGHTY /?PRG15
	EQUAL?	WRD,W?NINETY,W?HUNDRE,W?THOUSA /?PRG15
	EQUAL?	WRD,W?MILLIO,W?BILLIO,W?ZERO \FALSE
?PRG15:	PRINTR	"(Use numerals for numbers, for example ""10."")"


	.FUNCT	NAUGHTY-WORD?,WORD
	EQUAL?	WORD,W?CURSE,W?GODDAMNED,W?CUSS /?PRG11
	EQUAL?	WORD,W?DAMN,W?SHIT,W?FUCK /?PRG11
	EQUAL?	WORD,W?SHITHEAD,W?PISS,W?SUCK /?PRG11
	EQUAL?	WORD,W?BASTARD,W?SCREW,W?FUCKING /?PRG11
	EQUAL?	WORD,W?DAMNED,W?PEE,W?COCKSUCKER /?PRG11
	EQUAL?	WORD,W?FUCKED,W?CUNT,W?ASSHOLE /?PRG11
	EQUAL?	WORD,W?BITCH \FALSE
?PRG11:	PRINTC	40
	CALL	PICK-ONE,OFFENDED
	PRINT	STACK
	PRINTR	".)"


	.FUNCT	VERB-DIR-ONLY?,WRD,?TMP1
	CALL	WT?,WRD,128
	ZERO?	STACK \FALSE
	CALL	WT?,WRD,32
	ZERO?	STACK \FALSE
	CALL	WT?,WRD,16 >?TMP1
	ZERO?	?TMP1 /?PRD7
	RETURN	?TMP1
?PRD7:	CALL	WT?,WRD,64
	RSTACK	


	.FUNCT	STUFF,DEST,SRC,MAX=29,PTR=P-LEXSTART,CTR=1,BPTR
	GETB	SRC,0
	PUTB	DEST,0,STACK
	GETB	SRC,1
	PUTB	DEST,1,STACK
?PRG1:	GET	SRC,PTR
	PUT	DEST,PTR,STACK
	MUL	PTR,2
	ADD	STACK,2 >BPTR
	GETB	SRC,BPTR
	PUTB	DEST,BPTR,STACK
	MUL	PTR,2
	ADD	STACK,3 >BPTR
	GETB	SRC,BPTR
	PUTB	DEST,BPTR,STACK
	ADD	PTR,P-LEXELEN >PTR
	IGRTR?	'CTR,MAX \?PRG1
	RTRUE	


	.FUNCT	INBUF-STUFF,DEST,SRC,CNT=-1
?PRG1:	IGRTR?	'CNT,59 /TRUE
	GETB	SRC,CNT
	PUTB	DEST,CNT,STACK
	JUMP	?PRG1


	.FUNCT	INBUF-ADD,LEN,BEG,SLOT,DBEG,CTR=0,TMP,?TMP1
	GET	OOPS-TABLE,O-END >TMP
	ZERO?	TMP /?CCL3
	SET	'DBEG,TMP
	JUMP	?CND1
?CCL3:	GET	OOPS-TABLE,O-LENGTH >TMP
	GETB	AGAIN-LEXV,TMP >?TMP1
	ADD	TMP,1
	GETB	AGAIN-LEXV,STACK
	ADD	?TMP1,STACK >DBEG
?CND1:	ADD	DBEG,LEN
	PUT	OOPS-TABLE,O-END,STACK
?PRG4:	ADD	DBEG,CTR >?TMP1
	ADD	BEG,CTR
	GETB	P-INBUF,STACK
	PUTB	OOPS-INBUF,?TMP1,STACK
	INC	'CTR
	EQUAL?	CTR,LEN \?PRG4
	PUTB	AGAIN-LEXV,SLOT,DBEG
	SUB	SLOT,1
	PUTB	AGAIN-LEXV,STACK,LEN
	RTRUE	


	.FUNCT	NUMBER?,PTR,CNT,BPTR,CHR,SUM=0,TIM=0,DOLLAR=0,?TMP1
	MUL	PTR,2
	ADD	P-LEXV,STACK
	GETB	STACK,2 >CNT
	MUL	PTR,2
	ADD	P-LEXV,STACK
	GETB	STACK,3 >BPTR
?PRG1:	DLESS?	'CNT,0 /?REP2
	GETB	P-INBUF,BPTR >CHR
	EQUAL?	CHR,58 \?CCL8
	SET	'TIM,SUM
	SET	'SUM,0
	JUMP	?CND6
?CCL8:	GRTR?	SUM,9999 /FALSE
	EQUAL?	CHR,CURRENCY-SYMBOL \?CCL12
	SET	'DOLLAR,TRUE-VALUE
	JUMP	?CND6
?CCL12:	GRTR?	CHR,57 /FALSE
	LESS?	CHR,48 /FALSE
	MUL	SUM,10 >?TMP1
	SUB	CHR,48
	ADD	?TMP1,STACK >SUM
?CND6:	INC	'BPTR
	JUMP	?PRG1
?REP2:	CALL	CHANGE-LEXV,PTR,W?INTNUM
	GRTR?	SUM,9999 /FALSE
	ZERO?	TIM /?CND17
	GRTR?	TIM,23 /FALSE
	MUL	TIM,60
	ADD	SUM,STACK >SUM
?CND17:	SET	'P-DOLLAR-FLAG,DOLLAR
	ZERO?	DOLLAR /?CCL25
	GRTR?	SUM,0 \?CCL25
	SET	'P-AMOUNT,SUM
	RETURN	W?MONEY
?CCL25:	SET	'P-NUMBER,SUM
	SET	'P-DOLLAR-FLAG,FALSE-VALUE
	RETURN	W?INTNUM


	.FUNCT	ORPHAN-MERGE,CNT=-1,TEMP,VERB,BEG,END,ADJ=0,WRD,?TMP1
	SET	'P-OFLAG,FALSE-VALUE
	GET	P-ITBL,P-VERBN
	GET	STACK,0 >WRD
	CALL	WT?,WRD,64,1 >?TMP1
	GET	P-OTBL,P-VERB
	EQUAL?	?TMP1,STACK /?CTR2
	CALL	WT?,WRD,32
	ZERO?	STACK /?CCL3
?CTR2:	SET	'ADJ,TRUE-VALUE
	JUMP	?CND1
?CCL3:	CALL	WT?,WRD,128
	ZERO?	STACK /?CND1
	ZERO?	P-NCN \?CND1
	PUT	P-ITBL,P-VERB,0
	PUT	P-ITBL,P-VERBN,0
	ADD	P-LEXV,2
	PUT	P-ITBL,P-NC1,STACK
	ADD	P-LEXV,6
	PUT	P-ITBL,P-NC1L,STACK
	SET	'P-NCN,1
?CND1:	GET	P-ITBL,P-VERB >VERB
	ZERO?	VERB /?CCL11
	ZERO?	ADJ \?CCL11
	GET	P-OTBL,P-VERB
	EQUAL?	VERB,STACK \FALSE
?CCL11:	EQUAL?	P-NCN,2 /FALSE
	GET	P-OTBL,P-NC1
	EQUAL?	STACK,1 \?CCL18
	GET	P-ITBL,P-PREP1 >TEMP
	GET	P-OTBL,P-PREP1
	EQUAL?	TEMP,STACK /?CTR20
	ZERO?	TEMP \FALSE
?CTR20:	ZERO?	ADJ /?CCL26
	ADD	P-LEXV,2
	PUT	P-OTBL,P-NC1,STACK
	GET	P-ITBL,P-NC1L
	ZERO?	STACK \?CND27
	ADD	P-LEXV,6
	PUT	P-ITBL,P-NC1L,STACK
?CND27:	ZERO?	P-NCN \?CND24
	SET	'P-NCN,1
	JUMP	?CND24
?CCL26:	GET	P-ITBL,P-NC1
	PUT	P-OTBL,P-NC1,STACK
?CND24:	GET	P-ITBL,P-NC1L
	PUT	P-OTBL,P-NC1L,STACK
	JUMP	?CND9
?CCL18:	GET	P-OTBL,P-NC2
	EQUAL?	STACK,1 \?CCL32
	GET	P-ITBL,P-PREP1 >TEMP
	GET	P-OTBL,P-PREP2
	EQUAL?	TEMP,STACK /?CTR34
	ZERO?	TEMP \FALSE
?CTR34:	ZERO?	ADJ /?CND38
	ADD	P-LEXV,2
	PUT	P-ITBL,P-NC1,STACK
	GET	P-ITBL,P-NC1L
	ZERO?	STACK \?CND38
	ADD	P-LEXV,6
	PUT	P-ITBL,P-NC1L,STACK
?CND38:	GET	P-ITBL,P-NC1
	PUT	P-OTBL,P-NC2,STACK
	GET	P-ITBL,P-NC1L
	PUT	P-OTBL,P-NC2L,STACK
	SET	'P-NCN,2
	JUMP	?CND9
?CCL32:	ZERO?	P-ACLAUSE /?CND9
	EQUAL?	P-NCN,1 /?CCL45
	ZERO?	ADJ \?CCL45
	SET	'P-ACLAUSE,FALSE-VALUE
	RFALSE	
?CCL45:	GET	P-ITBL,P-NC1 >BEG
	ZERO?	ADJ /?CND48
	ADD	P-LEXV,2 >BEG
	SET	'ADJ,FALSE-VALUE
?CND48:	GET	P-ITBL,P-NC1L >END
?PRG50:	GET	BEG,0 >WRD
	EQUAL?	BEG,END \?CCL54
	ZERO?	ADJ /?CCL57
	CALL	ACLAUSE-WIN,ADJ
	JUMP	?CND9
?CCL57:	SET	'P-ACLAUSE,FALSE-VALUE
	RFALSE	
?CCL54:	ZERO?	ADJ \?CCL59
	GETB	WRD,P-PSOFF
	BTST	STACK,32 /?CTR58
	EQUAL?	WRD,W?ALL,W?EVERYTHING \?CCL59
?CTR58:	SET	'ADJ,WRD
?CND52:	ADD	BEG,P-WORDLEN >BEG
	ZERO?	END \?PRG50
	SET	'END,BEG
	SET	'P-NCN,1
	SUB	BEG,4
	PUT	P-ITBL,P-NC1,STACK
	PUT	P-ITBL,P-NC1L,BEG
	JUMP	?PRG50
?CCL59:	GETB	WRD,P-PSOFF
	BTST	STACK,128 \?CND52
	EQUAL?	WRD,P-ANAM \?CCL67
	CALL	ACLAUSE-WIN,ADJ
	JUMP	?CND9
?CCL67:	CALL	NCLAUSE-WIN
?CND9:	GET	P-OVTBL,0
	PUT	P-VTBL,0,STACK
	GETB	P-OVTBL,2
	PUTB	P-VTBL,2,STACK
	GETB	P-OVTBL,3
	PUTB	P-VTBL,3,STACK
	PUT	P-OTBL,P-VERBN,P-VTBL
	PUTB	P-VTBL,2,0
?PRG70:	IGRTR?	'CNT,P-ITBLLEN \?CCL74
	SET	'P-MERGED,TRUE-VALUE
	RTRUE	
?CCL74:	GET	P-OTBL,CNT
	PUT	P-ITBL,CNT,STACK
	JUMP	?PRG70


	.FUNCT	ACLAUSE-WIN,ADJ,X
	GET	P-OTBL,P-VERB
	PUT	P-ITBL,P-VERB,STACK
	ADD	P-ACLAUSE,1 >X
	PUT	P-CCTBL,CC-SBPTR,P-ACLAUSE
	PUT	P-CCTBL,CC-SEPTR,X
	PUT	P-CCTBL,CC-DBPTR,P-ACLAUSE
	PUT	P-CCTBL,CC-DEPTR,X
	CALL	CLAUSE-COPY,P-OTBL,P-OTBL,ADJ
	GET	P-OTBL,P-NC2
	ZERO?	STACK /?PEN3
	SET	'P-NCN,2
?PEN3:	SET	'P-ACLAUSE,FALSE-VALUE
	RTRUE	


	.FUNCT	NCLAUSE-WIN
	PUT	P-CCTBL,CC-SBPTR,P-NC1
	PUT	P-CCTBL,CC-SEPTR,P-NC1L
	PUT	P-CCTBL,CC-DBPTR,P-ACLAUSE
	ADD	P-ACLAUSE,1
	PUT	P-CCTBL,CC-DEPTR,STACK
	CALL	CLAUSE-COPY,P-ITBL,P-OTBL
	GET	P-OTBL,P-NC2
	ZERO?	STACK /?PEN3
	SET	'P-NCN,2
?PEN3:	SET	'P-ACLAUSE,FALSE-VALUE
	RTRUE	


	.FUNCT	WORD-PRINT,CNT,BUF
?PRG1:	DLESS?	'CNT,0 /TRUE
	GETB	P-INBUF,BUF
	PRINTC	STACK
	INC	'BUF
	JUMP	?PRG1


	.FUNCT	UNKNOWN-WORD,PTR,BUF,MSG,?TMP1
	PUT	OOPS-TABLE,O-PTR,PTR
	CALL	PICK-ONE,UNKNOWN-MSGS >MSG
	PRINTC	40
	GET	MSG,0
	PRINT	STACK
	MUL	PTR,2 >BUF
	ADD	P-LEXV,BUF
	GETB	STACK,2 >?TMP1
	ADD	P-LEXV,BUF
	GETB	STACK,3
	CALL	WORD-PRINT,?TMP1,STACK
	SET	'QUOTE-FLAG,FALSE-VALUE
	SET	'P-OFLAG,FALSE-VALUE
	GET	MSG,1
	PRINT	STACK
	PRINTR	")"


	.FUNCT	SYNTAX-CHECK,SYN,LEN,NUM,OBJ,DRIVE1=0,DRIVE2=0,PREP,VERB,?TMP2,?TMP1
	GET	P-ITBL,P-VERB >VERB
	ZERO?	VERB \?CND1
	CALL	NOT-IN-SENTENCE,STR?23
	RFALSE	
?CND1:	SUB	255,VERB
	GET	VERBS,STACK >SYN
	GETB	SYN,0 >LEN
	INC	'SYN
?PRG3:	GETB	SYN,P-SBITS
	BAND	STACK,P-SONUMS >NUM
	GRTR?	P-NCN,NUM /?CND5
	LESS?	NUM,1 /?CCL9
	ZERO?	P-NCN \?CCL9
	GET	P-ITBL,P-PREP1 >PREP
	ZERO?	PREP /?CTR8
	GETB	SYN,P-SPREP1
	EQUAL?	PREP,STACK \?CCL9
?CTR8:	SET	'DRIVE1,SYN
	JUMP	?CND5
?CCL9:	GETB	SYN,P-SPREP1 >?TMP1
	GET	P-ITBL,P-PREP1
	EQUAL?	?TMP1,STACK \?CND5
	EQUAL?	NUM,2 \?CCL18
	EQUAL?	P-NCN,1 \?CCL18
	SET	'DRIVE2,SYN
?CND5:	DLESS?	'LEN,1 \?CCL24
	ZERO?	DRIVE1 \?REP4
	ZERO?	DRIVE2 \?REP4
	CALL	DONT-UNDERSTAND
	RFALSE	
?CCL18:	GETB	SYN,P-SPREP2 >?TMP1
	GET	P-ITBL,P-PREP2
	EQUAL?	?TMP1,STACK \?CND5
	CALL	SYNTAX-FOUND,SYN
	RTRUE	
?CCL24:	ADD	SYN,P-SYNLEN >SYN
	JUMP	?PRG3
?REP4:	ZERO?	DRIVE1 /?CCL32
	GETB	DRIVE1,P-SFWIM1 >?TMP2
	GETB	DRIVE1,P-SLOC1 >?TMP1
	GETB	DRIVE1,P-SPREP1
	CALL	GWIM,?TMP2,?TMP1,STACK >OBJ
	ZERO?	OBJ /?CCL32
	PUT	P-PRSO,P-MATCHLEN,1
	PUT	P-PRSO,1,OBJ
	CALL	SYNTAX-FOUND,DRIVE1
	RSTACK	
?CCL32:	ZERO?	DRIVE2 /?CCL36
	GETB	DRIVE2,P-SFWIM2 >?TMP2
	GETB	DRIVE2,P-SLOC2 >?TMP1
	GETB	DRIVE2,P-SPREP2
	CALL	GWIM,?TMP2,?TMP1,STACK >OBJ
	ZERO?	OBJ /?CCL36
	PUT	P-PRSI,P-MATCHLEN,1
	PUT	P-PRSI,1,OBJ
	CALL	SYNTAX-FOUND,DRIVE2
	RSTACK	
?CCL36:	EQUAL?	VERB,ACT?FIND \?CCL40
	PRINTI	"That's your problem!"
	CRLF	
	RFALSE	
?CCL40:	EQUAL?	WINNER,PROTAGONIST \?PRG48
	CALL	ORPHAN,DRIVE1,DRIVE2
	PRINTI	"(Wh"
	JUMP	?CND43
?PRG48:	PRINTI	"(Your command wasn't complete. Next time, type wh"
?CND43:	EQUAL?	VERB,ACT?WALK \?CCL52
	PRINTI	"ere"
	JUMP	?CND50
?CCL52:	ZERO?	DRIVE1 /?PRD58
	GETB	DRIVE1,P-SFWIM1
	EQUAL?	STACK,ACTORBIT /?PRG63
?PRD58:	ZERO?	DRIVE2 /?PRG65
	GETB	DRIVE2,P-SFWIM2
	EQUAL?	STACK,ACTORBIT \?PRG65
?PRG63:	PRINTI	"om"
	JUMP	?CND50
?PRG65:	PRINTI	"at"
?CND50:	EQUAL?	WINNER,PROTAGONIST \?PRG72
	PRINTI	" do you want to "
	JUMP	?CND67
?PRG72:	PRINTI	" you want "
	CALL	ARTICLE,WINNER,TRUE-VALUE
	PRINTD	WINNER
	PRINTI	" to "
?CND67:	CALL	VERB-PRINT
	ZERO?	DRIVE2 /?CND76
	CALL	CLAUSE-PRINT,P-NC1,P-NC1L
?CND76:	SET	'P-END-ON-PREP,FALSE-VALUE
	ZERO?	DRIVE1 /?CCL80
	GETB	DRIVE1,P-SPREP1
	JUMP	?CND78
?CCL80:	GETB	DRIVE2,P-SPREP2
?CND78:	CALL	PREP-PRINT,STACK
	EQUAL?	WINNER,PROTAGONIST \?CCL83
	SET	'P-OFLAG,TRUE-VALUE
	PRINTI	"?)"
	CRLF	
	RFALSE	
?CCL83:	SET	'P-OFLAG,FALSE-VALUE
	PRINTI	".)"
	CRLF	
	RFALSE	


	.FUNCT	VERB-PRINT,TMP,?TMP1
	GET	P-ITBL,P-VERBN >TMP
	ZERO?	TMP \?CCL3
	PRINTI	"tell"
	RTRUE	
?CCL3:	GETB	P-VTBL,2
	ZERO?	STACK \?CCL7
	GET	TMP,0
	PRINTB	STACK
	RTRUE	
?CCL7:	GETB	TMP,2 >?TMP1
	GETB	TMP,3
	CALL	WORD-PRINT,?TMP1,STACK
	PUTB	P-VTBL,2,0
	RTRUE	


	.FUNCT	ORPHAN,D1,D2,CNT=-1
	ZERO?	P-MERGED \?CND1
	PUT	P-OCLAUSE,P-MATCHLEN,0
?CND1:	GET	P-VTBL,0
	PUT	P-OVTBL,0,STACK
	GETB	P-VTBL,2
	PUTB	P-OVTBL,2,STACK
	GETB	P-VTBL,3
	PUTB	P-OVTBL,3,STACK
?PRG3:	IGRTR?	'CNT,P-ITBLLEN /?REP4
	GET	P-ITBL,CNT
	PUT	P-OTBL,CNT,STACK
	JUMP	?PRG3
?REP4:	EQUAL?	P-NCN,2 \?CND8
	PUT	P-CCTBL,CC-SBPTR,P-NC2
	PUT	P-CCTBL,CC-SEPTR,P-NC2L
	PUT	P-CCTBL,CC-DBPTR,P-NC2
	PUT	P-CCTBL,CC-DEPTR,P-NC2L
	CALL	CLAUSE-COPY,P-ITBL,P-OTBL
?CND8:	LESS?	P-NCN,1 /?CND12
	PUT	P-CCTBL,CC-SBPTR,P-NC1
	PUT	P-CCTBL,CC-SEPTR,P-NC1L
	PUT	P-CCTBL,CC-DBPTR,P-NC1
	PUT	P-CCTBL,CC-DEPTR,P-NC1L
	CALL	CLAUSE-COPY,P-ITBL,P-OTBL
?CND12:	ZERO?	D1 /?CCL18
	GETB	D1,P-SPREP1
	PUT	P-OTBL,P-PREP1,STACK
	PUT	P-OTBL,P-NC1,1
	RTRUE	
?CCL18:	ZERO?	D2 /FALSE
	GETB	D2,P-SPREP2
	PUT	P-OTBL,P-PREP2,STACK
	PUT	P-OTBL,P-NC2,1
	RTRUE	


	.FUNCT	CLAUSE-PRINT,BPTR,EPTR,THE?=1,?TMP1
	GET	P-ITBL,BPTR >?TMP1
	GET	P-ITBL,EPTR
	CALL	BUFFER-PRINT,?TMP1,STACK,THE?
	RSTACK	


	.FUNCT	BUFFER-PRINT,BEG,END,CP,NOSP=0,WRD,FIRST??=1,PN=0,?TMP1
?PRG1:	EQUAL?	BEG,END /TRUE
	ZERO?	NOSP /?PRG9
	SET	'NOSP,FALSE-VALUE
	JUMP	?CND6
?PRG9:	PRINTC	32
?CND6:	GET	BEG,0 >WRD
	EQUAL?	WRD,W?HIM \?PRD14
	CALL	VISIBLE?,P-HIM-OBJECT
	ZERO?	STACK /?CCL12
?PRD14:	EQUAL?	WRD,W?HER \?PRD17
	CALL	VISIBLE?,P-HER-OBJECT
	ZERO?	STACK /?CCL12
?PRD17:	EQUAL?	WRD,W?THEM \?CND11
	CALL	VISIBLE?,P-THEM-OBJECT
	ZERO?	STACK \?CND11
?CCL12:	SET	'PN,TRUE-VALUE
?CND11:	EQUAL?	WRD,W?PERIOD \?CCL24
	SET	'NOSP,TRUE-VALUE
	JUMP	?CND3
?CCL24:	CALL	WT?,WRD,4
	ZERO?	STACK \?PRD28
	CALL	WT?,WRD,8
	ZERO?	STACK /?CCL26
?PRD28:	CALL	WT?,WRD,32
	ZERO?	STACK \?CCL26
	CALL	WT?,WRD,128
	ZERO?	STACK \?CCL26
	SET	'NOSP,TRUE-VALUE
	JUMP	?CND3
?CCL26:	EQUAL?	WRD,W?ME \?CCL33
	PRINTD	PROTAGONIST
	SET	'PN,TRUE-VALUE
	JUMP	?CND3
?CCL33:	CALL	NAME?,WRD
	ZERO?	STACK /?CCL35
	CALL	CAPITALIZE,BEG
	SET	'PN,TRUE-VALUE
	JUMP	?CND3
?CCL35:	ZERO?	FIRST?? /?CND36
	ZERO?	PN \?CND36
	ZERO?	CP /?CND36
	PRINTI	"the "
?CND36:	ZERO?	P-OFLAG \?CTR44
	ZERO?	P-MERGED /?CCL45
?CTR44:	PRINTB	WRD
	JUMP	?CND43
?CCL45:	EQUAL?	WRD,W?IT \?CCL49
	CALL	VISIBLE?,P-IT-OBJECT
	ZERO?	STACK /?CCL49
	PRINTD	P-IT-OBJECT
	JUMP	?CND43
?CCL49:	EQUAL?	WRD,W?HER \?CCL53
	ZERO?	PN \?CCL53
	PRINTD	P-HER-OBJECT
	JUMP	?CND43
?CCL53:	EQUAL?	WRD,W?THEM \?CCL57
	ZERO?	PN \?CCL57
	PRINTD	P-THEM-OBJECT
	JUMP	?CND43
?CCL57:	EQUAL?	WRD,W?HIM \?CCL61
	ZERO?	PN \?CCL61
	PRINTD	P-HIM-OBJECT
	JUMP	?CND43
?CCL61:	GETB	BEG,2 >?TMP1
	GETB	BEG,3
	CALL	WORD-PRINT,?TMP1,STACK
?CND43:	SET	'FIRST??,FALSE-VALUE
?CND3:	ADD	BEG,P-WORDLEN >BEG
	JUMP	?PRG1


	.FUNCT	NAME?,WRD
	EQUAL?	WRD,W?MR,W?MRS,W?MISS /TRUE
	RFALSE	


	.FUNCT	CAPITALIZE,PTR,?TMP1
	ZERO?	P-OFLAG \?CTR2
	ZERO?	P-MERGED /?CCL3
?CTR2:	GET	PTR,0
	PRINTB	STACK
	RTRUE	
?CCL3:	GETB	PTR,3
	GETB	P-INBUF,STACK
	SUB	STACK,32
	PRINTC	STACK
	GETB	PTR,2
	SUB	STACK,1 >?TMP1
	GETB	PTR,3
	ADD	STACK,1
	CALL	WORD-PRINT,?TMP1,STACK
	RSTACK	


	.FUNCT	PREP-PRINT,PREP,SP?=1,WRD
	ZERO?	PREP /FALSE
	ZERO?	P-END-ON-PREP \FALSE
	ZERO?	SP? /?CND6
	PRINTC	32
?CND6:	CALL	PREP-FIND,PREP >WRD
	EQUAL?	WRD,W?THROUGH \?CCL12
	PRINTI	"through"
	JUMP	?CND10
?CCL12:	PRINTB	WRD
?CND10:	GET	P-ITBL,P-VERBN
	GET	STACK,0
	EQUAL?	W?SIT,STACK \?CND15
	EQUAL?	W?DOWN,WRD \?CND15
	PRINTI	" on"
?CND15:	GET	P-ITBL,P-VERBN
	GET	STACK,0
	EQUAL?	W?GET,STACK \TRUE
	EQUAL?	W?OUT,WRD \TRUE
	PRINTI	" of"
	RTRUE	


	.FUNCT	CLAUSE-COPY,SRC,DEST,INSRT=0,BEG,END,?TMP1
	GET	P-CCTBL,CC-SBPTR
	GET	SRC,STACK >BEG
	GET	P-CCTBL,CC-SEPTR
	GET	SRC,STACK >END
	GET	P-CCTBL,CC-DBPTR >?TMP1
	GET	P-OCLAUSE,P-MATCHLEN
	MUL	STACK,P-LEXELEN
	ADD	STACK,2
	ADD	P-OCLAUSE,STACK
	PUT	DEST,?TMP1,STACK
?PRG1:	EQUAL?	BEG,END \?CCL5
	GET	P-CCTBL,CC-DEPTR >?TMP1
	GET	P-OCLAUSE,P-MATCHLEN
	MUL	STACK,P-LEXELEN
	ADD	STACK,2
	ADD	P-OCLAUSE,STACK
	PUT	DEST,?TMP1,STACK
	RTRUE	
?CCL5:	ZERO?	INSRT /?CND6
	GET	BEG,0
	EQUAL?	P-ANAM,STACK \?CND6
	CALL	CLAUSE-ADD,INSRT
?CND6:	GET	BEG,0
	CALL	CLAUSE-ADD,STACK
	ADD	BEG,P-WORDLEN >BEG
	JUMP	?PRG1


	.FUNCT	CLAUSE-ADD,WRD,PTR
	GET	P-OCLAUSE,P-MATCHLEN
	ADD	STACK,2 >PTR
	SUB	PTR,1
	PUT	P-OCLAUSE,STACK,WRD
	PUT	P-OCLAUSE,PTR,0
	PUT	P-OCLAUSE,P-MATCHLEN,PTR
	RTRUE	


	.FUNCT	PREP-FIND,PREP,CNT=0,SIZE
	GET	PREPOSITIONS,0
	MUL	STACK,2 >SIZE
?PRG1:	IGRTR?	'CNT,SIZE /FALSE
	GET	PREPOSITIONS,CNT
	EQUAL?	STACK,PREP \?PRG1
	SUB	CNT,1
	GET	PREPOSITIONS,STACK
	RSTACK	


	.FUNCT	SYNTAX-FOUND,SYN
	SET	'P-SYNTAX,SYN
	GETB	SYN,P-SACTION >PRSA
	RETURN	PRSA


	.FUNCT	GWIM,GBIT,LBIT,PREP,OBJ
	EQUAL?	GBIT,RLANDBIT \?CND1
	RETURN	ROOMS
?CND1:	SET	'P-GWIMBIT,GBIT
	SET	'P-SLOCBITS,LBIT
	PUT	P-MERGE,P-MATCHLEN,0
	CALL	GET-OBJECT,P-MERGE,FALSE-VALUE
	ZERO?	STACK /?CCL5
	SET	'P-GWIMBIT,0
	GET	P-MERGE,P-MATCHLEN
	EQUAL?	STACK,1 \FALSE
	GET	P-MERGE,1 >OBJ
	PRINTC	40
	CALL	PREP-PRINT,PREP,FALSE-VALUE
	ZERO?	STACK /?PRG15
	PRINTC	32
	CALL	ARTICLE,OBJ,TRUE-VALUE
?PRG15:	PRINTD	OBJ
	PRINTC	41
	CRLF	
	RETURN	OBJ
?CCL5:	SET	'P-GWIMBIT,0
	RFALSE	


	.FUNCT	SNARF-OBJECTS,PTR
	GET	P-ITBL,P-NC1 >PTR
	ZERO?	PTR /?CND1
	GETB	P-SYNTAX,P-SLOC1 >P-SLOCBITS
	GET	P-ITBL,P-NC1L
	CALL	SNARFEM,PTR,STACK,P-PRSO
	ZERO?	STACK /FALSE
	GET	P-BUTS,P-MATCHLEN
	ZERO?	STACK /?CND1
	CALL	BUT-MERGE,P-PRSO >P-PRSO
?CND1:	GET	P-ITBL,P-NC2 >PTR
	ZERO?	PTR /TRUE
	GETB	P-SYNTAX,P-SLOC2 >P-SLOCBITS
	GET	P-ITBL,P-NC2L
	CALL	SNARFEM,PTR,STACK,P-PRSI
	ZERO?	STACK /FALSE
	GET	P-BUTS,P-MATCHLEN
	ZERO?	STACK /TRUE
	GET	P-PRSI,P-MATCHLEN
	EQUAL?	STACK,1 \?CCL15
	CALL	BUT-MERGE,P-PRSO >P-PRSO
	RTRUE	
?CCL15:	CALL	BUT-MERGE,P-PRSI >P-PRSI
	RTRUE	


	.FUNCT	BUT-MERGE,TBL,LEN,BUTLEN,CNT=1,MATCHES=0,OBJ,NTBL
	GET	TBL,P-MATCHLEN >LEN
	PUT	P-MERGE,P-MATCHLEN,0
?PRG1:	DLESS?	'LEN,0 /?REP2
	GET	TBL,CNT >OBJ
	CALL	ZMEMQ,OBJ,P-BUTS
	ZERO?	STACK \?CND3
	ADD	MATCHES,1
	PUT	P-MERGE,STACK,OBJ
	INC	'MATCHES
?CND3:	INC	'CNT
	JUMP	?PRG1
?REP2:	PUT	P-MERGE,P-MATCHLEN,MATCHES
	SET	'NTBL,P-MERGE
	SET	'P-MERGE,TBL
	RETURN	NTBL


	.FUNCT	SNARFEM,PTR,EPTR,TBL,BUT=0,LEN,WV,WRD,NW,WAS-ALL?=0,ONEOBJ
	SET	'P-AND,FALSE-VALUE
	EQUAL?	P-GETFLAGS,P-ALL \?CND1
	SET	'WAS-ALL?,TRUE-VALUE
?CND1:	SET	'P-GETFLAGS,0
	PUT	P-BUTS,P-MATCHLEN,0
	PUT	TBL,P-MATCHLEN,0
	GET	PTR,0 >WRD
?PRG3:	EQUAL?	PTR,EPTR \?CCL7
	ZERO?	BUT /?PRD10
	PUSH	BUT
	JUMP	?PEN8
?PRD10:	PUSH	TBL
?PEN8:	CALL	GET-OBJECT,STACK >WV
	ZERO?	WAS-ALL? \?CCL12
	RETURN	WV
?CCL12:	SET	'P-GETFLAGS,P-ALL
	RETURN	WV
?CCL7:	GET	PTR,P-LEXELEN >NW
	EQUAL?	WRD,W?ALL,W?BOTH,W?EVERYTHING \?CCL15
	SET	'P-GETFLAGS,P-ALL
	EQUAL?	NW,W?OF \?CND5
	ADD	PTR,P-WORDLEN >PTR
	JUMP	?CND5
?CCL15:	EQUAL?	WRD,W?BUT,W?EXCEPT \?CCL19
	ZERO?	BUT /?PRD24
	PUSH	BUT
	JUMP	?PEN22
?PRD24:	PUSH	TBL
?PEN22:	CALL	GET-OBJECT,STACK
	ZERO?	STACK /FALSE
	SET	'BUT,P-BUTS
	PUT	BUT,P-MATCHLEN,0
	JUMP	?CND5
?CCL19:	CALL	BUZZER-WORD?,WRD
	ZERO?	STACK \FALSE
	EQUAL?	WRD,W?A \?CCL28
	ZERO?	P-ADJ \?CCL31
	SET	'P-GETFLAGS,P-ONE
	EQUAL?	NW,W?OF \?CND5
	ADD	PTR,P-WORDLEN >PTR
	JUMP	?CND5
?CCL31:	SET	'P-NAM,ONEOBJ
	ZERO?	BUT /?PRD38
	PUSH	BUT
	JUMP	?PEN36
?PRD38:	PUSH	TBL
?PEN36:	CALL	GET-OBJECT,STACK
	ZERO?	STACK /FALSE
	ZERO?	NW \?CND5
	RTRUE	
?CCL28:	EQUAL?	WRD,W?AND,W?COMMA \?CCL42
	EQUAL?	NW,W?AND,W?COMMA /?CCL42
	SET	'P-AND,TRUE-VALUE
	ZERO?	BUT /?PRD49
	PUSH	BUT
	JUMP	?PEN47
?PRD49:	PUSH	TBL
?PEN47:	CALL	GET-OBJECT,STACK
	ZERO?	STACK \?CND5
	RFALSE	
?CCL42:	CALL	WT?,WRD,4
	ZERO?	STACK \?CND5
	EQUAL?	WRD,W?AND,W?COMMA /?CND5
	EQUAL?	WRD,W?OF \?CCL53
	ZERO?	P-GETFLAGS \?CND5
	SET	'P-GETFLAGS,P-INHIBIT
	JUMP	?CND5
?CCL53:	CALL	WT?,WRD,32,2 >WV
	ZERO?	WV /?CCL57
	ZERO?	P-ADJ \?CCL57
	EQUAL?	NW,W?OF /?CCL57
	SET	'P-ADJ,WV
	SET	'P-ADJN,WRD
	JUMP	?CND5
?CCL57:	CALL	WT?,WRD,128
	ZERO?	STACK /?CND5
	SET	'P-NAM,WRD
	SET	'ONEOBJ,WRD
?CND5:	EQUAL?	PTR,EPTR /?PRG3
	ADD	PTR,P-WORDLEN >PTR
	SET	'WRD,NW
	JUMP	?PRG3


	.FUNCT	GET-OBJECT,TBL,VRB=1,BTS,LEN,XBITS,TLEN,GCHECK=0,OLEN=0,OBJ,ADJ,X
	SET	'XBITS,P-SLOCBITS
	GET	TBL,P-MATCHLEN >TLEN
	BTST	P-GETFLAGS,P-INHIBIT /TRUE
	SET	'ADJ,P-ADJN
	ZERO?	P-NAM \?CND3
	ZERO?	P-ADJ /?CND3
	CALL	WT?,P-ADJN,128
	ZERO?	STACK /?CCL9
	SET	'P-NAM,P-ADJN
	SET	'P-ADJ,FALSE-VALUE
?CND3:	ZERO?	P-NAM \?CND11
	ZERO?	P-ADJ \?CND11
	EQUAL?	P-GETFLAGS,P-ALL /?CND11
	ZERO?	P-GWIMBIT \?CND11
	ZERO?	VRB /FALSE
	CALL	NOT-IN-SENTENCE,STR?24
	RFALSE	
?CCL9:	CALL	WT?,P-ADJN,16,3 >BTS
	ZERO?	BTS /?CND3
	SET	'P-ADJ,FALSE-VALUE
	PUT	TBL,P-MATCHLEN,1
	PUT	TBL,1,INTDIR
	SET	'P-DIRECTION,BTS
	RTRUE	
?CND11:	EQUAL?	P-GETFLAGS,P-ALL \?CCL20
	ZERO?	P-SLOCBITS \?CND19
?CCL20:	SET	'P-SLOCBITS,-1
?CND19:	SET	'P-TABLE,TBL
?PRG23:	ZERO?	GCHECK /?CCL27
	CALL	GLOBAL-CHECK,TBL
	JUMP	?CND25
?CCL27:	ZERO?	LIT /?CND28
	FCLEAR	PROTAGONIST,TRANSBIT
	CALL	DO-SL,HERE,SOG,SIR
	FSET	PROTAGONIST,TRANSBIT
?CND28:	CALL	DO-SL,PROTAGONIST,SH,SC
?CND25:	GET	TBL,P-MATCHLEN
	SUB	STACK,TLEN >LEN
	BTST	P-GETFLAGS,P-ALL /?CND30
	BTST	P-GETFLAGS,P-ONE \?CCL33
	ZERO?	LEN /?CCL33
	EQUAL?	LEN,1 /?CND36
	RANDOM	LEN
	GET	TBL,STACK
	PUT	TBL,1,STACK
	PRINTI	"(How about "
	GET	TBL,1
	CALL	ARTICLE,STACK,TRUE-VALUE
	GET	TBL,1
	PRINTD	STACK
	PRINTI	"?)"
	CRLF	
?CND36:	PUT	TBL,P-MATCHLEN,1
?CND30:	ADD	TLEN,1
	GET	TBL,STACK >X
	ZERO?	P-ADJ /?CND82
	ZERO?	P-NAM \?CND82
	ZERO?	X /?CND82
	PRINT	I-ASSUME
	PRINTC	32
	CALL	ARTICLE,X,TRUE-VALUE
	PRINTD	X
	PRINTI	".)"
	CRLF	
?CND82:	SET	'P-SLOCBITS,XBITS
	SET	'P-NAM,FALSE-VALUE
	SET	'P-ADJ,FALSE-VALUE
	RTRUE	
?CCL33:	GRTR?	LEN,1 /?CTR42
	ZERO?	LEN \?CCL43
	EQUAL?	P-SLOCBITS,-1 /?CCL43
?CTR42:	EQUAL?	P-SLOCBITS,-1 \?CCL50
	SET	'P-SLOCBITS,XBITS
	SET	'OLEN,LEN
	GET	TBL,P-MATCHLEN
	SUB	STACK,LEN
	PUT	TBL,P-MATCHLEN,STACK
	JUMP	?PRG23
?CCL50:	ZERO?	LEN \?CND51
	SET	'LEN,OLEN
?CND51:	ZERO?	VRB /?CCL55
	EQUAL?	WINNER,PROTAGONIST /?CCL55
	PRINTI	"(Please try saying that another way.)"
	CRLF	
	RFALSE	
?CCL55:	ZERO?	VRB /?CCL61
	ZERO?	P-NAM /?CCL61
	CALL	WHICH-PRINT,TLEN,LEN,TBL
	EQUAL?	TBL,P-PRSO \?CCL66
	SET	'P-ACLAUSE,P-NC1
	JUMP	?CND64
?CCL66:	SET	'P-ACLAUSE,P-NC2
?CND64:	SET	'P-AADJ,P-ADJ
	SET	'P-ANAM,P-NAM
	CALL	ORPHAN,FALSE-VALUE,FALSE-VALUE
	SET	'P-OFLAG,TRUE-VALUE
	JUMP	?CND53
?CCL61:	ZERO?	VRB /?CND53
	CALL	NOT-IN-SENTENCE,STR?25
?CND53:	SET	'P-NAM,FALSE-VALUE
	SET	'P-ADJ,FALSE-VALUE
	RFALSE	
?CCL43:	ZERO?	LEN \?CCL69
	ZERO?	GCHECK /?CCL69
	ZERO?	VRB /?CND72
	SET	'P-SLOCBITS,XBITS
	ZERO?	LIT \?CTR75
	CALL	SPEAKING-VERB?
	ZERO?	STACK /?CCL76
?CTR75:	CALL	OBJ-FOUND,NOT-HERE-OBJECT,TBL
	SET	'P-XNAM,P-NAM
	SET	'P-NAM,FALSE-VALUE
	SET	'P-XADJ,P-ADJ
	SET	'P-XADJN,P-ADJN
	SET	'P-ADJ,FALSE-VALUE
	SET	'P-ADJN,FALSE-VALUE
	RTRUE	
?CCL76:	CALL	TOO-DARK
?CND72:	SET	'P-NAM,FALSE-VALUE
	SET	'P-ADJ,FALSE-VALUE
	RFALSE	
?CCL69:	ZERO?	LEN \?CND30
	SET	'GCHECK,TRUE-VALUE
	JUMP	?PRG23


	.FUNCT	SPEAKING-VERB?,V=0
	ZERO?	V \?CND1
	SET	'V,PRSA
?CND1:	EQUAL?	V,V?ASK-ABOUT,V?ASK-FOR,V?HELLO /TRUE
	EQUAL?	V,V?TELL,V?QUESTION,V?REPLY /TRUE
	RFALSE	


	.FUNCT	MOBY-FIND,TBL,OBJ=1,LEN,FOO
	SET	'P-NAM,P-XNAM
	SET	'P-ADJ,P-XADJ
	PUT	TBL,P-MATCHLEN,0
	GETB	0,18
	ZERO?	STACK /?CCL3
?PRG4:	CALL	META-LOC,OBJ >FOO
	ZERO?	FOO /?CND6
	CALL	THIS-IT?,OBJ >FOO
	ZERO?	FOO /?CND6
	CALL	OBJ-FOUND,OBJ,TBL >FOO
?CND6:	IGRTR?	'OBJ,DUMMY-OBJECT \?PRG4
	GET	TBL,P-MATCHLEN >LEN
	EQUAL?	LEN,1 \?CND12
	GET	TBL,1 >P-MOBY-FOUND
?CND12:	RETURN	LEN
?CCL3:	SET	'P-MOBY-FLAG,TRUE-VALUE
	SET	'P-TABLE,TBL
	SET	'P-SLOCBITS,-1
	FIRST?	ROOMS >FOO /?PRG14
?PRG14:	ZERO?	FOO /?REP15
	CALL	SEARCH-LIST,FOO,TBL,P-SRCALL
	NEXT?	FOO >FOO /?PRG14
	JUMP	?PRG14
?REP15:	GET	TBL,P-MATCHLEN >LEN
	ZERO?	LEN \?CND19
	CALL	DO-SL,LOCAL-GLOBALS,1,1
?CND19:	GET	TBL,P-MATCHLEN >LEN
	ZERO?	LEN \?CND21
	CALL	DO-SL,ROOMS,1,1
?CND21:	GET	TBL,P-MATCHLEN >LEN
	EQUAL?	LEN,1 \?CND23
	GET	TBL,1 >P-MOBY-FOUND
?CND23:	SET	'P-MOBY-FLAG,FALSE-VALUE
	SET	'P-NAM,FALSE-VALUE
	SET	'P-ADJ,FALSE-VALUE
	RETURN	LEN


	.FUNCT	WHICH-PRINT,TLEN,LEN,TBL,OBJ,RLEN
	SET	'RLEN,LEN
	PRINTI	"Which"
	ZERO?	P-OFLAG \?PRG9
	ZERO?	P-MERGED \?PRG9
	ZERO?	P-AND /?CCL5
?PRG9:	PRINTC	32
	PRINTB	P-NAM
	JUMP	?PRG13
?CCL5:	EQUAL?	TBL,P-PRSO \?CCL12
	CALL	CLAUSE-PRINT,P-NC1,P-NC1L,FALSE-VALUE
	JUMP	?PRG13
?CCL12:	CALL	CLAUSE-PRINT,P-NC2,P-NC2L,FALSE-VALUE
?PRG13:	PRINTI	" do you mean,"
?PRG15:	INC	'TLEN
	GET	TBL,TLEN >OBJ
	PRINTC	32
	CALL	ARTICLE,OBJ,TRUE-VALUE
	PRINTD	OBJ
	EQUAL?	LEN,2 \?CCL23
	EQUAL?	RLEN,2 /?PRG28
	PRINTC	44
?PRG28:	PRINTI	" or"
	JUMP	?CND21
?CCL23:	GRTR?	LEN,2 \?CND21
	PRINTC	44
?CND21:	DLESS?	'LEN,1 \?PRG15
	PRINTR	"?"


	.FUNCT	GLOBAL-CHECK,TBL,LEN,RMG,RMGL,CNT=0,OBJ,OBITS,FOO
	GET	TBL,P-MATCHLEN >LEN
	SET	'OBITS,P-SLOCBITS
	GETPT	HERE,P?GLOBAL >RMG
	ZERO?	RMG /?CND1
	PTSIZE	RMG
	SUB	STACK,1 >RMGL
?PRG3:	GETB	RMG,CNT >OBJ
	FIRST?	OBJ \?CND5
	CALL	SEARCH-LIST,OBJ,TBL,P-SRCALL
?CND5:	CALL	THIS-IT?,OBJ
	ZERO?	STACK /?CND7
	CALL	OBJ-FOUND,OBJ,TBL
?CND7:	IGRTR?	'CNT,RMGL \?PRG3
?CND1:	GETPT	HERE,P?PSEUDO >RMG
	ZERO?	RMG /?CND11
	PTSIZE	RMG
	DIV	STACK,4
	SUB	STACK,1 >RMGL
	SET	'CNT,0
?PRG13:	MUL	CNT,2
	GET	RMG,STACK
	EQUAL?	P-NAM,STACK \?CCL17
	SET	'LAST-PSEUDO-LOC,HERE
	MUL	CNT,2
	ADD	STACK,1
	GET	RMG,STACK
	PUTP	PSEUDO-OBJECT,P?ACTION,STACK
	GETPT	PSEUDO-OBJECT,P?ACTION
	SUB	STACK,5 >FOO
	GET	P-NAM,0
	PUT	FOO,0,STACK
	GET	P-NAM,1
	PUT	FOO,1,STACK
	CALL	OBJ-FOUND,PSEUDO-OBJECT,TBL
	JUMP	?CND11
?CCL17:	IGRTR?	'CNT,RMGL \?PRG13
?CND11:	GET	TBL,P-MATCHLEN
	EQUAL?	STACK,LEN \FALSE
	SET	'P-SLOCBITS,-1
	SET	'P-TABLE,TBL
	CALL	DO-SL,GLOBAL-OBJECTS,1,1
	SET	'P-SLOCBITS,OBITS
	GET	TBL,P-MATCHLEN
	ZERO?	STACK \FALSE
	EQUAL?	PRSA,V?LOOK-INSIDE,V?DUMB-EXAMINE,V?EXAMINE /?CCL27
	EQUAL?	PRSA,V?LEAVE,V?FOLLOW,V?FIND /?CCL27
	EQUAL?	PRSA,V?THROUGH,V?SMELL,V?SEARCH /?CCL27
	EQUAL?	PRSA,V?LOOK-ON,V?WAIT-FOR,V?WALK-TO \FALSE
?CCL27:	CALL	DO-SL,ROOMS,1,1
	RSTACK	


	.FUNCT	DO-SL,OBJ,BIT1,BIT2,BITS
	ADD	BIT1,BIT2
	BTST	P-SLOCBITS,STACK \?CCL3
	CALL	SEARCH-LIST,OBJ,P-TABLE,P-SRCALL
	RSTACK	
?CCL3:	BTST	P-SLOCBITS,BIT1 \?CCL6
	CALL	SEARCH-LIST,OBJ,P-TABLE,P-SRCTOP
	RSTACK	
?CCL6:	BTST	P-SLOCBITS,BIT2 \TRUE
	CALL	SEARCH-LIST,OBJ,P-TABLE,P-SRCBOT
	RSTACK	


	.FUNCT	SEARCH-LIST,OBJ,TBL,LVL
	FIRST?	OBJ >OBJ \FALSE
?PRG4:	EQUAL?	LVL,P-SRCBOT /?CND6
	GETPT	OBJ,P?SYNONYM
	ZERO?	STACK /?CND6
	CALL	THIS-IT?,OBJ
	ZERO?	STACK /?CND6
	CALL	OBJ-FOUND,OBJ,TBL
?CND6:	EQUAL?	LVL,P-SRCTOP \?PRD14
	FSET?	OBJ,SEARCHBIT /?PRD14
	FSET?	OBJ,SURFACEBIT \?CND11
?PRD14:	FIRST?	OBJ \?CND11
	CALL	SEE-INSIDE?,OBJ
	ZERO?	STACK /?CND11
	FSET?	OBJ,SURFACEBIT \?CCL21
	PUSH	P-SRCALL
	JUMP	?CND19
?CCL21:	FSET?	OBJ,SEARCHBIT \?CCL23
	PUSH	P-SRCALL
	JUMP	?CND19
?CCL23:	PUSH	P-SRCTOP
?CND19:	CALL	SEARCH-LIST,OBJ,TBL,STACK
?CND11:	NEXT?	OBJ >OBJ /?PRG4
	RTRUE	


	.FUNCT	THIS-IT?,OBJ,SYNS
	FSET?	OBJ,INVISIBLE /FALSE
	ZERO?	P-NAM /?CCL5
	GETPT	OBJ,P?SYNONYM >SYNS
	ZERO?	SYNS /FALSE
	PTSIZE	SYNS
	DIV	STACK,2
	SUB	STACK,1
	CALL	ZMEMQ,P-NAM,SYNS,STACK
	ZERO?	STACK /FALSE
?CCL5:	ZERO?	P-ADJ /?CCL11
	GETPT	OBJ,P?ADJECTIVE >SYNS
	ZERO?	SYNS /FALSE
	PTSIZE	SYNS
	SUB	STACK,1
	CALL	ZMEMQB,P-ADJ,SYNS,STACK
	ZERO?	STACK /FALSE
?CCL11:	ZERO?	P-GWIMBIT /TRUE
	FSET?	OBJ,P-GWIMBIT /TRUE
	RFALSE	


	.FUNCT	OBJ-FOUND,OBJ,TBL,PTR
	GET	TBL,P-MATCHLEN >PTR
	ADD	PTR,1
	PUT	TBL,STACK,OBJ
	ADD	PTR,1
	PUT	TBL,P-MATCHLEN,STACK
	RTRUE	


	.FUNCT	TAKE-CHECK
	GETB	P-SYNTAX,P-SLOC1
	CALL	ITAKE-CHECK,P-PRSO,STACK
	ZERO?	STACK /FALSE
	GETB	P-SYNTAX,P-SLOC2
	CALL	ITAKE-CHECK,P-PRSI,STACK
	RSTACK	


	.FUNCT	ITAKE-CHECK,TBL,BITS,PTR,OBJ,TAKEN
	GET	TBL,P-MATCHLEN >PTR
	ZERO?	PTR /TRUE
	BTST	BITS,SHAVE /?PRG8
	BTST	BITS,STAKE \TRUE
?PRG8:	DLESS?	'PTR,0 /TRUE
	ADD	PTR,1
	GET	TBL,STACK >OBJ
	EQUAL?	OBJ,IT \?CCL14
	CALL	ACCESSIBLE?,P-IT-OBJECT
	ZERO?	STACK \?CCL17
	CALL	REFERRING
	RFALSE	
?CCL17:	SET	'OBJ,P-IT-OBJECT
	JUMP	?CND12
?CCL14:	EQUAL?	OBJ,HER \?CCL19
	CALL	ACCESSIBLE?,P-HER-OBJECT
	ZERO?	STACK \?CCL22
	CALL	REFERRING
	RFALSE	
?CCL22:	SET	'OBJ,P-HER-OBJECT
	JUMP	?CND12
?CCL19:	EQUAL?	OBJ,HIM \?CCL24
	CALL	ACCESSIBLE?,P-HIM-OBJECT
	ZERO?	STACK \?CCL27
	CALL	REFERRING
	RFALSE	
?CCL27:	SET	'OBJ,P-HIM-OBJECT
	JUMP	?CND12
?CCL24:	EQUAL?	OBJ,THEM \?CND12
	CALL	ACCESSIBLE?,P-THEM-OBJECT
	ZERO?	STACK \?CCL31
	CALL	REFERRING
	RFALSE	
?CCL31:	SET	'OBJ,P-THEM-OBJECT
?CND12:	CALL	HELD?,OBJ
	ZERO?	STACK \?PRG8
	EQUAL?	OBJ,HANDS /?PRG8
	SET	'PRSO,OBJ
	FSET?	OBJ,TRYTAKEBIT \?CCL38
	SET	'TAKEN,TRUE-VALUE
	JUMP	?CND36
?CCL38:	EQUAL?	WINNER,PROTAGONIST /?CCL40
	SET	'TAKEN,FALSE-VALUE
	JUMP	?CND36
?CCL40:	BTST	BITS,STAKE \?CCL42
	CALL	ITAKE,FALSE-VALUE
	EQUAL?	STACK,TRUE-VALUE \?CCL42
	SET	'TAKEN,FALSE-VALUE
	JUMP	?CND36
?CCL42:	SET	'TAKEN,TRUE-VALUE
?CND36:	ZERO?	TAKEN /?CCL47
	BTST	BITS,SHAVE \?CCL47
	PRINTI	"(You don't seem to be holding"
	GET	TBL,P-MATCHLEN
	LESS?	1,STACK \?CCL54
	PRINTI	" all those things"
	JUMP	?PRG65
?CCL54:	EQUAL?	OBJ,NOT-HERE-OBJECT \?CCL58
	PRINTI	" that"
	JUMP	?PRG65
?CCL58:	CALL	THIS-IS-IT,OBJ
	PRINTC	32
	CALL	ARTICLE,OBJ,TRUE-VALUE
	PRINTD	OBJ
?PRG65:	PRINTI	"!)"
	CRLF	
	RFALSE	
?CCL47:	ZERO?	TAKEN \?PRG8
	EQUAL?	WINNER,PROTAGONIST \?PRG8
	PRINTI	"(taking "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	ZERO?	ITAKE-LOC /?PRG80
	PRINTI	" from "
	CALL	ARTICLE,ITAKE-LOC,TRUE-VALUE
	PRINTD	ITAKE-LOC
?PRG80:	PRINTI	" first)"
	CRLF	
	JUMP	?PRG8


	.FUNCT	MANY-CHECK,LOSS=0,TMP,?TMP1
	GET	P-PRSO,P-MATCHLEN
	GRTR?	STACK,1 \?CCL3
	GETB	P-SYNTAX,P-SLOC1
	BTST	STACK,SMANY /?CCL3
	SET	'LOSS,1
	JUMP	?CND1
?CCL3:	GET	P-PRSI,P-MATCHLEN
	GRTR?	STACK,1 \?CND1
	GETB	P-SYNTAX,P-SLOC2
	BTST	STACK,SMANY /?CND1
	SET	'LOSS,2
?CND1:	ZERO?	LOSS /TRUE
	PRINTC	40
	PRINT	CANT
	PRINTI	" use more than one object at a time with """
	GET	P-ITBL,P-VERBN >TMP
	ZERO?	TMP \?CCL16
	PRINTI	"tell"
	JUMP	?PRG23
?CCL16:	ZERO?	P-OFLAG \?CTR19
	ZERO?	P-MERGED /?CCL20
?CTR19:	GET	TMP,0
	PRINTB	STACK
	JUMP	?PRG23
?CCL20:	GETB	TMP,2 >?TMP1
	GETB	TMP,3
	CALL	WORD-PRINT,?TMP1,STACK
?PRG23:	PRINTI	"."")"
	CRLF	
	RFALSE	


	.FUNCT	ZMEMQ,ITM,TBL,SIZE=-1,CNT=1
	ZERO?	TBL /FALSE
	LESS?	SIZE,0 /?CCL5
	SET	'CNT,0
	JUMP	?PRG6
?CCL5:	GET	TBL,0 >SIZE
?PRG6:	GET	TBL,CNT
	EQUAL?	ITM,STACK \?CCL10
	ZERO?	CNT /TRUE
	RETURN	CNT
?CCL10:	IGRTR?	'CNT,SIZE \?PRG6
	RFALSE	


	.FUNCT	ZMEMQB,ITM,TBL,SIZE,CNT=0
?PRG1:	GETB	TBL,CNT
	EQUAL?	ITM,STACK \?CCL5
	ZERO?	CNT /TRUE
	RETURN	CNT
?CCL5:	IGRTR?	'CNT,SIZE \?PRG1
	RFALSE	


	.FUNCT	LIT?,RM,RMBIT=1,OHERE,LIT=0
	ZERO?	ALWAYS-LIT? /?CND1
	EQUAL?	WINNER,PROTAGONIST /TRUE
?CND1:	SET	'P-GWIMBIT,ONBIT
	SET	'OHERE,HERE
	SET	'HERE,RM
	ZERO?	RMBIT /?CCL7
	FSET?	RM,ONBIT \?CCL7
	SET	'LIT,TRUE-VALUE
	JUMP	?CND5
?CCL7:	PUT	P-MERGE,P-MATCHLEN,0
	SET	'P-TABLE,P-MERGE
	SET	'P-SLOCBITS,-1
	EQUAL?	OHERE,RM \?CND10
	CALL	DO-SL,WINNER,1,1
	EQUAL?	WINNER,PROTAGONIST /?CND10
	IN?	PROTAGONIST,RM \?CND10
	CALL	DO-SL,PROTAGONIST,1,1
?CND10:	CALL	DO-SL,RM,1,1
	GET	P-TABLE,P-MATCHLEN
	GRTR?	STACK,0 \?CND5
	SET	'LIT,TRUE-VALUE
?CND5:	SET	'HERE,OHERE
	SET	'P-GWIMBIT,0
	RETURN	LIT


	.FUNCT	PICK-ONE,FROB,THIS=0,L,CNT,RND,MSG,RFROB
	GET	FROB,0 >L
	GET	FROB,1 >CNT
	DEC	'L
	ADD	FROB,2 >FROB
	MUL	CNT,2
	ADD	FROB,STACK >RFROB
	ZERO?	THIS /?CCL3
	ZERO?	CNT \?CCL3
	SET	'RND,THIS
	JUMP	?CND1
?CCL3:	SUB	L,CNT
	RANDOM	STACK >RND
?CND1:	GET	RFROB,RND >MSG
	GET	RFROB,1
	PUT	RFROB,RND,STACK
	PUT	RFROB,1,MSG
	INC	'CNT
	EQUAL?	CNT,L \?CND6
	SET	'CNT,0
?CND6:	PUT	FROB,0,CNT
	RETURN	MSG


	.FUNCT	DONT-HAVE?,OBJ,WHERE
	LOC	OBJ >WHERE
	EQUAL?	WHERE,PROTAGONIST /FALSE
	IN?	WHERE,PROTAGONIST \?CCL5
	PRINTI	"You'll have to take "
	CALL	ARTICLE,OBJ,TRUE-VALUE
	PRINTD	OBJ
	PRINTC	32
	FSET?	WHERE,CONTBIT \?PRG15
	PRINTI	"out"
	JUMP	?PRG17
?PRG15:	PRINTI	"off"
?PRG17:	PRINTI	" of "
	CALL	ARTICLE,WHERE,TRUE-VALUE
	PRINTD	WHERE
	PRINTR	" first."
?CCL5:	CALL	NOT-HOLDING,OBJ
	RTRUE	


	.FUNCT	NOT-HOLDING,OBJ=0
	PRINTI	"You're not holding "
	ZERO?	OBJ /?PRG6
	CALL	ARTICLE,OBJ,TRUE-VALUE
	PRINTD	OBJ
	JUMP	?PRG8
?PRG6:	PRINTI	"that"
?PRG8:	PRINTR	"."


	.FUNCT	ASKING?,ACTOR
	EQUAL?	PRSA,V?QUESTION,V?ASK-FOR,V?ASK-ABOUT \FALSE
	EQUAL?	PRSO,ACTOR /TRUE
	RFALSE	


	.FUNCT	TALKING-TO?,ACTOR
	CALL	ASKING?,ACTOR
	ZERO?	STACK \TRUE
	EQUAL?	PRSA,V?WAVE-AT,V?HELLO,V?TELL /?PRD7
	EQUAL?	PRSA,V?ALARM,V?REPLY \FALSE
?PRD7:	EQUAL?	PRSO,ACTOR /TRUE
	RFALSE	


	.FUNCT	HURT?,THING
	EQUAL?	PRSA,V?MUNG,V?KICK,V?KILL /?PRD5
	EQUAL?	PRSA,V?KNOCK,V?SQUEEZE,V?CUT /?PRD5
	EQUAL?	PRSA,V?BITE,V?RAPE,V?SHAKE \?CCL3
?PRD5:	EQUAL?	PRSO,THING /TRUE
?CCL3:	EQUAL?	PRSA,V?THROW \FALSE
	EQUAL?	PRSI,THING /TRUE
	RFALSE	


	.FUNCT	ANYONE-HERE?,OBJ
	FIRST?	HERE >OBJ /?PRG1
?PRG1:	ZERO?	OBJ \?CCL5
	RETURN	OBJ
?CCL5:	FSET?	OBJ,ACTORBIT \?CCL7
	EQUAL?	OBJ,PROTAGONIST /?CCL7
	RETURN	OBJ
?CCL7:	NEXT?	OBJ >OBJ /?PRG1
	JUMP	?PRG1


	.FUNCT	GETTING-INTO?
	EQUAL?	PRSA,V?WALK-TO,V?THROUGH,V?ENTER /TRUE
	EQUAL?	PRSA,V?SIT,V?STAND-ON,V?LIE-DOWN /TRUE
	EQUAL?	PRSA,V?CLIMB-UP,V?CLIMB-ON,V?LEAP /TRUE
	EQUAL?	PRSA,V?SWIM,V?WEAR,V?WALK-AROUND /TRUE
	RFALSE	


	.FUNCT	SAY-THE,THING
	PRINTI	"The "
	PRINTD	THING
	RTRUE	


	.FUNCT	BUT-THE,THING
	PRINTI	"But "
	CALL	ARTICLE,THING,TRUE-VALUE
	PRINTD	THING
	PRINTC	32
	RTRUE	


	.FUNCT	MOVING?,THING
	EQUAL?	PRSA,V?MOVE,V?PULL,V?PUSH /?PRD5
	EQUAL?	PRSA,V?TAKE,V?TURN,V?PUSH-TO /?PRD5
	EQUAL?	PRSA,V?RAISE,V?SPIN,V?SHAKE \FALSE
?PRD5:	EQUAL?	PRSO,THING /TRUE
	RFALSE	


	.FUNCT	NOT-HERE-OBJECT-F,TBL,PRSO?=1,OBJ
	EQUAL?	PRSO,NOT-HERE-OBJECT \?CCL3
	EQUAL?	PRSI,NOT-HERE-OBJECT \?CCL3
	PRINTR	"Those things aren't here!"
?CCL3:	EQUAL?	PRSO,NOT-HERE-OBJECT \?CCL9
	SET	'TBL,P-PRSO
	JUMP	?CND1
?CCL9:	SET	'TBL,P-PRSI
	SET	'PRSO?,FALSE-VALUE
?CND1:	ZERO?	PRSO? /?CCL12
	EQUAL?	PRSA,V?FIND,V?FOLLOW,V?BUY /?CCL14
	EQUAL?	PRSA,V?WAIT-FOR /?CCL14
	EQUAL?	PRSA,V?TAKE \?PRG29
	EQUAL?	WINNER,PROTAGONIST /?PRG29
?CCL14:	CALL	FIND-NOT-HERE,TBL,PRSO? >OBJ
	ZERO?	OBJ /FALSE
	EQUAL?	OBJ,NOT-HERE-OBJECT /?PRG29
	RETURN	2
?CCL12:	EQUAL?	PRSA,V?TELL,V?ASK-ABOUT,V?ASK-FOR /FALSE
?PRG29:	PRINT	CANT
	PRINTI	" see"
	CALL	NAME?,P-XNAM
	ZERO?	STACK \?CND31
	PRINTI	" any"
?CND31:	CALL	NOT-HERE-PRINT,PRSO?
	PRINTI	" here!"
	CRLF	
	CALL	PCLEAR
	RETURN	2


	.FUNCT	FIND-NOT-HERE,TBL,PRSO?,M-F,OBJ
	CALL	MOBY-FIND,TBL >M-F
	EQUAL?	1,M-F \?CCL3
	ZERO?	PRSO? /?CCL6
	SET	'PRSO,P-MOBY-FOUND
	RFALSE	
?CCL6:	SET	'PRSI,P-MOBY-FOUND
	RFALSE	
?CCL3:	ZERO?	PRSO? \?CCL8
	PRINTI	"You wouldn't find any"
	CALL	NOT-HERE-PRINT,PRSO?
	PRINTR	" there."
?CCL8:	RETURN	NOT-HERE-OBJECT


	.FUNCT	NOT-HERE-PRINT,PRSO?=0,?TMP1
	ZERO?	P-OFLAG \?CTR2
	ZERO?	P-MERGED /?CCL3
?CTR2:	ZERO?	P-XADJ /?CND6
	PRINTC	32
	PRINTB	P-XADJN
?CND6:	ZERO?	P-XNAM /FALSE
	PRINTC	32
	PRINTB	P-XNAM
	RTRUE	
?CCL3:	ZERO?	PRSO? /?CCL16
	GET	P-ITBL,P-NC1 >?TMP1
	GET	P-ITBL,P-NC1L
	CALL	BUFFER-PRINT,?TMP1,STACK,FALSE-VALUE
	RSTACK	
?CCL16:	GET	P-ITBL,P-NC2 >?TMP1
	GET	P-ITBL,P-NC2L
	CALL	BUFFER-PRINT,?TMP1,STACK,FALSE-VALUE
	RSTACK	


	.FUNCT	PRINT-CONTENTS,THING,OBJ,NXT,1ST?=1,IT?=0,TWO?=0
	FIRST?	THING >OBJ /?PRG1
?PRG1:	ZERO?	OBJ /?REP2
	NEXT?	OBJ >NXT /?KLU50
?KLU50:	FSET?	OBJ,INVISIBLE /?CCL7
	EQUAL?	OBJ,WINNER \?CND6
?CCL7:	MOVE	OBJ,C-OBJECT
?CND6:	SET	'OBJ,NXT
	JUMP	?PRG1
?REP2:	FIRST?	THING >OBJ /?KLU51
?KLU51:	ZERO?	OBJ \?PRG15
	PRINTI	"nothing "
	CALL	PICK-ONE,YAWNS
	PRINT	STACK
	JUMP	?CND10
?PRG15:	ZERO?	OBJ /?CCL19
	NEXT?	OBJ >NXT /?KLU52
?KLU52:	ZERO?	1ST? /?CCL22
	SET	'1ST?,FALSE-VALUE
	JUMP	?CND20
?CCL22:	ZERO?	NXT /?PRG28
	PRINTI	", "
	JUMP	?CND20
?PRG28:	PRINTI	" and "
?CND20:	CALL	ARTICLE,OBJ
	PRINTD	OBJ
	FSET?	OBJ,WORNBIT \?CND32
	PRINTI	" (being worn)"
?CND32:	FSET?	OBJ,ONBIT \?CND36
	PRINTI	" (providing light)"
?CND36:	ZERO?	IT? \?CCL42
	ZERO?	TWO? \?CCL42
	SET	'IT?,OBJ
	JUMP	?CND40
?CCL42:	SET	'TWO?,TRUE-VALUE
	SET	'IT?,FALSE-VALUE
?CND40:	SET	'OBJ,NXT
	JUMP	?PRG15
?CCL19:	ZERO?	IT? /?CND10
	ZERO?	TWO? \?CND10
	CALL	THIS-IS-IT,IT?
?CND10:	CALL	MOVE-ALL,C-OBJECT,THING
	RSTACK	


	.FUNCT	MOVE-ALL,FROM,TO,OBJ,NXT
	FIRST?	FROM >OBJ /?PRG1
?PRG1:	ZERO?	OBJ /TRUE
	NEXT?	OBJ >NXT /?KLU7
?KLU7:	FCLEAR	OBJ,WORNBIT
	MOVE	OBJ,TO
	SET	'OBJ,NXT
	JUMP	?PRG1


	.FUNCT	DESCRIBE-OBJECTS,OBJ,NXT,STR,1ST?=1,TWO?=0,IT?=0
	ZERO?	LIT \?CND1
	CALL	TOO-DARK
	RTRUE	
?CND1:	FIRST?	HERE >OBJ /?KLU89
?KLU89:	ZERO?	OBJ /TRUE
?PRG5:	ZERO?	OBJ /?REP6
	NEXT?	OBJ >NXT /?KLU90
?KLU90:	FSET?	OBJ,INVISIBLE /?CCL11
	FSET?	OBJ,NDESCBIT /?CCL11
	EQUAL?	OBJ,WINNER \?CND10
?CCL11:	MOVE	OBJ,DUMMY-OBJECT
?CND10:	SET	'OBJ,NXT
	JUMP	?PRG5
?REP6:	FIRST?	HERE >OBJ /?PRG15
?PRG15:	ZERO?	OBJ /?REP16
	NEXT?	OBJ >NXT /?KLU92
?KLU92:	GETP	OBJ,P?FDESC >STR
	ZERO?	STR /?CND20
	FSET?	OBJ,TOUCHBIT /?CND20
	CRLF	
	PRINT	STR
	CRLF	
	MOVE	OBJ,DUMMY-OBJECT
?CND20:	SET	'OBJ,NXT
	JUMP	?PRG15
?REP16:	FIRST?	HERE >OBJ /?PRG26
?PRG26:	ZERO?	OBJ /?REP27
	NEXT?	OBJ >NXT /?KLU94
?KLU94:	GETP	OBJ,P?DESCFCN >STR
	ZERO?	STR /?CND31
	CRLF	
	CALL	STR,M-OBJDESC >STR
	CRLF	
	MOVE	OBJ,DUMMY-OBJECT
?CND31:	SET	'OBJ,NXT
	JUMP	?PRG26
?REP27:	FIRST?	HERE >OBJ /?KLU95
?KLU95:	ZERO?	OBJ /?CND33
?PRG35:	ZERO?	OBJ /?CCL39
	NEXT?	OBJ >NXT /?KLU96
?KLU96:	ZERO?	1ST? /?CCL42
	SET	'1ST?,FALSE-VALUE
	CRLF	
	ZERO?	NXT /?PRG48
	PRINT	YOU-SEE
	JUMP	?CND40
?PRG48:	PRINTI	"There's "
	JUMP	?CND40
?CCL42:	ZERO?	NXT /?PRG55
	PRINTI	", "
	JUMP	?CND40
?PRG55:	PRINTI	" and "
?CND40:	CALL	ARTICLE,OBJ
	PRINTD	OBJ
	FSET?	OBJ,ONBIT \?CND59
	PRINTI	" (providing light)"
?CND59:	CALL	SEE-INSIDE?,OBJ
	ZERO?	STACK /?CND63
	CALL	SEE-ANYTHING-IN?,OBJ
	ZERO?	STACK /?CND63
	PRINTI	" with "
	CALL	PRINT-CONTENTS,OBJ
	FSET?	OBJ,CONTBIT \?PRG74
	PRINTI	" in"
	JUMP	?PRG76
?PRG74:	PRINTI	" on"
?PRG76:	PRINTI	" it"
?CND63:	ZERO?	IT? \?CCL80
	ZERO?	TWO? \?CCL80
	SET	'IT?,OBJ
	JUMP	?CND78
?CCL80:	SET	'TWO?,TRUE-VALUE
	SET	'IT?,FALSE-VALUE
?CND78:	SET	'OBJ,NXT
	JUMP	?PRG35
?CCL39:	ZERO?	IT? /?PRG87
	ZERO?	TWO? \?PRG87
	CALL	THIS-IS-IT,IT?
?PRG87:	PRINTI	" here."
	CRLF	
?CND33:	CALL	MOVE-ALL,DUMMY-OBJECT,HERE
	RSTACK	


	.FUNCT	SEE-ANYTHING-IN?,THING,OBJ,NXT,ANY?=0
	FIRST?	THING >OBJ /?PRG1
?PRG1:	ZERO?	OBJ /?REP2
	FSET?	OBJ,INVISIBLE /?CND6
	FSET?	OBJ,NDESCBIT /?CND6
	EQUAL?	OBJ,WINNER /?CND6
	SET	'ANY?,TRUE-VALUE
	RETURN	ANY?
?CND6:	NEXT?	OBJ >OBJ /?PRG1
	JUMP	?PRG1
?REP2:	RETURN	ANY?


	.FUNCT	GLOBAL-IN?,OBJ1,OBJ2,TBL
	GETPT	OBJ2,P?GLOBAL >TBL
	ZERO?	TBL /FALSE
	PTSIZE	TBL
	SUB	STACK,1
	CALL	ZMEMQB,OBJ1,TBL,STACK
	RSTACK	


	.FUNCT	ARTICLE,OBJ,THE=0
	FSET?	OBJ,NARTICLEBIT /FALSE
	ZERO?	THE /?CCL5
	PRINTI	"the "
	RTRUE	
?CCL5:	FSET?	OBJ,VOWELBIT \?PRG12
	PRINTI	"an "
	RTRUE	
?PRG12:	PRINTI	"a "
	RTRUE	


	.FUNCT	HELD?,OBJ
	ZERO?	OBJ /FALSE
	IN?	OBJ,PROTAGONIST /TRUE
	IN?	OBJ,WINNER /TRUE
	FSET?	OBJ,TAKEBIT \FALSE
	IN?	OBJ,ROOMS /FALSE
	IN?	OBJ,GLOBAL-OBJECTS /FALSE
	LOC	OBJ
	CALL	HELD?,STACK
	RSTACK	


	.FUNCT	WHAT-A-CONCEPT
	PRINTR	"What a concept!"


	.FUNCT	YOU-DONT-NEED,THING,STRING?=0
	PRINTI	"(You don't need to refer to "
	ZERO?	STRING? /?CCL5
	PRINTI	"the "
	PRINT	THING
	JUMP	?PRG10
?CCL5:	CALL	ARTICLE,THING,TRUE-VALUE
	PRINTD	THING
?PRG10:	PRINTR	" that way to finish this story.)"


	.FUNCT	ITS-CLOSED,OBJ
	CALL	THIS-IS-IT,OBJ
	CALL	SAY-THE,OBJ
	CALL	IS-CLOSED
	CRLF	
	RTRUE	


	.FUNCT	IS-CLOSED
	PRINTI	" is closed."
	RTRUE	


	.FUNCT	I-PROMPT,GARG=0
	DEC	'P-PROMPT
	RFALSE	

	.ENDI
