

	.FUNCT	V-VERBOSE
	SET	'VERBOSE,TRUE-VALUE
	SET	'SUPER-BRIEF,FALSE-VALUE
	PRINTI	"(Maximum verbosity.)"
	CRLF	
	CRLF	
	CALL	V-LOOK
	RSTACK	


	.FUNCT	V-BRIEF
	SET	'VERBOSE,FALSE-VALUE
	SET	'SUPER-BRIEF,FALSE-VALUE
	PRINTR	"(Brief descriptions.)"


	.FUNCT	V-SUPER-BRIEF
	SET	'SUPER-BRIEF,TRUE-VALUE
	PRINTR	"(Super-brief descriptions.)"


	.FUNCT	V-INVENTORY
	PRINTI	"You're "
	FIRST?	PROTAGONIST \?PRG8
	PRINTI	"holding "
	CALL	PRINT-CONTENTS,PROTAGONIST
	JUMP	?PRG10
?PRG8:	PRINTI	"not holding anything"
?PRG10:	PRINTR	"."


	.FUNCT	SAY-SURE
	PRINTI	"Are you sure you want to "
	RTRUE	


	.FUNCT	V-QUIT,ASK?=1,SCOR
	CALL	V-SCORE
	ZERO?	ASK? /?CCL3
	CALL	SAY-SURE
	PRINTI	"leave the story now?"
	CALL	YES?
	ZERO?	STACK /?PRG9
	QUIT	
	RTRUE	
?PRG9:	PRINT	OKAY
	PRINTR	"continuing."
?CCL3:	QUIT	
	RTRUE	


	.FUNCT	V-RESTART
	CALL	V-SCORE
	CALL	SAY-SURE
	PRINTI	"restart the story?"
	CALL	YES?
	ZERO?	STACK /FALSE
	RESTART	
	CALL	FAILED
	RSTACK	


	.FUNCT	FINISH,REPEATING=0,WORD
	CRLF	
	ZERO?	REPEATING \?PRG3
	CALL	V-SCORE
	CRLF	
?PRG3:	PRINTI	"Do you want to restart the story, restore a saved position, or quit?

(Type RESTART, RESTORE or QUIT.)
>"
	READ	P-INBUF,P-LEXV
	GET	P-LEXV,1 >WORD
	EQUAL?	WORD,W?RESTAR \?CCL7
	RESTART	
	CALL	FAILED
	CALL	FINISH,TRUE-VALUE
	RSTACK	
?CCL7:	EQUAL?	WORD,W?RESTOR \?CCL9
	RESTORE	 \?CCL12
	CALL	SAY-OKAY
	RSTACK	
?CCL12:	CALL	FAILED
	CALL	FINISH,TRUE-VALUE
	RSTACK	
?CCL9:	QUIT	
	RTRUE	


	.FUNCT	YES?,WORD
	CRLF	
?PRG1:	CRLF	
	PRINTI	"(Please type YES or NO.) >"
	PUTB	YES-LEXV,0,4
	READ	YES-INBUF,YES-LEXV
	GET	YES-LEXV,P-LEXSTART >WORD
	GETB	YES-LEXV,P-LEXWORDS
	ZERO?	STACK /?PRG1
	ZERO?	WORD /?PRG1
	EQUAL?	WORD,W?YES,W?Y,W?YUP /TRUE
	EQUAL?	WORD,W?OKAY,W?OK,W?AYE /TRUE
	EQUAL?	WORD,W?SURE,W?AFFIRM,W?POSITI /TRUE
	EQUAL?	WORD,W?NO,W?N,W?NOPE /FALSE
	EQUAL?	WORD,W?NAY,W?NAW,W?NEGATIVE \?PRG1
	RFALSE	


	.FUNCT	SAY-OKAY
	PRINT	OKAY
	PRINTR	"done."


	.FUNCT	FAILED
	PRINTR	"Failed."


	.FUNCT	V-RESTORE
	RESTORE	 \?CCL3
	CALL	SAY-OKAY
	RSTACK	
?CCL3:	CALL	FAILED
	RSTACK	


	.FUNCT	V-SAVE
	SAVE	 \?CCL3
	CALL	SAY-OKAY
	RSTACK	
?CCL3:	CALL	FAILED
	RSTACK	


	.FUNCT	V-SCORE
	PRINTI	"Your score is "
	PRINTN	SCORE
	PRINTI	" point"
	EQUAL?	SCORE,1 /?PRG7
	PRINTC	115
?PRG7:	PRINTI	" out of 100, in "
	PRINTN	MOVES
	PRINTI	" move"
	EQUAL?	MOVES,1 /?PRG13
	PRINTC	115
?PRG13:	PRINTR	"."


	.FUNCT	V-TIME
	PRINTI	"It's "
	CALL	TELL-TIME
	PRINTR	"."


	.FUNCT	TELL-TIME,H,PM?=0
	GRTR?	SCORE,11 \?CND1
	SET	'PM?,TRUE-VALUE
?CND1:	GRTR?	SCORE,12 \?CCL5
	SUB	SCORE,12 >H
	JUMP	?PRG8
?CCL5:	ZERO?	SCORE \?CCL7
	SET	'H,12
	JUMP	?PRG8
?CCL7:	SET	'H,SCORE
?PRG8:	PRINTN	H
	PRINTC	58
	LESS?	MOVES,10 \?PRG14
	PRINTC	48
?PRG14:	PRINTN	MOVES
	ZERO?	PM? /?PRG21
	PRINTI	" pm"
	RTRUE	
?PRG21:	PRINTI	" am"
	RTRUE	


	.FUNCT	V-SCRIPT
	GET	0,8
	BOR	STACK,1
	PUT	0,8,STACK
	CALL	TRANSCRIPT,STR?38
	RTRUE	


	.FUNCT	V-UNSCRIPT
	CALL	TRANSCRIPT,STR?39
	GET	0,8
	BAND	STACK,-2
	PUT	0,8,STACK
	RTRUE	


	.FUNCT	TRANSCRIPT,STR
	PRINTI	"Here "
	PRINT	STR
	PRINTI	"s a transcript of interaction with"
	CRLF	
	CALL	V-VERSION
	RSTACK	


	.FUNCT	V-VERSION,CNT=17,V
	GET	0,1
	BAND	STACK,2047 >V
	CRLF	
	PRINTI	"GENERIC
Copyright (C) 1985 Infocom, Inc. All rights reserved."
	CRLF	
	GETB	0,1
	BTST	STACK,8 \?PRG7
	PRINTI	"Licensed to Tandy Corporation. Version 00.00."
	PRINTN	V
	CRLF	
?PRG7:	PRINTI	"GENERIC is a trademark of Infocom, Inc.
Release "
	PRINTN	V
	PRINTI	" / Serial Number "
?PRG9:	IGRTR?	'CNT,23 /?REP10
	GETB	0,CNT
	PRINTC	STACK
	JUMP	?PRG9
?REP10:	CRLF	
	RTRUE	


	.FUNCT	V-USE
	FSET?	PRSO,ACTORBIT \?CCL3
	CALL	BUT-THE,PRSO
	PRINTR	"might resent that."
?CCL3:	CALL	HOW?
	RSTACK	


	.FUNCT	V-$VERIFY
	ZERO?	PRSO /?PRG11
	EQUAL?	PRSO,INTNUM \?CCL6
	EQUAL?	P-NUMBER,93 \?CCL6
	PRINTN	SERIAL
	CRLF	
	RTRUE	
?CCL6:	CALL	DONT-UNDERSTAND
	RSTACK	
?PRG11:	PRINTI	"Verifying disk."
	CRLF	
	VERIFY	 \?CCL15
	PRINTR	"Correct."
?CCL15:	CALL	FAILED
	RSTACK	


	.FUNCT	V-ALARM
	EQUAL?	PRSO,ME,ROOMS \?CCL3
	PRINTI	"But you're "
	JUMP	?PRG10
?CCL3:	FSET?	PRSO,ACTORBIT \?CCL7
	CALL	BUT-THE,PRSO
	PRINTI	"is "
?PRG10:	PRINTR	"already wide awake!"
?CCL7:	CALL	WHAT-A-CONCEPT
	RTRUE	


	.FUNCT	V-ASK-ABOUT
	CALL	V-ASK-FOR
	RSTACK	


	.FUNCT	V-QUESTION
	CALL	V-ASK-FOR
	RSTACK	


	.FUNCT	V-WAVE-AT
	CALL	V-ASK-FOR
	RSTACK	


	.FUNCT	V-ASK-FOR
	EQUAL?	PRSO,ME,ROOMS \?CCL3
	CALL	PERFORM,V?TELL,ME
	JUMP	?CND1
?CCL3:	CALL	NOT-LIKELY,PRSO,STR?40
?CND1:	CALL	PCLEAR
	RETURN	2


	.FUNCT	V-BITE
	CALL	HACK-HACK,STR?41
	RSTACK	


	.FUNCT	V-BLOW-INTO
	FSET?	PRSO,ACTORBIT \?CCL3
	CALL	PERFORM,V?USE,PRSO
	RTRUE	
?CCL3:	CALL	HACK-HACK,STR?42
	RSTACK	


	.FUNCT	V-BURN
	PRINTI	"With "
	CALL	ARTICLE,PRSI
	PRINTD	PRSI
	PRINTI	"? "
	CALL	PICK-ONE,YUKS
	PRINT	STACK
	CRLF	
	RTRUE	


	.FUNCT	V-BUY
	CALL	VISIBLE?,PRSO
	ZERO?	STACK \?CCL3
	CALL	CANT-SEE-ANY,PRSO
	RTRUE	
?CCL3:	FSET?	PRSO,TAKEBIT /?CCL5
	FSET?	PRSO,TRYTAKEBIT /?CCL5
	PRINT	CANT
	PRINTR	" buy that!"
?CCL5:	CALL	HELD?,PRSO
	ZERO?	STACK /?CCL11
	PRINTR	"You already have one."
?CCL11:	ZERO?	PRSI /?PRG16
	CALL	NOT-LIKELY,PRSI,STR?43
	RSTACK	
?PRG16:	PRINTR	"You don't have any money."


	.FUNCT	V-CLEAN
	CALL	NOT-A,STR?44
	RSTACK	


	.FUNCT	V-CLIMB-DOWN
	EQUAL?	PRSO,ROOMS \?CCL3
	CALL	DO-WALK,P?DOWN
	RSTACK	
?CCL3:	CALL	WHAT-A-CONCEPT
	RSTACK	


	.FUNCT	V-CLIMB-ON
	PRINT	CANT
	PRINTR	" climb onto that."


	.FUNCT	V-CLIMB-OVER
	EQUAL?	PRSO,ROOMS \?PRG4
	CALL	V-WALK-AROUND
	RSTACK	
?PRG4:	PRINT	CANT
	PRINTR	" climb over that."


	.FUNCT	V-CLIMB-UP
	EQUAL?	PRSO,ROOMS \?CCL3
	CALL	DO-WALK,P?UP
	RSTACK	
?CCL3:	CALL	WHAT-A-CONCEPT
	RSTACK	


	.FUNCT	V-CLOSE
	FSET?	PRSO,ACTORBIT \?CCL3
	CALL	NOT-A,STR?45
	RSTACK	
?CCL3:	FSET?	PRSO,SURFACEBIT \?CCL5
	CALL	CANT-CLOSE-THAT
	RSTACK	
?CCL5:	FSET?	PRSO,CONTBIT /?CCL7
	FSET?	PRSO,DOORBIT /?CCL7
	CALL	PERFORM,V?OPEN,PRSO
	RTRUE	
?CCL7:	FSET?	PRSO,SURFACEBIT /?CCL11
	GETP	PRSO,P?CAPACITY
	ZERO?	STACK /?CCL11
	FSET?	PRSO,OPENBIT \?CCL16
	CALL	NOW-CLOSED-OR-OPEN,PRSO
	CALL	SAY-IF-NOT-LIT
	RSTACK	
?CCL16:	CALL	ALREADY-CLOSED
	RSTACK	
?CCL11:	FSET?	PRSO,DOORBIT \?CCL18
	FSET?	PRSO,OPENBIT \?CCL21
	CALL	NOW-CLOSED-OR-OPEN,PRSO
	RSTACK	
?CCL21:	CALL	ALREADY-CLOSED
	RSTACK	
?CCL18:	CALL	CANT-CLOSE-THAT
	RSTACK	


	.FUNCT	CANT-CLOSE-THAT
	PRINT	CANT
	PRINTR	" close that!"


	.FUNCT	NOW-CLOSED-OR-OPEN,THING,OPEN?=0
	CALL	THIS-IS-IT,THING
	PRINT	OKAY
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTI	" is now "
	ZERO?	OPEN? /?CCL7
	FSET	THING,OPENBIT
	PRINTI	"open"
	JUMP	?PRG12
?CCL7:	FCLEAR	THING,OPENBIT
	PRINTI	"closed"
?PRG12:	PRINTR	"."


	.FUNCT	V-COUNT
	CALL	WASTE-OF-TIME
	RSTACK	


	.FUNCT	V-COVER
	CALL	PERFORM,V?PUT-ON,PRSI,PRSO
	RTRUE	


	.FUNCT	V-CROSS
	PRINT	CANT
	PRINTR	" cross that!"


	.FUNCT	V-CUT
	CALL	NOT-LIKELY,PRSI,STR?46
	RSTACK	


	.FUNCT	V-DIG
	CALL	WASTE-OF-TIME
	RSTACK	


	.FUNCT	V-DRINK
	PRINT	CANT
	PRINTR	" drink that!"


	.FUNCT	V-DRINK-FROM
	CALL	WHAT-A-CONCEPT
	RSTACK	


	.FUNCT	V-DROP
	CALL	IDROP
	ZERO?	STACK /FALSE
	PRINTR	"Dropped."


	.FUNCT	IDROP
	CALL	DONT-HAVE?,PRSO
	ZERO?	STACK \FALSE
	IN?	PRSO,WINNER /?CCL5
	LOC	PRSO
	FSET?	STACK,OPENBIT /?CCL5
	PRINT	CANT
	PRINTI	" do that while "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	CALL	IS-CLOSED
	CRLF	
	RFALSE	
?CCL5:	FSET?	PRSO,WORNBIT \?CND1
	CALL	TAKE-OFF-PRSO-FIRST
?CND1:	LOC	WINNER
	MOVE	PRSO,STACK
	RTRUE	


	.FUNCT	V-EAT
	CALL	NOT-LIKELY,PRSO,STR?47
	RSTACK	


	.FUNCT	V-ENTER,VEHICLE
	EQUAL?	PRSO,ROOMS \?CCL3
	CALL	DO-WALK,P?IN
	RTRUE	
?CCL3:	FSET?	PRSO,WEARBIT \?PRG6
	CALL	PRESUMABLY-YOU-WANT-TO,STR?48,PRSO
	CALL	PERFORM,V?WEAR,PRSO
	RTRUE	
?PRG6:	CALL	PICK-ONE,YUKS
	PRINT	STACK
	CRLF	
	RTRUE	


	.FUNCT	PRE-DUMB-EXAMINE
	ZERO?	LIT \?PRG4
	CALL	TOO-DARK
	RTRUE	
?PRG4:	PRINT	I-ASSUME
	PRINTI	" LOOK AT "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTI	", not LOOK INSIDE or LOOK ON or LOOK UNDER or LOOK BEHIND "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTI	".)"
	CRLF	
	CALL	PERFORM,V?EXAMINE,PRSO
	RTRUE	


	.FUNCT	V-DUMB-EXAMINE
	CALL	V-EXAMINE
	RSTACK	


	.FUNCT	PRE-EXAMINE
	ZERO?	LIT \FALSE
	CALL	TOO-DARK
	RTRUE	


	.FUNCT	V-EXAMINE
	FSET?	PRSO,DOORBIT \?CCL3
	PRINTI	"It looks like "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTI	" is "
	FSET?	PRSO,OPENBIT \?PRG13
	PRINTI	"open"
	JUMP	?PRG15
?PRG13:	PRINTI	"closed"
?PRG15:	PRINTR	"."
?CCL3:	FSET?	PRSO,SURFACEBIT \?CCL18
	CALL	V-LOOK-ON
	RSTACK	
?CCL18:	FSET?	PRSO,CONTBIT \?PRG26
	FSET?	PRSO,OPENBIT /?CTR22
	FSET?	PRSO,TRANSBIT \?CCL23
?CTR22:	CALL	V-LOOK-INSIDE
	RSTACK	
?CCL23:	CALL	ITS-CLOSED,PRSO
	RSTACK	
?PRG26:	PRINTI	"You see nothing "
	CALL	PICK-ONE,YAWNS
	PRINT	STACK
	PRINTI	" about "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTR	"."


	.FUNCT	V-EXIT
	CALL	DO-WALK,P?OUT
	RSTACK	


	.FUNCT	V-FILL
	ZERO?	PRSI \?CCL3
	PRINTR	"There's nothing to fill it with."
?CCL3:	CALL	HOW?
	RSTACK	


	.FUNCT	V-FIND,L
	LOC	PRSO >L
	EQUAL?	PRSO,ME,HANDS \?CCL3
	PRINTI	"You're right here"
	JUMP	?PRG41
?CCL3:	IN?	PRSO,PROTAGONIST \?CCL7
	PRINTI	"You're holding it"
	JUMP	?PRG41
?CCL7:	IN?	PRSO,HERE /?CTR10
	EQUAL?	PRSO,PSEUDO-OBJECT \?CCL11
?CTR10:	CALL	BUT-THE,PRSO
	PRINTI	"is right in front of you"
	JUMP	?PRG41
?CCL11:	IN?	PRSO,LOCAL-GLOBALS \?CCL17
	CALL	HOW?
	RTRUE	
?CCL17:	FSET?	L,ACTORBIT \?CCL19
	CALL	VISIBLE?,L
	ZERO?	STACK /?CCL19
	PRINTI	"It looks like "
	CALL	ARTICLE,L,TRUE-VALUE
	PRINTD	L
	PRINTI	" has it"
	JUMP	?PRG41
?CCL19:	CALL	SEE-INSIDE?,L
	ZERO?	STACK /?PRG39
	CALL	VISIBLE?,L
	ZERO?	STACK /?PRG39
	PRINTI	"It's "
	FSET?	L,SURFACEBIT \?PRG37
	PRINTI	"on "
	JUMP	?CND32
?PRG37:	PRINTI	"in "
?CND32:	CALL	ARTICLE,L,TRUE-VALUE
	PRINTD	L
	JUMP	?PRG41
?PRG39:	PRINTI	"You'll have to do that yourself"
?PRG41:	PRINTR	"."


	.FUNCT	V-FIRST-LOOK
	CALL	DESCRIBE-ROOM
	ZERO?	STACK /FALSE
	ZERO?	SUPER-BRIEF \FALSE
	CALL	DESCRIBE-OBJECTS
	RSTACK	


	.FUNCT	V-FLY
	PRINT	CANT
	PRINTR	" do that!"


	.FUNCT	V-FOLLOW,WHERE
	LOC	PRSO >WHERE
	CALL	BUT-THE,PRSO
	PRINTI	"is "
	EQUAL?	WHERE,HERE /?PRG8
	CALL	GLOBAL-IN?,PRSO,HERE
	ZERO?	STACK /?CCL5
?PRG8:	PRINTI	"right here in front of you"
	JUMP	?PRG22
?CCL5:	EQUAL?	WHERE,PROTAGONIST \?CCL11
	PRINTI	"in "
	PRINTD	HANDS
	PRINTC	115
	JUMP	?PRG22
?CCL11:	IN?	WHERE,PROTAGONIST \?PRG20
	PRINTI	"in "
	CALL	ARTICLE,WHERE,TRUE-VALUE
	PRINTD	WHERE
	JUMP	?PRG22
?PRG20:	PRINTI	"nowhere to be seen"
?PRG22:	PRINTR	"!"


	.FUNCT	PRE-FEED
	CALL	PRE-GIVE,TRUE-VALUE
	ZERO?	STACK /FALSE
	RTRUE	


	.FUNCT	V-FEED
	CALL	V-GIVE,TRUE-VALUE
	RSTACK	


	.FUNCT	V-SFEED
	CALL	PERFORM,V?FEED,PRSI,PRSO
	RTRUE	


	.FUNCT	PRE-GIVE,FEED?=0
	ZERO?	PRSO /?CTR2
	ZERO?	PRSI \?CCL3
?CTR2:	CALL	REFERRING
	RTRUE	
?CCL3:	IN?	PRSO,LOCAL-GLOBALS /?CTR6
	IN?	PRSO,PSEUDO-OBJECT \?CCL7
?CTR6:	CALL	NOT-HOLDING
	RTRUE	
?CCL7:	CALL	DONT-HAVE?,PRSO
	ZERO?	STACK \TRUE
	FSET?	PRSI,ACTORBIT /?CCL13
	PRINT	CANT
	ZERO?	FEED? /?PRG21
	PRINTI	" feed"
	JUMP	?PRG23
?PRG21:	PRINTI	" give"
?PRG23:	PRINTR	" anything to that!"
?CCL13:	FSET?	PRSO,WORNBIT \FALSE
	CALL	TAKE-OFF-PRSO-FIRST
	RFALSE	


	.FUNCT	V-SGIVE
	CALL	PERFORM,V?GIVE,PRSI,PRSO
	RTRUE	


	.FUNCT	V-GIVE,FEED?=0
	FSET?	PRSI,ACTORBIT \?PRG8
	PRINTI	"Politely, "
	CALL	ARTICLE,PRSI,TRUE-VALUE
	PRINTD	PRSI
	PRINTR	" refuses your offer."
?PRG8:	PRINT	CANT
	ZERO?	FEED? /?PRG15
	PRINTI	" feed "
	JUMP	?CND10
?PRG15:	PRINTI	" give "
?CND10:	CALL	ARTICLE,PRSO
	PRINTD	PRSO
	PRINTI	" to "
	CALL	ARTICLE,PRSI
	PRINTD	PRSI
	PRINTR	"!"


	.FUNCT	V-HELLO,WHO
	ZERO?	PRSO /?CCL3
	SET	'WHO,PRSO
?CND1:	ZERO?	WHO /?CCL8
	FSET?	WHO,ACTORBIT \?CCL11
	PRINTI	"It's apparent that "
	CALL	ARTICLE,WHO,TRUE-VALUE
	PRINTD	WHO
	PRINTR	" didn't expect you to say that."
?CCL3:	CALL	ANYONE-HERE? >WHO
	ZERO?	WHO /?CND1
	CALL	SPOKEN-TO,WHO
	CALL	PERFORM,V?HELLO,WHO
	RTRUE	
?CCL11:	CALL	NOT-LIKELY,WHO,STR?40
	RSTACK	
?CCL8:	CALL	TALK-TO-SELF
	RSTACK	


	.FUNCT	V-HELP
	PRINTR	"(If you're really stuck, maps and InvisiClues (TM) hint booklets are available using the order form that came in your GENERIC package.)"


	.FUNCT	V-HIDE
	PRINTR	"There aren't any good hiding places here."


	.FUNCT	V-KICK
	CALL	HACK-HACK,STR?49
	RSTACK	


	.FUNCT	V-KILL
	FSET?	PRSO,ACTORBIT /?PRG8
	PRINT	CANT
	PRINTI	" attack "
	CALL	ARTICLE,PRSO
	PRINTD	PRSO
	PRINTR	"!"
?PRG8:	PRINTI	"Attacking "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	ZERO?	PRSI /?PRG14
	PRINTI	" with "
	CALL	ARTICLE,PRSI
	PRINTD	PRSI
?PRG14:	PRINTR	" isn't likely to help matters."


	.FUNCT	V-KNOCK
	FSET?	PRSO,DOORBIT \?CCL3
	CALL	NO-ANSWER
	RSTACK	
?CCL3:	FSET?	PRSO,ACTORBIT \?CCL5
	CALL	PERFORM,V?USE,PRSO
	RTRUE	
?CCL5:	CALL	WASTE-OF-TIME
	RSTACK	


	.FUNCT	V-KISS
	PRINTR	"Smack!"


	.FUNCT	V-LAMP-OFF
	CALL	V-LAMP-ON,TRUE-VALUE
	RSTACK	


	.FUNCT	V-LAMP-ON,OFF?=0
	PRINT	CANT
	PRINTI	" turn that "
	ZERO?	OFF? /?PRG8
	PRINTI	"off"
	JUMP	?PRG10
?PRG8:	PRINTI	"on"
?PRG10:	PRINTR	"."


	.FUNCT	V-LEAP
	EQUAL?	PRSO,ROOMS /?CCL3
	PRINTR	"That'd be a cute trick."
?CCL3:	CALL	WASTE-OF-TIME
	RSTACK	


	.FUNCT	V-LEAVE
	EQUAL?	PRSO,ROOMS /?CTR2
	FSET?	PRSO,TAKEBIT /?CCL3
?CTR2:	CALL	DO-WALK,P?OUT
	RTRUE	
?CCL3:	CALL	DONT-HAVE?,PRSO
	ZERO?	STACK \TRUE
	CALL	PERFORM,V?DROP,PRSO
	RTRUE	


	.FUNCT	V-LIE-DOWN
	PRINTR	"This is no time for resting."


	.FUNCT	V-LISTEN
	PRINTI	"At the moment, "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTR	" makes no sound."


	.FUNCT	V-LOCK
	FSET?	PRSO,DOORBIT /?CTR2
	FSET?	PRSO,CONTBIT \?CCL3
?CTR2:	FSET?	PRSO,OPENBIT \?CCL8
	CALL	YOUD-HAVE-TO,STR?50,PRSO
	RSTACK	
?CCL8:	FSET?	PRSO,LOCKEDBIT \?CCL10
	CALL	BUT-THE,PRSO
	PRINTR	"is already locked."
?CCL10:	CALL	THING-WONT-LOCK,PRSI,PRSO
	RSTACK	
?CCL3:	CALL	CANT-LOCK
	RSTACK	


	.FUNCT	V-UNLOCK
	FSET?	PRSO,DOORBIT /?CTR2
	FSET?	PRSO,CONTBIT \?CCL3
?CTR2:	FSET?	PRSO,OPENBIT \?CCL8
	CALL	ALREADY-OPEN
	RSTACK	
?CCL8:	FSET?	PRSO,LOCKEDBIT /?CCL10
	CALL	BUT-THE,PRSO
	PRINTR	"isn't locked."
?CCL10:	CALL	THING-WONT-LOCK,PRSI,PRSO,TRUE-VALUE
	RSTACK	
?CCL3:	CALL	CANT-LOCK,TRUE-VALUE
	RSTACK	


	.FUNCT	CANT-LOCK,UN?=0
	PRINT	CANT
	PRINTC	32
	ZERO?	UN? /?PRG7
	PRINTI	"un"
?PRG7:	PRINTI	"lock "
	CALL	ARTICLE,PRSO
	PRINTD	PRSO
	PRINTR	"!"


	.FUNCT	THING-WONT-LOCK,THING,CLOSED-THING,UN?=0
	PRINTI	"A quick test shows that "
	CALL	ARTICLE,THING,TRUE-VALUE
	PRINTD	THING
	PRINTI	" won't "
	ZERO?	UN? /?PRG9
	PRINTI	"un"
?PRG9:	PRINTI	"lock "
	CALL	ARTICLE,CLOSED-THING,TRUE-VALUE
	PRINTD	CLOSED-THING
	PRINTR	"."


	.FUNCT	V-LOOK
	CALL	DESCRIBE-ROOM,TRUE-VALUE
	ZERO?	STACK /FALSE
	CALL	DESCRIBE-OBJECTS
	RSTACK	


	.FUNCT	V-LOOK-BEHIND
	ZERO?	LIT \?PRG4
	CALL	TOO-DARK
	RSTACK	
?PRG4:	PRINTI	"There's nothing behind "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTR	"."


	.FUNCT	V-LOOK-DOWN
	ZERO?	LIT \?CCL3
	CALL	TOO-DARK
	RTRUE	
?CCL3:	CALL	PERFORM,V?LOOK-INSIDE,PRSO
	RTRUE	


	.FUNCT	V-LOOK-UP
	ZERO?	LIT \?PRG4
	CALL	TOO-DARK
	RSTACK	
?PRG4:	PRINTR	"You begin to get a stiff neck."


	.FUNCT	V-LOOK-INSIDE
	ZERO?	LIT \?CCL3
	CALL	TOO-DARK
	RSTACK	
?CCL3:	FSET?	PRSO,ACTORBIT \?CCL5
	CALL	NOT-A,STR?45
	RSTACK	
?CCL5:	FSET?	PRSO,DOORBIT \?CCL7
	CALL	PERFORM,V?EXAMINE,PRSO
	RTRUE	
?CCL7:	FSET?	PRSO,CONTBIT \?PRG23
	LOC	WINNER
	EQUAL?	PRSO,STACK \?CCL12
	CALL	V-LOOK
	RSTACK	
?CCL12:	FSET?	PRSO,OPENBIT /?PRG17
	FSET?	PRSO,TRANSBIT /?PRG17
	CALL	ITS-CLOSED,PRSO
	RSTACK	
?PRG17:	PRINT	YOU-SEE
	CALL	PRINT-CONTENTS,PRSO
	PRINTI	" in "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTR	"."
?PRG23:	PRINT	CANT
	PRINTI	" look inside "
	CALL	ARTICLE,PRSO
	PRINTD	PRSO
	PRINTR	"."


	.FUNCT	NOT-A,STR
	PRINTI	"You're not a "
	PRINT	STR
	PRINTR	"!"


	.FUNCT	V-LOOK-ON
	ZERO?	LIT \?PRG3
	CALL	TOO-DARK
	RTRUE	
?PRG3:	PRINT	YOU-SEE
	FSET?	PRSO,SURFACEBIT \?PRG8
	CALL	PRINT-CONTENTS,PRSO
	JUMP	?PRG10
?PRG8:	PRINTI	"nothing "
	CALL	PICK-ONE,YAWNS
	PRINT	STACK
?PRG10:	PRINTI	" on "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTR	"."


	.FUNCT	V-LOOK-THRU
	ZERO?	LIT \?CCL3
	CALL	TOO-DARK
	RSTACK	
?CCL3:	ZERO?	PRSI /?CCL5
	FSET?	PRSI,TRANSBIT /?CCL5
	PRINT	CANT
	PRINTR	" look through that!"
?CCL5:	CALL	NOTHING-INTERESTING,TRUE-VALUE
	RSTACK	


	.FUNCT	V-LOOK-UNDER
	ZERO?	LIT \?CCL3
	CALL	TOO-DARK
	RSTACK	
?CCL3:	IN?	PRSO,PROTAGONIST \?CCL5
	PRINTI	"You're already "
	FSET?	PRSO,WORNBIT \?PRG13
	PRINTI	"wear"
	JUMP	?PRG15
?PRG13:	PRINTI	"hold"
?PRG15:	PRINTR	"ing that!"
?CCL5:	CALL	NOTHING-INTERESTING,TRUE-VALUE
	RSTACK	


	.FUNCT	V-LOWER
	CALL	V-RAISE
	RSTACK	


	.FUNCT	V-MOVE
	EQUAL?	PRSO,ROOMS \?CCL3
	CALL	V-WALK-AROUND
	RSTACK	
?CCL3:	FSET?	PRSO,TAKEBIT \?PRG10
	PRINTI	"Moving "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTI	" reveals nothing "
	CALL	PICK-ONE,YAWNS
	PRINT	STACK
	PRINTR	"."
?PRG10:	PRINT	CANT
	PRINTI	" move "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTR	"."


	.FUNCT	V-MUNG
	CALL	HACK-HACK,STR?51
	RSTACK	


	.FUNCT	V-OPEN,F,STR
	FSET?	PRSO,ACTORBIT \?CCL3
	CALL	NOT-A,STR?45
	RSTACK	
?CCL3:	FSET?	PRSO,CONTBIT /?CCL5
	FSET?	PRSO,DOORBIT /?CCL5
	PRINTI	"How can you"
	CALL	DO-TO
	CALL	ARTICLE,PRSO
	PRINTD	PRSO
	PRINTR	"?"
?CCL5:	FSET?	PRSO,OPENBIT \?CCL13
	CALL	ALREADY-OPEN
	RSTACK	
?CCL13:	FSET?	PRSO,LOCKEDBIT \?CCL15
	CALL	OBJECT-IS-LOCKED
	RSTACK	
?CCL15:	FSET?	PRSO,CONTBIT \?CCL17
	FSET	PRSO,OPENBIT
	FSET	PRSO,TOUCHBIT
	FIRST?	PRSO \?CTR19
	FSET?	PRSO,TRANSBIT \?PRG23
?CTR19:	CALL	NOW-CLOSED-OR-OPEN,PRSO,TRUE-VALUE
	RSTACK	
?PRG23:	PRINTI	"Opening "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTI	" reveals "
	CALL	PRINT-CONTENTS,PRSO
	PRINTR	"."
?CCL17:	CALL	NOW-CLOSED-OR-OPEN,PRSO,TRUE-VALUE
	RSTACK	


	.FUNCT	V-PAY
	CALL	PERFORM,V?GIVE,PRSI,PRSO
	RTRUE	


	.FUNCT	V-PLAY
	EQUAL?	PRSO,ROOMS \?CCL3
	CALL	WASTE-OF-TIME
	RSTACK	
?CCL3:	CALL	HACK-HACK,STR?52
	RSTACK	


	.FUNCT	V-PICK
	FSET?	PRSO,DOORBIT \?CCL3
	CALL	NOT-A,STR?53
	RSTACK	
?CCL3:	CALL	WHAT-A-CONCEPT
	RSTACK	


	.FUNCT	V-POINT
	PRINTR	"It's not polite to point."


	.FUNCT	V-POUR
	PRINT	CANT
	PRINTR	" pour that!"


	.FUNCT	V-EMPTY,OBJ,NXT
	FSET?	PRSO,CONTBIT \?PRG23
	FSET?	PRSO,OPENBIT \?CCL6
	FIRST?	PRSO >OBJ /?KLU25
?KLU25:	ZERO?	OBJ /?CCL9
?PRG10:	ZERO?	OBJ /TRUE
	NEXT?	OBJ >NXT /?KLU26
?KLU26:	FSET?	OBJ,NARTICLEBIT /?PRG19
	PRINTI	"The "
?PRG19:	PRINTD	OBJ
	PRINTI	": "
	CALL	PERFORM,V?TAKE,OBJ,PRSO
	SET	'OBJ,NXT
	JUMP	?PRG10
?CCL9:	CALL	BUT-THE,PRSO
	PRINTR	"is already empty!"
?CCL6:	CALL	ITS-CLOSED,PRSO
	RTRUE	
?PRG23:	PRINT	CANT
	PRINTR	" empty that!"


	.FUNCT	V-PULL
	CALL	HACK-HACK,STR?54
	RSTACK	


	.FUNCT	V-PUSH
	CALL	HACK-HACK,STR?55
	RSTACK	


	.FUNCT	V-PUSH-TO
	PRINT	CANT
	PRINTR	" push things to that."


	.FUNCT	PRE-PUT
	IN?	PRSO,GLOBAL-OBJECTS /?PRG6
	FSET?	PRSO,TAKEBIT /?CCL3
?PRG6:	CALL	PICK-ONE,YUKS
	PRINT	STACK
	CRLF	
	RTRUE	
?CCL3:	CALL	DONT-HAVE?,PRSO
	ZERO?	STACK \TRUE
	CALL	ACCESSIBLE?,PRSI
	ZERO?	STACK \?CCL11
	CALL	CANT-SEE-ANY,PRSI
	RTRUE	
?CCL11:	FSET?	PRSO,WORNBIT \FALSE
	CALL	TAKE-OFF-PRSO-FIRST
	RFALSE	


	.FUNCT	TAKE-OFF-PRSO-FIRST
	PRINTI	"(taking off "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTI	" first)"
	CRLF	
	CALL	PERFORM,V?TAKE-OFF,PRSO
	CRLF	
	RTRUE	


	.FUNCT	V-PUT,?TMP1,?TMP2,?TMP3
	ZERO?	PRSI /?CCL3
	FSET?	PRSI,OPENBIT /?CCL3
	FSET?	PRSI,DOORBIT /?CCL3
	FSET?	PRSI,CONTBIT /?CCL3
	FSET?	PRSI,SURFACEBIT /?CCL3
	PRINT	CANT
	PRINTR	" possibly do that!"
?CCL3:	FSET?	PRSI,OPENBIT /?CCL12
	FSET?	PRSI,SURFACEBIT /?CCL12
	CALL	BUT-THE,PRSI
	PRINTI	"isn't open!"
	CRLF	
	CALL	THIS-IS-IT,PRSI
	RSTACK	
?CCL12:	EQUAL?	PRSI,PRSO \?CCL18
	CALL	WHAT-A-CONCEPT
	RSTACK	
?CCL18:	IN?	PRSO,PRSI \?CCL20
	CALL	BUT-THE,PRSO
	PRINTI	"is already "
	FSET?	PRSI,SURFACEBIT \?PRG28
	PRINTI	"on "
	JUMP	?CND23
?PRG28:	PRINTI	"in "
?CND23:	CALL	ARTICLE,PRSI,TRUE-VALUE
	PRINTD	PRSI
	PRINTR	"!"
?CCL20:	CALL	WEIGHT,PRSI >?TMP3
	CALL	WEIGHT,PRSO
	ADD	?TMP3,STACK >?TMP2
	GETP	PRSI,P?SIZE
	SUB	?TMP2,STACK >?TMP1
	GETP	PRSI,P?CAPACITY
	GRTR?	?TMP1,STACK \?CCL33
	PRINTI	"There's no room."
	CRLF	
	CRLF	
	RTRUE	
?CCL33:	IN?	PRSO,PROTAGONIST /?CCL37
	CALL	ITAKE
	EQUAL?	STACK,FALSE-VALUE,M-FATAL /TRUE
?CCL37:	MOVE	PRSO,PRSI
	FSET	PRSO,TOUCHBIT
	PRINTR	"Done."


	.FUNCT	SAY-IF-NOT-LIT
	CALL	LIT?,HERE >LIT
	ZERO?	LIT \FALSE
	CRLF	
	CALL	NOW-BLACK
	CRLF	
	RTRUE	


	.FUNCT	V-PUT-BEHIND
	PRINTR	"That hiding place is too obvious."


	.FUNCT	PRE-PUT-ON
	CALL	PRE-PUT
	ZERO?	STACK /FALSE
	RTRUE	


	.FUNCT	V-PUT-ON
	EQUAL?	PRSI,ME \?CCL3
	CALL	PERFORM,V?WEAR,PRSO
	RTRUE	
?CCL3:	FSET?	PRSI,SURFACEBIT \?PRG6
	CALL	V-PUT
	RSTACK	
?PRG6:	PRINTI	"There's no good surface on "
	ZERO?	PRSI /?PRG11
	CALL	ARTICLE,PRSI,TRUE-VALUE
	PRINTD	PRSI
	JUMP	?PRG13
?PRG11:	PRINTI	"that"
?PRG13:	PRINTR	"."


	.FUNCT	V-PUT-UNDER
	PRINT	CANT
	PRINTR	" put anything under that."


	.FUNCT	V-RAPE
	PRINTR	"What a wholesome idea."


	.FUNCT	V-RAISE
	CALL	HACK-HACK,STR?56
	RSTACK	


	.FUNCT	V-REACH-IN,OBJ
	FIRST?	PRSO >OBJ /?KLU23
?KLU23:	FSET?	PRSO,ACTORBIT \?CCL3
	CALL	NOT-A,STR?45
	RSTACK	
?CCL3:	FSET?	PRSO,CONTBIT /?CCL5
	CALL	PICK-ONE,YUKS
	PRINT	STACK
	CRLF	
	RTRUE	
?CCL5:	FSET?	PRSO,OPENBIT /?CCL9
	PRINTR	"It's not open."
?CCL9:	ZERO?	OBJ /?PRG17
	FSET?	OBJ,INVISIBLE /?PRG17
	FSET?	OBJ,TAKEBIT /?PRG19
?PRG17:	PRINTR	"It's empty."
?PRG19:	PRINTI	"You reach into "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTR	" and feel something."


	.FUNCT	V-READ
	ZERO?	LIT \?CCL3
	CALL	TOO-DARK
	RSTACK	
?CCL3:	FSET?	PRSO,READBIT /?PRG8
	CALL	HOW-READ
	PRINTR	"?"
?PRG8:	PRINTR	"It's undecipherable."


	.FUNCT	V-READ-TO
	ZERO?	LIT \?CCL3
	CALL	TOO-DARK
	RSTACK	
?CCL3:	FSET?	PRSO,READBIT /?CCL5
	CALL	HOW-READ
	PRINTI	" to "
	CALL	ARTICLE,PRSI
	PRINTD	PRSI
	PRINTR	"?"
?CCL5:	CALL	NOT-LIKELY,PRSI,STR?57
	RSTACK	


	.FUNCT	HOW-READ
	PRINTI	"How can you read "
	CALL	ARTICLE,PRSO
	PRINTD	PRSO
	RTRUE	


	.FUNCT	V-RELEASE
	EQUAL?	PRSO,ME \?CCL3
	PRINTI	"But you are"
	JUMP	?PRG8
?CCL3:	CALL	BUT-THE,PRSO
	PRINTI	"is"
?PRG8:	PRINTR	"n't confined by anything!"


	.FUNCT	V-REPLACE
	EQUAL?	PRSO,ME \?CCL3
	PRINTI	"That's easy"
	JUMP	?PRG8
?CCL3:	CALL	BUT-THE,PRSO
	PRINTI	"doesn't need replacement"
?PRG8:	PRINTR	"."


	.FUNCT	V-REPLY
	CALL	NOT-LIKELY,PRSO,STR?58
	CALL	PCLEAR
	RETURN	2


	.FUNCT	V-RESCUE
	EQUAL?	PRSO,ME \?CCL3
	CALL	V-HELP
	RSTACK	
?CCL3:	CALL	BUT-THE,PRSO
	PRINTR	"doesn't need any help."


	.FUNCT	V-RIDE
	FSET?	PRSO,ACTORBIT \?PRG4
	CALL	NOT-LIKELY,PRSO,STR?59
	JUMP	?CND1
?PRG4:	PRINT	CANT
	PRINTI	" ride that!"
	CRLF	
?CND1:	CRLF	
	RTRUE	


	.FUNCT	V-RUB
	CALL	HACK-HACK,STR?60
	RSTACK	


	.FUNCT	V-BOW
	CALL	HACK-HACK,STR?61
	RSTACK	


	.FUNCT	V-YELL
	CALL	PCLEAR
	CALL	ANYONE-HERE?
	ZERO?	STACK /?PRG6
	CALL	WAY-TO-TALK
	RETURN	2
?PRG6:	PRINTR	"You begin to get a sore throat."


	.FUNCT	V-SAY
	CALL	ANYONE-HERE?
	ZERO?	STACK /?CCL3
	CALL	WAY-TO-TALK
	CALL	PCLEAR
	RETURN	2
?CCL3:	CALL	TALK-TO-SELF
	RSTACK	


	.FUNCT	V-SEARCH
	EQUAL?	PRSO,ME \?CCL3
	CALL	V-HELP
	RSTACK	
?CCL3:	FSET?	PRSO,CONTBIT \?CCL5
	FSET?	PRSO,OPENBIT /?PRG11
	FSET?	PRSO,TRANSBIT /?PRG11
	CALL	YOUD-HAVE-TO,STR?62,PRSO
	RSTACK	
?PRG11:	PRINT	YOU-SEE
	CALL	PRINT-CONTENTS,PRSO
	PRINTI	" inside "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTR	"."
?CCL5:	FSET?	PRSO,SURFACEBIT \?CCL18
	PRINT	YOU-SEE
	CALL	PRINT-CONTENTS,PRSO
	PRINTI	" on "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTR	"."
?CCL18:	FSET?	PRSO,ACTORBIT \?CCL26
	CALL	PERFORM,V?USE,PRSO
	RTRUE	
?CCL26:	CALL	NOTHING-INTERESTING
	RSTACK	


	.FUNCT	NOTHING-INTERESTING,SEE?=0
	PRINTI	"You "
	ZERO?	SEE? /?PRG8
	PRINTI	"see"
	JUMP	?PRG10
?PRG8:	PRINTI	"find"
?PRG10:	PRINTI	" nothing "
	CALL	PICK-ONE,YAWNS
	PRINT	STACK
	PRINTR	"."


	.FUNCT	V-SHAKE,X
	FSET?	PRSO,ACTORBIT \?CCL3
	CALL	PERFORM,V?ALARM,PRSO
	RTRUE	
?CCL3:	FSET?	PRSO,TAKEBIT /?CCL5
	FSET?	PRSO,TRYTAKEBIT /?CCL5
	CALL	HACK-HACK,STR?67
	RSTACK	
?CCL5:	CALL	WASTE-OF-TIME
	RSTACK	


	.FUNCT	V-SHOOT
	PRINTR	"You don't have any weapons."


	.FUNCT	V-SIT
	CALL	WASTE-OF-TIME
	RSTACK	


	.FUNCT	V-SLEEP
	PRINTR	"You're not tired."


	.FUNCT	V-SMELL
	EQUAL?	PRSO,ROOMS \?PRG6
	PRINTI	"You smell nothing "
	CALL	PICK-ONE,YAWNS
	PRINT	STACK
	JUMP	?PRG8
?PRG6:	PRINTI	"It smells just like "
	CALL	ARTICLE,PRSO
	PRINTD	PRSO
?PRG8:	PRINTR	"."


	.FUNCT	V-SPIN
	PRINT	CANT
	PRINTR	" spin that!"


	.FUNCT	V-SQUEEZE
	CALL	WASTE-OF-TIME
	RSTACK	


	.FUNCT	V-STAND
	PRINTR	"You're already standing."


	.FUNCT	V-STAND-ON
	CALL	WASTE-OF-TIME
	RSTACK	


	.FUNCT	V-STAND-UNDER
	CALL	PICK-ONE,YUKS
	PRINT	STACK
	CRLF	
	RTRUE	


	.FUNCT	V-SWING
	ZERO?	PRSI \?CCL3
	PRINTR	"Whoosh!"
?CCL3:	CALL	PERFORM,V?KILL,PRSI,PRSO
	RTRUE	


	.FUNCT	V-SWIM
	PRINT	CANT
	PRINTR	" swim here!"


	.FUNCT	V-TAKE-OFF,WHERE
	FSET?	PRSO,TAKEBIT \?CCL3
	IN?	PRSO,PROTAGONIST \?PRG13
	FSET?	PRSO,WORNBIT \?PRG13
	FCLEAR	PRSO,WORNBIT
	PRINT	OKAY
	PRINTI	"you're no longer wearing "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTR	"."
?PRG13:	PRINTR	"You aren't wearing that!"
?CCL3:	CALL	DO-WALK,P?OUT
	RSTACK	


	.FUNCT	V-TASTE
	CALL	PERFORM,V?EAT,PRSO
	RTRUE	


	.FUNCT	V-TELL
	EQUAL?	PRSO,ME,ROOMS \?CCL3
	CALL	TALK-TO-SELF
	RSTACK	
?CCL3:	FSET?	PRSO,ACTORBIT \?PRG9
	ZERO?	P-CONT /?CCL8
	SET	'WINNER,PRSO
	LOC	WINNER >HERE
	RETURN	HERE
?CCL8:	CALL	NO-ANSWER
	RSTACK	
?PRG9:	PRINT	CANT
	PRINTI	" talk to "
	CALL	ARTICLE,PRSO
	PRINTD	PRSO
	PRINTC	33
	CRLF	
	CALL	PCLEAR
	RETURN	2


	.FUNCT	NO-ANSWER
	PRINTR	"There's no answer."


	.FUNCT	V-THANK
	FSET?	PRSO,ACTORBIT \?PRG8
	PRINTI	"You do so, but "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTR	" seems less than overjoyed by your gratitude."
?PRG8:	PRINTR	"You're loony."


	.FUNCT	V-THROUGH
	EQUAL?	PRSO,ROOMS \?CCL3
	CALL	DO-WALK,P?IN
	RSTACK	
?CCL3:	FSET?	PRSO,DOORBIT \?CCL5
	CALL	OTHER-SIDE,PRSO
	CALL	DO-WALK,STACK
	RTRUE	
?CCL5:	IN?	PRSO,WINNER \?CCL7
	PRINTR	"That would involve quite a contortion!"
?CCL7:	FSET?	PRSO,ACTORBIT \?PRG12
	CALL	V-RAPE
	RSTACK	
?PRG12:	CALL	PICK-ONE,YUKS
	PRINT	STACK
	CRLF	
	RTRUE	


	.FUNCT	PRE-THROW
	CALL	PRE-PUT
	ZERO?	STACK /FALSE
	RTRUE	


	.FUNCT	V-THROW
	CALL	IDROP
	ZERO?	STACK /FALSE
	PRINTR	"Thrown."


	.FUNCT	V-THROW-OFF
	CALL	WASTE-OF-TIME
	RSTACK	


	.FUNCT	V-TIE
	PRINT	CANT
	PRINTI	" tie "
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTR	" to that."


	.FUNCT	V-TIE-UP
	PRINT	CANT
	PRINTR	" tie anything with that!"


	.FUNCT	V-TURN
	FSET?	PRSO,TAKEBIT /?CCL3
	FSET?	PRSO,TRYTAKEBIT /?CCL3
	CALL	PICK-ONE,YUKS
	PRINT	STACK
	CRLF	
	RTRUE	
?CCL3:	CALL	HACK-HACK,STR?68
	RSTACK	


	.FUNCT	DO-WALK,DIR
	SET	'P-WALK-DIR,DIR
	CALL	PERFORM,V?WALK,DIR
	RTRUE	


	.FUNCT	V-WALK,PT,PTS,STR,OBJ,RM
	ZERO?	P-WALK-DIR \?CCL3
	ZERO?	PRSO /?CCL6
	CALL	PRESUMABLY-YOU-WANT-TO,STR?69,PRSO
	CALL	PERFORM,V?WALK-TO,PRSO
	RTRUE	
?CCL6:	CALL	V-WALK-AROUND
	RTRUE	
?CCL3:	GETPT	HERE,PRSO >PT
	ZERO?	PT /?CCL8
	PTSIZE	PT >PTS
	EQUAL?	PTS,UEXIT \?CCL11
	GETB	PT,REXIT
	CALL	GOTO,STACK
	RSTACK	
?CCL11:	EQUAL?	PTS,NEXIT \?CCL13
	GET	PT,NEXITSTR
	PRINT	STACK
	CRLF	
	RETURN	2
?CCL13:	EQUAL?	PTS,FEXIT \?CCL19
	GET	PT,FEXITFCN
	CALL	STACK >RM
	ZERO?	RM /?PRG23
	CALL	GOTO,RM
	RSTACK	
?PRG23:	RETURN	2
?CCL19:	EQUAL?	PTS,CEXIT \?CCL26
	GETB	PT,CEXITFLAG
	VALUE	STACK
	ZERO?	STACK /?CCL29
	GETB	PT,REXIT
	CALL	GOTO,STACK
	RSTACK	
?CCL29:	GET	PT,CEXITSTR >STR
	ZERO?	STR /?CCL31
	PRINT	STR
	CRLF	
	RETURN	2
?CCL31:	CALL	CANT-GO
	RETURN	2
?CCL26:	EQUAL?	PTS,DEXIT \FALSE
	GETB	PT,DEXITOBJ >OBJ
	FSET?	OBJ,OPENBIT \?CCL42
	GETB	PT,REXIT
	CALL	GOTO,STACK
	RSTACK	
?CCL42:	GET	PT,DEXITSTR >STR
	ZERO?	STR /?CCL44
	PRINT	STR
	CRLF	
	CALL	THIS-IS-IT,OBJ
	RETURN	2
?CCL44:	CALL	ITS-CLOSED,OBJ
	RETURN	2
?CCL8:	CALL	CANT-GO
	RETURN	2


	.FUNCT	V-WALK-AROUND
	PRINTI	"(Do you have any particular direction in mind?)"
	CRLF	
	RFALSE	


	.FUNCT	V-WALK-TO
	ZERO?	PRSO /?CCL3
	EQUAL?	PRSO,INTDIR \?CCL6
	CALL	DO-WALK,P-DIRECTION
	RTRUE	
?CCL6:	CALL	V-FOLLOW
	RSTACK	
?CCL3:	CALL	V-WALK-AROUND
	RSTACK	


	.FUNCT	V-WAIT,NUM=3
	PRINTI	"Time passes."
	CRLF	
?PRG3:	DLESS?	'NUM,0 /?REP4
	CALL	CLOCKER
	ZERO?	STACK /?PRG3
?REP4:	SET	'CLOCK-WAIT,TRUE-VALUE
	RETURN	CLOCK-WAIT


	.FUNCT	V-WAIT-FOR
	LOC	PRSO
	EQUAL?	STACK,HERE,WINNER \?PRG6
	CALL	BUT-THE,PRSO
	PRINTR	"is already here!"
?PRG6:	PRINTR	"You may be waiting quite a while."


	.FUNCT	V-WEAR
	IN?	PRSO,PROTAGONIST \?CCL3
	FSET?	PRSO,WORNBIT \?CCL3
	PRINTI	"You're already wearing "
	JUMP	?CND1
?CCL3:	FSET?	PRSO,WEARBIT /?CCL9
	PRINT	CANT
	PRINTI	" wear "
	JUMP	?CND1
?CCL9:	CALL	DONT-HAVE?,PRSO
	ZERO?	STACK \TRUE
	FSET	PRSO,WORNBIT
	PRINT	OKAY
	PRINTI	"you're now wearing "
?CND1:	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTR	"."


	.FUNCT	PRE-TAKE,CONTAINER
	LOC	PRSO >CONTAINER
	IN?	PRSO,WINNER \?CCL3
	PRINTI	"You're already "
	FSET?	PRSO,WORNBIT \?PRG11
	PRINTI	"wear"
	JUMP	?PRG13
?PRG11:	PRINTI	"hold"
?PRG13:	PRINTR	"ing it."
?CCL3:	ZERO?	CONTAINER /?CCL16
	FSET?	CONTAINER,CONTBIT \?CCL16
	FSET?	CONTAINER,OPENBIT /?CCL16
	PRINT	CANT
	PRINTI	" reach into "
	CALL	ARTICLE,CONTAINER,TRUE-VALUE
	PRINTD	CONTAINER
	PRINTR	". It's closed."
?CCL16:	ZERO?	PRSI /?CCL25
	EQUAL?	PRSO,ME \?CCL28
	CALL	PERFORM,V?DROP,PRSI
	RTRUE	
?CCL28:	IN?	PRSO,PRSI /FALSE
	FSET?	PRSI,ACTORBIT \?CCL33
	CALL	BUT-THE,PRSI
	PRINTI	"doesn't have "
	CALL	ARTICLE,PRSO
	PRINTD	PRSO
	JUMP	?PRG38
?CCL33:	CALL	BUT-THE,PRSO
	PRINTI	"isn't in "
	CALL	ARTICLE,PRSI,TRUE-VALUE
	PRINTD	PRSI
?PRG38:	PRINTR	"."
?CCL25:	LOC	WINNER
	EQUAL?	PRSO,STACK \FALSE
	PRINTR	"You're in it!"


	.FUNCT	V-TAKE,CNT
	CALL	ITAKE
	ZERO?	STACK /FALSE
	PRINTI	"Taken."
	CRLF	
	GETP	PRSO,P?VALUE >CNT
	GRTR?	CNT,0 \TRUE
	ADD	SCORE,CNT >SCORE
	PUTP	PRSO,P?VALUE,0
	RTRUE	


	.FUNCT	ITAKE,VB=1,CNT,OBJ
	CALL	THIS-IS-IT,PRSO
	FSET?	PRSO,TAKEBIT /?CCL3
	ZERO?	VB /FALSE
	CALL	PICK-ONE,YUKS
	PRINT	STACK
	CRLF	
	RFALSE	
?CCL3:	CALL	TOO-MUCH-JUNK?,VB
	ZERO?	STACK \FALSE
	MOVE	PRSO,WINNER
	FSET	PRSO,TOUCHBIT
	FCLEAR	PRSO,NDESCBIT
	RTRUE	


	.FUNCT	TOO-MUCH-JUNK?,VB=1,?TMP1
	LOC	PRSO
	IN?	STACK,WINNER /?CCL3
	CALL	WEIGHT,PRSO >?TMP1
	CALL	WEIGHT,WINNER
	ADD	?TMP1,STACK
	GRTR?	STACK,LOAD-ALLOWED \?CCL3
	ZERO?	VB /TRUE
	FIRST?	PROTAGONIST \?PRG13
	PRINTI	"Your load is"
	JUMP	?PRG15
?PRG13:	PRINTI	"It's a little"
?PRG15:	PRINTR	" too heavy."
?CCL3:	CALL	CCOUNT,WINNER
	GRTR?	STACK,FUMBLE-NUMBER \FALSE
	ZERO?	VB /TRUE
	PRINTR	"You're holding too many things already!"


	.FUNCT	CCOUNT,THING,OBJ,CNT=0
	FIRST?	THING >OBJ /?PRG1
?PRG1:	ZERO?	OBJ /?REP2
	FSET?	OBJ,WORNBIT /?CND6
	INC	'CNT
?CND6:	NEXT?	OBJ >OBJ /?PRG1
	JUMP	?PRG1
?REP2:	RETURN	CNT


	.FUNCT	WEIGHT,THING,OBJ,WT=0
	FIRST?	THING >OBJ /?PRG1
?PRG1:	ZERO?	OBJ /?REP2
	EQUAL?	THING,PROTAGONIST \?CCL8
	FSET?	OBJ,WORNBIT \?CCL8
	INC	'WT
	JUMP	?CND6
?CCL8:	CALL	WEIGHT,OBJ
	ADD	WT,STACK >WT
?CND6:	NEXT?	OBJ >OBJ /?PRG1
	JUMP	?PRG1
?REP2:	GETP	THING,P?SIZE
	ADD	WT,STACK >WT
	RETURN	WT


	.FUNCT	DESCRIBE-ROOM,LOOK?=0,V?,STR,AV
	ZERO?	LOOK? /?PRD3
	SET	'V?,LOOK?
	JUMP	?PEN1
?PRD3:	SET	'V?,VERBOSE
?PEN1:	ZERO?	LIT /?CCL6
	SET	'FIRST-WARNING?,TRUE-VALUE
	FSET?	HERE,TOUCHBIT /?CND13
	FSET	HERE,TOUCHBIT
	SET	'V?,TRUE-VALUE
?CND13:	IN?	HERE,ROOMS \?CND15
	PRINTD	HERE
	CRLF	
?CND15:	ZERO?	LOOK? \?CCL20
	ZERO?	SUPER-BRIEF \TRUE
?CCL20:	LOC	WINNER >AV
	ZERO?	V? /?CCL25
	GETP	HERE,P?ACTION
	CALL	STACK,M-LOOK
	ZERO?	STACK \TRUE
?CCL25:	ZERO?	V? /?CCL29
	GETP	HERE,P?LDESC >STR
	ZERO?	STR /?CCL29
	PRINT	STR
	CRLF	
	JUMP	?CND23
?CCL6:	CALL	NOW-BLACK
	ZERO?	FIRST-WARNING? \?PRG11
	RANDOM	100
	LESS?	50,STACK /?CND7
?PRG11:	PRINTI	" You are likely to be eaten by a grue."
	SET	'FIRST-WARNING?,FALSE-VALUE
?CND7:	CRLF	
	RFALSE	
?CCL29:	GETP	HERE,P?ACTION
	CALL	STACK,M-FLASH
?CND23:	EQUAL?	HERE,AV /TRUE
	FSET?	AV,VEHBIT \TRUE
	GETP	AV,P?ACTION
	CALL	STACK,M-LOOK
	RTRUE	


	.FUNCT	GOTO,RM,V?=1,OLIT,OHERE
	SET	'OHERE,HERE
	SET	'OLIT,LIT
	MOVE	WINNER,RM
	SET	'HERE,RM
	CALL	LIT?,HERE >LIT
	ZERO?	OLIT \?CND1
	ZERO?	LIT \?CND1
	ZERO?	FIRST-WARNING? \?CND1
	RANDOM	100
	LESS?	50,STACK /?CND1
	PRINTI	"Oh, no! Something lurked out of the darkness and devoured you!"
	CRLF	
	CALL	FINISH
?CND1:	GETP	HERE,P?ACTION
	CALL	STACK,M-ENTER
	EQUAL?	HERE,RM \TRUE
	ZERO?	V? /TRUE
	CALL	V-FIRST-LOOK
	RTRUE	


	.FUNCT	OTHER-SIDE,DOBJ,P=0,T
?PRG1:	NEXTP	HERE,P >P
	LESS?	P,LOW-DIRECTION /FALSE
	GETPT	HERE,P >T
	PTSIZE	T
	EQUAL?	STACK,DEXIT \?PRG1
	GETB	T,DEXITOBJ
	EQUAL?	STACK,DOBJ \?PRG1
	RETURN	P


	.FUNCT	HACK-HACK,STR
	PRINT	STR
	PRINTC	32
	CALL	ARTICLE,PRSO,TRUE-VALUE
	PRINTD	PRSO
	PRINTC	32
	CALL	PICK-ONE,HO-HUM
	PRINT	STACK
	PRINTR	"."


	.FUNCT	TOO-DARK
	PRINTR	"It's too dark to see!"


	.FUNCT	CANT-GO
	FSET?	HERE,INDOORSBIT \?PRG6
	PRINTI	"There's no exit"
	JUMP	?PRG8
?PRG6:	PRINT	CANT
	PRINTI	" go"
?PRG8:	PRINTR	" that way."


	.FUNCT	NOW-BLACK
	PRINTI	"It is pitch black."
	RTRUE	


	.FUNCT	ALREADY-OPEN
	CALL	ITS-ALREADY,STR?62
	RSTACK	


	.FUNCT	ALREADY-CLOSED
	CALL	ITS-ALREADY,STR?76
	RSTACK	


	.FUNCT	ITS-ALREADY,STR
	PRINTI	"It's already "
	PRINT	STR
	PRINTR	"."


	.FUNCT	REFERRING
	PRINTR	"(Please be more specific.)"


	.FUNCT	WASTE-OF-TIME
	PRINTI	"That would be a "
	CALL	PICK-ONE,USELESSNESS
	PRINT	STACK
	PRINTR	"."

	.ENDI
