	.INSERT "PS:<INTERLOGIC.GENERIC>GDAT"	; Data file
	.INSERT "PS:<INTERLOGIC.GENERIC>GPUR"
	.INSERT "PS:<INTERLOGIC.GENERIC>G-MISC"
	.INSERT "PS:<INTERLOGIC.GENERIC>G-PARSER"
	.INSERT "PS:<INTERLOGIC.GENERIC>G-GLOBALS"
	.INSERT "PS:<INTERLOGIC.GENERIC>G-SYNTAX"
	.INSERT "PS:<INTERLOGIC.GENERIC>G-VERBS"
	.INSERT "PS:<INTERLOGIC.GENERIC>G-ROOMS"

	.INSERT "PS:<INTERLOGIC.GENERIC>GSTR"

	.END
