

; STRINGS ARE DEFINED HERE

STRBEG::

	.GSTR STR?1,"Not Here"
	.GSTR STR?2,"Actor"
	.GSTR STR?3,"Room (M-BEG)"
	.GSTR STR?4,"Preaction"
	.GSTR STR?5,"PRSI"
	.GSTR STR?6,"PRSO"
	.GSTR STR?7,"Room (M-END)"
	.GSTR STR?8,"Container"
	.GSTR STR?9,"locate"
	.GSTR STR?10,"FIND"
	.GSTR STR?11,"ask about"
	.GSTR STR?12,"ASK CHARACTER ABOUT"
	.GSTR STR?13,"What charming language"
	.GSTR STR?14,"Computers aren't impressed by naughty words"
	.GSTR STR?15,"Grow up"
	.GSTR STR?16,"This story doesn't know the word """
	.GSTR STR?17,"."""
	.GSTR STR?18,"Sorry, but the word """
	.GSTR STR?19,""" is not in the vocabulary that you can use."
	.GSTR STR?20,"You don't need to use the word """
	.GSTR STR?21,""" to finish this story."
	.GSTR STR?22,"Sorry, but this story doesn't recognize the word """
	.GSTR STR?23,"any verbs"
	.GSTR STR?24,"enough nouns [1]"
	.GSTR STR?25,"enough nouns [2]"
	.GSTR STR?26,"You can see "
	.GSTR STR?27,"F"
	.GSTR STR?28,"L"
	.GSTR STR?29," isn't likely"
	.GSTR STR?30," seems doubtful"
	.GSTR STR?31," seems unlikely"
	.GSTR STR?32,"'s unlikely"
	.GSTR STR?33,"'s not likely"
	.GSTR STR?34,"'s doubtful"
	.GSTR STR?35,"(Presumably, you mean"
	.GSTR STR?36,"You can't"
	.GSTR STR?37,"Okay, "
	.GSTR STR?38,"begin"
	.GSTR STR?39,"end"
	.GSTR STR?40,"would respond"
	.GSTR STR?41,"Biting"
	.GSTR STR?42,"Blowing"
	.GSTR STR?43,"would buy that"
	.GSTR STR?44,"janitor"
	.GSTR STR?45,"surgeon"
	.GSTR STR?46,"could cut anything"
	.GSTR STR?47,"would agree with you"
	.GSTR STR?48,"WEAR"
	.GSTR STR?49,"Kicking"
	.GSTR STR?50,"close"
	.GSTR STR?51,"Trying to destroy"
	.GSTR STR?52,"Playing with"
	.GSTR STR?53,"locksmith"
	.GSTR STR?54,"Pulling on"
	.GSTR STR?55,"Pushing around"
	.GSTR STR?56,"Toying in this way with"
	.GSTR STR?57,"would appreciate your reading"
	.GSTR STR?58,"is interested"
	.GSTR STR?59,"wants to play piggyback"
	.GSTR STR?60,"Fiddling with"
	.GSTR STR?61,"Paying respect to"
	.GSTR STR?62,"open"
	.GSTR STR?63,"unusual"
	.GSTR STR?64,"interesting"
	.GSTR STR?65,"extraordinary"
	.GSTR STR?66,"special"
	.GSTR STR?67,"Shaking"
	.GSTR STR?68,"Turning"
	.GSTR STR?69,"WALK TO"
	.GSTR STR?70,"doesn't do anything"
	.GSTR STR?71,"accomplishes nothing"
	.GSTR STR?72,"has no effect"
	.GSTR STR?73,"That's impossible."
	.GSTR STR?74,"You can't be serious."
	.GSTR STR?75,"Don't be silly."
	.GSTR STR?76,"closed"
	.GSTR STR?77,"waste of time"
	.GSTR STR?78,"useless effort"
	.GSTR STR?79,"pointless thing to do"
	.GSTR STR?80,"You're in a room."
	.GSTR STR?81,"You're in another room."

	.ENDI
