from dataclasses import dataclass
from typing import List, Tuple, Union


@dataclass
class Opcodes:
    name: str
    versions: Union[str, List[int]]
    opcode_bytes: Tuple[int, int]
    store: bool = False

    def __init__(
        self,
        name: str,
        versions: Union[str, List[int]],
        opcode_bytes: Tuple[int, int],
        store: bool = False,
    ):
        if versions == "all":
            self.versions = [1, 2, 3, 4, 5, 6, 7, 8]
        else:
            self.versions = versions
        self.name = name
        self.opcode_bytes = opcode_bytes
        self.store = store

    def matches(self, version: int, opcode_byte: int, opcode_number: int) -> bool:
        return (
            version in self.versions
            and (opcode_byte, opcode_number) == self.opcode_bytes
        )


opcodes = [
    # 0OP
    Opcodes(name="rtrue", versions="all", opcode_bytes=(176, 0)),
    Opcodes(name="rfalse", versions="all", opcode_bytes=(177, 1)),
    Opcodes(name="print", versions="all", opcode_bytes=(178, 2)),
    Opcodes(name="print_ret", versions="all", opcode_bytes=(179, 3)),
    Opcodes(name="nop", versions="all", opcode_bytes=(180, 4)),
    Opcodes(name="save", versions=[1, 2, 3, 4], opcode_bytes=(181, 5)),
    Opcodes(name="restore", versions=[1, 2, 3, 4], opcode_bytes=(182, 6)),
    Opcodes(name="restart", versions="all", opcode_bytes=(183, 7)),
    Opcodes(name="ret_popped", versions="all", opcode_bytes=(184, 8)),
    Opcodes(name="pop", versions=[1, 2, 3, 4], opcode_bytes=(185, 9)),
    Opcodes(name="catch", versions=[5, 6, 7, 8], opcode_bytes=(185, 9), store=True),
    Opcodes(name="quit", versions="all", opcode_bytes=(186, 10)),
    Opcodes(name="new_line", versions="all", opcode_bytes=(187, 11)),
    Opcodes(name="show_status", versions=[3], opcode_bytes=(188, 12)),
    Opcodes(name="verify", versions=[3, 4, 5, 6, 7, 8], opcode_bytes=(189, 13)),
    # (190,14) is used for the first byte of extended opcode
    Opcodes(name="piracy", versions=[5, 6, 7, 8], opcode_bytes=(191, 15)),
    # 1OP
    Opcodes(name="jz", versions="all", opcode_bytes=(128, 0)),
    Opcodes(name="jz", versions="all", opcode_bytes=(144, 0)),
    Opcodes(name="jz", versions="all", opcode_bytes=(160, 0)),
    Opcodes(name="get_sibling", versions="all", opcode_bytes=(129, 1), store=True),
    Opcodes(name="get_sibling", versions="all", opcode_bytes=(145, 1), store=True),
    Opcodes(name="get_sibling", versions="all", opcode_bytes=(161, 1), store=True),
    Opcodes(name="get_child", versions="all", opcode_bytes=(130, 2), store=True),
    Opcodes(name="get_child", versions="all", opcode_bytes=(146, 2), store=True),
    Opcodes(name="get_child", versions="all", opcode_bytes=(162, 2), store=True),
    Opcodes(name="get_parent", versions="all", opcode_bytes=(131, 3), store=True),
    Opcodes(name="get_parent", versions="all", opcode_bytes=(147, 3), store=True),
    Opcodes(name="get_parent", versions="all", opcode_bytes=(163, 3), store=True),
    Opcodes(name="get_prop_len", versions="all", opcode_bytes=(132, 4), store=True),
    Opcodes(name="get_prop_len", versions="all", opcode_bytes=(148, 4), store=True),
    Opcodes(name="get_prop_len", versions="all", opcode_bytes=(164, 4), store=True),
    Opcodes(name="inc", versions="all", opcode_bytes=(133, 5)),
    Opcodes(name="inc", versions="all", opcode_bytes=(149, 5)),
    Opcodes(name="inc", versions="all", opcode_bytes=(165, 5)),
    Opcodes(name="dec", versions="all", opcode_bytes=(134, 6)),
    Opcodes(name="dec", versions="all", opcode_bytes=(150, 6)),
    Opcodes(name="dec", versions="all", opcode_bytes=(166, 6)),
    Opcodes(name="print_addr", versions="all", opcode_bytes=(135, 7)),
    Opcodes(name="print_addr", versions="all", opcode_bytes=(151, 7)),
    Opcodes(name="print_addr", versions="all", opcode_bytes=(167, 7)),
    Opcodes(
        name="call_1s", versions=[4, 5, 6, 7, 8], opcode_bytes=(136, 8), store=True
    ),
    Opcodes(name="call_1s", versions="all", opcode_bytes=(152, 8), store=True),
    Opcodes(name="call_1s", versions="all", opcode_bytes=(168, 8), store=True),
    Opcodes(name="remove_obj", versions="all", opcode_bytes=(137, 9)),
    Opcodes(name="remove_obj", versions="all", opcode_bytes=(153, 9)),
    Opcodes(name="remove_obj", versions="all", opcode_bytes=(169, 9)),
    Opcodes(name="print_obj", versions="all", opcode_bytes=(138, 10)),
    Opcodes(name="print_obj", versions="all", opcode_bytes=(154, 10)),
    Opcodes(name="print_obj", versions="all", opcode_bytes=(170, 10)),
    Opcodes(name="ret", versions="all", opcode_bytes=(139, 11)),
    Opcodes(name="ret", versions="all", opcode_bytes=(155, 11)),
    Opcodes(name="ret", versions="all", opcode_bytes=(171, 11)),
    Opcodes(name="jump", versions="all", opcode_bytes=(140, 12)),
    Opcodes(name="jump", versions="all", opcode_bytes=(156, 12)),
    Opcodes(name="jump", versions="all", opcode_bytes=(172, 12)),
    Opcodes(name="print_paddr", versions="all", opcode_bytes=(141, 13)),
    Opcodes(name="print_paddr", versions="all", opcode_bytes=(157, 13)),
    Opcodes(name="print_paddr", versions="all", opcode_bytes=(173, 13)),
    Opcodes(name="load", versions="all", opcode_bytes=(142, 14), store=True),
    Opcodes(name="load", versions="all", opcode_bytes=(158, 14), store=True),
    Opcodes(name="load", versions="all", opcode_bytes=(174, 14), store=True),
    Opcodes(name="not", versions=[1, 2, 3, 4], opcode_bytes=(143, 15), store=True),
    Opcodes(name="call_1n", versions=[5, 6, 7, 8], opcode_bytes=(159, 15)),
    Opcodes(name="call_1n", versions="all", opcode_bytes=(175, 15)),
    # 2OP
    Opcodes(name="je", versions="all", opcode_bytes=(1, 1)),
    Opcodes(name="je", versions="all", opcode_bytes=(33, 1)),
    Opcodes(name="je", versions="all", opcode_bytes=(65, 1)),
    Opcodes(name="je", versions="all", opcode_bytes=(97, 1)),
    Opcodes(name="je", versions="all", opcode_bytes=(193, 1)),
    Opcodes(name="jl", versions="all", opcode_bytes=(2, 2)),
    Opcodes(name="jl", versions="all", opcode_bytes=(34, 2)),
    Opcodes(name="jl", versions="all", opcode_bytes=(66, 2)),
    Opcodes(name="jl", versions="all", opcode_bytes=(98, 2)),
    Opcodes(name="jl", versions="all", opcode_bytes=(194, 2)),
    Opcodes(name="jg", versions="all", opcode_bytes=(3, 3)),
    Opcodes(name="jg", versions="all", opcode_bytes=(35, 3)),
    Opcodes(name="jg", versions="all", opcode_bytes=(67, 3)),
    Opcodes(name="jg", versions="all", opcode_bytes=(99, 3)),
    Opcodes(name="jg", versions="all", opcode_bytes=(195, 3)),
    Opcodes(name="dec_chk", versions="all", opcode_bytes=(4, 4)),
    Opcodes(name="dec_chk", versions="all", opcode_bytes=(36, 4)),
    Opcodes(name="dec_chk", versions="all", opcode_bytes=(68, 4)),
    Opcodes(name="dec_chk", versions="all", opcode_bytes=(100, 4)),
    Opcodes(name="dec_chk", versions="all", opcode_bytes=(196, 4)),
    Opcodes(name="inc_chk", versions="all", opcode_bytes=(5, 5)),
    Opcodes(name="inc_chk", versions="all", opcode_bytes=(37, 5)),
    Opcodes(name="inc_chk", versions="all", opcode_bytes=(69, 5)),
    Opcodes(name="inc_chk", versions="all", opcode_bytes=(101, 5)),
    Opcodes(name="inc_chk", versions="all", opcode_bytes=(197, 5)),
    Opcodes(name="jin", versions="all", opcode_bytes=(6, 6)),
    Opcodes(name="jin", versions="all", opcode_bytes=(38, 6)),
    Opcodes(name="jin", versions="all", opcode_bytes=(70, 6)),
    Opcodes(name="jin", versions="all", opcode_bytes=(102, 6)),
    Opcodes(name="jin", versions="all", opcode_bytes=(198, 6)),
    Opcodes(name="test", versions="all", opcode_bytes=(7, 7)),
    Opcodes(name="test", versions="all", opcode_bytes=(39, 7)),
    Opcodes(name="test", versions="all", opcode_bytes=(71, 7)),
    Opcodes(name="test", versions="all", opcode_bytes=(103, 7)),
    Opcodes(name="test", versions="all", opcode_bytes=(199, 7)),
    Opcodes(name="or", versions="all", opcode_bytes=(8, 8), store=True),
    Opcodes(name="or", versions="all", opcode_bytes=(40, 8), store=True),
    Opcodes(name="or", versions="all", opcode_bytes=(72, 8), store=True),
    Opcodes(name="or", versions="all", opcode_bytes=(104, 8), store=True),
    Opcodes(name="or", versions="all", opcode_bytes=(200, 8), store=True),
    Opcodes(name="and", versions="all", opcode_bytes=(9, 9), store=True),
    Opcodes(name="and", versions="all", opcode_bytes=(41, 9), store=True),
    Opcodes(name="and", versions="all", opcode_bytes=(73, 9), store=True),
    Opcodes(name="and", versions="all", opcode_bytes=(105, 9), store=True),
    Opcodes(name="and", versions="all", opcode_bytes=(201, 9), store=True),
    Opcodes(name="test_attr", versions="all", opcode_bytes=(10, 10)),
    Opcodes(name="test_attr", versions="all", opcode_bytes=(42, 10)),
    Opcodes(name="test_attr", versions="all", opcode_bytes=(74, 10)),
    Opcodes(name="test_attr", versions="all", opcode_bytes=(106, 10)),
    Opcodes(name="test_attr", versions="all", opcode_bytes=(202, 10)),
    Opcodes(name="set_attr", versions="all", opcode_bytes=(11, 11)),
    Opcodes(name="set_attr", versions="all", opcode_bytes=(43, 11)),
    Opcodes(name="set_attr", versions="all", opcode_bytes=(75, 11)),
    Opcodes(name="set_attr", versions="all", opcode_bytes=(107, 11)),
    Opcodes(name="set_attr", versions="all", opcode_bytes=(203, 11)),
    Opcodes(name="clear_attr", versions="all", opcode_bytes=(12, 12)),
    Opcodes(name="clear_attr", versions="all", opcode_bytes=(44, 12)),
    Opcodes(name="clear_attr", versions="all", opcode_bytes=(76, 12)),
    Opcodes(name="clear_attr", versions="all", opcode_bytes=(108, 12)),
    Opcodes(name="clear_attr", versions="all", opcode_bytes=(204, 12)),
    Opcodes(name="store", versions="all", opcode_bytes=(13, 13)),
    Opcodes(name="store", versions="all", opcode_bytes=(45, 13)),
    Opcodes(name="store", versions="all", opcode_bytes=(77, 13)),
    Opcodes(name="store", versions="all", opcode_bytes=(109, 13)),
    Opcodes(name="store", versions="all", opcode_bytes=(205, 13)),
    Opcodes(name="insert_obj", versions="all", opcode_bytes=(14, 14)),
    Opcodes(name="insert_obj", versions="all", opcode_bytes=(46, 14)),
    Opcodes(name="insert_obj", versions="all", opcode_bytes=(78, 14)),
    Opcodes(name="insert_obj", versions="all", opcode_bytes=(110, 14)),
    Opcodes(name="insert_obj", versions="all", opcode_bytes=(206, 14)),
    Opcodes(name="loadw", versions="all", opcode_bytes=(15, 15), store=True),
    Opcodes(name="loadw", versions="all", opcode_bytes=(47, 15), store=True),
    Opcodes(name="loadw", versions="all", opcode_bytes=(79, 15), store=True),
    Opcodes(name="loadw", versions="all", opcode_bytes=(111, 15), store=True),
    Opcodes(name="loadw", versions="all", opcode_bytes=(207, 15), store=True),
    Opcodes(name="loadb", versions="all", opcode_bytes=(16, 16), store=True),
    Opcodes(name="loadb", versions="all", opcode_bytes=(48, 16), store=True),
    Opcodes(name="loadb", versions="all", opcode_bytes=(80, 16), store=True),
    Opcodes(name="loadb", versions="all", opcode_bytes=(112, 16), store=True),
    Opcodes(name="loadb", versions="all", opcode_bytes=(208, 16), store=True),
    Opcodes(name="get_prop", versions="all", opcode_bytes=(17, 17), store=True),
    Opcodes(name="get_prop", versions="all", opcode_bytes=(49, 17), store=True),
    Opcodes(name="get_prop", versions="all", opcode_bytes=(81, 17), store=True),
    Opcodes(name="get_prop", versions="all", opcode_bytes=(113, 17), store=True),
    Opcodes(name="get_prop", versions="all", opcode_bytes=(209, 17), store=True),
    Opcodes(name="get_prop_addr", versions="all", opcode_bytes=(18, 18), store=True),
    Opcodes(name="get_prop_addr", versions="all", opcode_bytes=(50, 18), store=True),
    Opcodes(name="get_prop_addr", versions="all", opcode_bytes=(82, 18), store=True),
    Opcodes(name="get_prop_addr", versions="all", opcode_bytes=(114, 18), store=True),
    Opcodes(name="get_prop_addr", versions="all", opcode_bytes=(210, 18), store=True),
    Opcodes(name="get_next_prop", versions="all", opcode_bytes=(19, 19), store=True),
    Opcodes(name="get_next_prop", versions="all", opcode_bytes=(51, 19), store=True),
    Opcodes(name="get_next_prop", versions="all", opcode_bytes=(83, 19), store=True),
    Opcodes(name="get_next_prop", versions="all", opcode_bytes=(115, 19), store=True),
    Opcodes(name="get_next_prop", versions="all", opcode_bytes=(211, 19), store=True),
    Opcodes(name="add", versions="all", opcode_bytes=(20, 20), store=True),
    Opcodes(name="add", versions="all", opcode_bytes=(52, 20), store=True),
    Opcodes(name="add", versions="all", opcode_bytes=(84, 20), store=True),
    Opcodes(name="add", versions="all", opcode_bytes=(116, 20), store=True),
    Opcodes(name="add", versions="all", opcode_bytes=(212, 20), store=True),
    Opcodes(name="sub", versions="all", opcode_bytes=(21, 21), store=True),
    Opcodes(name="sub", versions="all", opcode_bytes=(53, 21), store=True),
    Opcodes(name="sub", versions="all", opcode_bytes=(85, 21), store=True),
    Opcodes(name="sub", versions="all", opcode_bytes=(117, 21), store=True),
    Opcodes(name="sub", versions="all", opcode_bytes=(213, 21), store=True),
    Opcodes(name="mul", versions="all", opcode_bytes=(22, 22), store=True),
    Opcodes(name="mul", versions="all", opcode_bytes=(54, 22), store=True),
    Opcodes(name="mul", versions="all", opcode_bytes=(86, 22), store=True),
    Opcodes(name="mul", versions="all", opcode_bytes=(118, 22), store=True),
    Opcodes(name="mul", versions="all", opcode_bytes=(214, 22), store=True),
    Opcodes(name="div", versions="all", opcode_bytes=(23, 23), store=True),
    Opcodes(name="div", versions="all", opcode_bytes=(55, 23), store=True),
    Opcodes(name="div", versions="all", opcode_bytes=(87, 23), store=True),
    Opcodes(name="div", versions="all", opcode_bytes=(119, 23), store=True),
    Opcodes(name="div", versions="all", opcode_bytes=(215, 23), store=True),
    Opcodes(name="mod", versions="all", opcode_bytes=(24, 24), store=True),
    Opcodes(name="mod", versions="all", opcode_bytes=(56, 24), store=True),
    Opcodes(name="mod", versions="all", opcode_bytes=(88, 24), store=True),
    Opcodes(name="mod", versions="all", opcode_bytes=(120, 24), store=True),
    Opcodes(name="mod", versions="all", opcode_bytes=(216, 24), store=True),
    Opcodes(name="call_2s", versions=[4, 5, 6, 7, 8], opcode_bytes=(25, 25)),
    Opcodes(name="call_2s", versions="all", opcode_bytes=(57, 25), store=True),
    Opcodes(name="call_2s", versions="all", opcode_bytes=(89, 25), store=True),
    Opcodes(name="call_2s", versions="all", opcode_bytes=(121, 25), store=True),
    Opcodes(name="call_2s", versions="all", opcode_bytes=(217, 25), store=True),
    Opcodes(name="call_2n", versions=[5, 6, 7, 8], opcode_bytes=(26, 26)),
    Opcodes(name="call_2n", versions="all", opcode_bytes=(58, 26)),
    Opcodes(name="call_2n", versions="all", opcode_bytes=(90, 26)),
    Opcodes(name="call_2n", versions="all", opcode_bytes=(122, 26)),
    Opcodes(name="call_2n", versions="all", opcode_bytes=(218, 26)),
    Opcodes(name="set_colour", versions=[5, 6, 7, 8], opcode_bytes=(27, 27)),
    Opcodes(name="set_colour", versions=[6, 7, 8], opcode_bytes=(59, 27)),
    Opcodes(name="set_colour", versions="all", opcode_bytes=(91, 27)),
    Opcodes(name="set_colour", versions="all", opcode_bytes=(123, 27)),
    Opcodes(name="set_colour", versions="all", opcode_bytes=(219, 27)),
    Opcodes(name="throw", versions=[5, 6, 7, 8], opcode_bytes=(28, 28)),
    Opcodes(name="throw", versions="all", opcode_bytes=(60, 28)),
    Opcodes(name="throw", versions="all", opcode_bytes=(92, 28)),
    Opcodes(name="throw", versions="all", opcode_bytes=(124, 28)),
    Opcodes(name="throw", versions="all", opcode_bytes=(220, 28)),
    # VAR
    Opcodes(name="call", versions=[1, 2, 3], opcode_bytes=(224, 0), store=True),
    Opcodes(name="call_vs", versions=[4, 5, 6, 7, 8], opcode_bytes=(224, 0)),
    Opcodes(name="storew", versions="all", opcode_bytes=(225, 1)),
    Opcodes(name="storeb", versions="all", opcode_bytes=(226, 2)),
    Opcodes(name="put_prop", versions="all", opcode_bytes=(227, 3)),
    Opcodes(name="sread", versions=[1, 2, 3, 4], opcode_bytes=(228, 4)),
    Opcodes(name="aread", versions=[5, 6, 7, 8], opcode_bytes=(228, 4), store=True),
    Opcodes(name="print_char", versions="all", opcode_bytes=(229, 5)),
    Opcodes(name="print_num", versions="all", opcode_bytes=(230, 6)),
    Opcodes(name="random", versions="all", opcode_bytes=(231, 7), store=True),
    Opcodes(name="push", versions="all", opcode_bytes=(232, 8)),
    # NOTE: Version 6 version of pull stores; prior versions do not.
    # This may become problematic.
    Opcodes(name="pull", versions="all", opcode_bytes=(233, 9), store=True),
    Opcodes(name="split_window", versions=[3, 4, 5, 6, 7, 8], opcode_bytes=(234, 10)),
    Opcodes(name="set_window", versions=[3, 4, 5, 6, 7, 8], opcode_bytes=(235, 11)),
    Opcodes(
        name="call_vs2", versions=[4, 5, 6, 7, 8], opcode_bytes=(236, 12), store=True
    ),
    Opcodes(name="erase_window", versions=[4, 5, 6, 7, 8], opcode_bytes=(237, 13)),
    Opcodes(name="erase_line", versions=[4, 5, 6, 7, 8], opcode_bytes=(238, 14)),
    Opcodes(name="set_cursor", versions=[4, 5, 6, 7, 8], opcode_bytes=(239, 15)),
    Opcodes(name="get_cursor", versions=[4, 5, 6, 7, 8], opcode_bytes=(240, 16)),
    Opcodes(name="set_text_style", versions=[4, 5, 6, 7, 8], opcode_bytes=(241, 17)),
    Opcodes(name="buffer_mode", versions=[4, 5, 6, 7, 8], opcode_bytes=(242, 18)),
    Opcodes(name="output_stream", versions=[3, 4, 5, 6, 7, 8], opcode_bytes=(243, 19)),
    Opcodes(name="input_stream", versions=[3, 4, 5, 6, 7, 8], opcode_bytes=(244, 20)),
    Opcodes(name="sound_effect", versions=[3, 4, 5, 6, 7, 8], opcode_bytes=(245, 21)),
    Opcodes(
        name="read_char", versions=[4, 5, 6, 7, 8], opcode_bytes=(246, 22), store=True
    ),
    Opcodes(
        name="scan_table", versions=[4, 5, 6, 7, 8], opcode_bytes=(247, 23), store=True
    ),
    Opcodes(name="not", versions=[5, 6, 7, 8], opcode_bytes=(248, 24), store=True),
    Opcodes(name="call_vn", versions=[1, 2, 3], opcode_bytes=(249, 25)),
    Opcodes(name="call_vn2", versions=[5, 6, 7, 8], opcode_bytes=(250, 26)),
    Opcodes(name="tokenise", versions=[5, 6, 7, 8], opcode_bytes=(251, 27)),
    Opcodes(name="encode_text", versions=[5, 6, 7, 8], opcode_bytes=(252, 28)),
    Opcodes(name="copy_table", versions=[5, 6, 7, 8], opcode_bytes=(253, 29)),
    Opcodes(name="print_table", versions=[5, 6, 7, 8], opcode_bytes=(254, 30)),
    Opcodes(name="check_arg_count", versions=[5, 6, 7, 8], opcode_bytes=(255, 31)),
    # EXT
    Opcodes(name="save", versions="all", opcode_bytes=(0, 0), store=True),
    Opcodes(name="restore", versions=[5, 6, 7, 8], opcode_bytes=(1, 1), store=True),
    Opcodes(name="log_shift", versions=[5, 6, 7, 8], opcode_bytes=(2, 2), store=True),
    Opcodes(name="art_shift", versions=[5, 6, 7, 8], opcode_bytes=(3, 3), store=True),
    Opcodes(name="set_font", versions=[5, 6, 7, 8], opcode_bytes=(4, 4), store=True),
    Opcodes(name="draw_picture", versions=[6, 7, 8], opcode_bytes=(5, 5)),
    Opcodes(name="picture_data", versions=[6, 7, 8], opcode_bytes=(6, 6)),
    Opcodes(name="erase_picture", versions=[6, 7, 8], opcode_bytes=(7, 7)),
    Opcodes(name="set_margins", versions=[6, 7, 8], opcode_bytes=(8, 8)),
    Opcodes(name="save_undo", versions=[5, 6, 7, 8], opcode_bytes=(9, 9), store=True),
    Opcodes(
        name="restore_undo", versions=[5, 6, 7, 8], opcode_bytes=(10, 10), store=True
    ),
    Opcodes(name="print_unicode", versions=[5, 6, 7, 8], opcode_bytes=(11, 11)),
    Opcodes(name="check_unicode", versions=[5, 6, 7, 8], opcode_bytes=(12, 12)),
    Opcodes(name="set_true_colour", versions=[5, 6, 7, 8], opcode_bytes=(13, 13)),
    # (14, 14) and (15, 15) are unspecified
    Opcodes(name="move_window", versions=[6, 7, 8], opcode_bytes=(16, 16)),
    Opcodes(name="window_size", versions=[6, 7, 8], opcode_bytes=(17, 17)),
    Opcodes(name="window_style", versions=[6, 7, 8], opcode_bytes=(18, 18)),
    Opcodes(
        name="get_wind_prop", versions=[6, 7, 8], opcode_bytes=(19, 19), store=True
    ),
    Opcodes(name="scroll_window", versions=[6, 7, 8], opcode_bytes=(20, 20)),
    Opcodes(name="pop_stack", versions=[6, 7, 8], opcode_bytes=(21, 21)),
    Opcodes(name="read_mouse", versions=[6, 7, 8], opcode_bytes=(22, 22)),
    Opcodes(name="mouse_window", versions=[6, 7, 8], opcode_bytes=(23, 23)),
    Opcodes(name="push_stack", versions=[6, 7, 8], opcode_bytes=(24, 24)),
    Opcodes(name="put_wind_prop", versions=[6, 7, 8], opcode_bytes=(25, 25)),
    Opcodes(name="print_form", versions=[6, 7, 8], opcode_bytes=(26, 26)),
    Opcodes(name="make_menu", versions=[6, 7, 8], opcode_bytes=(27, 27)),
    Opcodes(name="picture_table", versions=[6, 7, 8], opcode_bytes=(28, 28)),
    Opcodes(
        name="buffer_screen", versions=[6, 7, 8], opcode_bytes=(29, 29), store=True
    ),
]
